### ISSUE TITLE
MEGAsync for linux should use the new Cloud Providers API for file manager integration

### ISSUE THREAD

**Issue by micahilbery** [meganz/MEGAsync#1]
To integrate with linux file managers (not just nautilus, but including nautilus) you can use the Cloud Providers API shown <a href="https://csorianognome.wordpress.com/2015/07/07/cloud-providers/" target= "blank">here</a>

**Comment by javiserrano** [comment]
We have already worked on the implementation of extensions for Dolphin and Thunar (and the code is in the repo) but they aren't ready for production yet.

When we finish other tasks with a higher priority in which we are currently working on, we will evaluate if it's better to use that API than finishing those extensions.

Thank you!
