### ISSUE TITLE
Check for updates always fails

### ISSUE THREAD

**Issue by sidorov-alex** [meganz/MEGAsync#1001]
Check for updates button doesn't work. Result is always "no updates available at the moment". For many years. I have updated manually. There is part of the log:

```
INFO Starting update check
10/04-10:21:32.616328 17184 DBG  Downloading updated file from http://g.static.mega.co.nz/upd/wsync64/v.txt?PHQGHUMEAY
10/04-10:21:33.033210 17184 ERR  Unable to download file
10/04-10:21:33.033216 17184 INFO Update task finished. No updates available
```

> http://g.static.mega.co.nz/upd/wsync64/v.txt?PHQGHUMEAY
THIS URL IS 404 Not Found

And as you know winget upgrade [does not work too.](https://github.com/meganz/MEGAsync/issues/786#issue-1611509108)

**Comment by FIFER-Mods** [comment]
Yes I have the same issue

**Comment by vtmateos** [comment]
Hi there,
Auto update rollout is delivered on incremental stages during some weeks timeframe. You will receive it soon.
Regards.
