### ISSUE TITLE
"The backup has been externally modified."

### ISSUE THREAD

**Issue by perigozin** [meganz/MEGAsync#1002]
I constantly get this message for no apparent reason for a backup of an entire drive.
I have to keep activating the backup again and again.

**Comment by emj04** [comment]
This is happening to me too (Fedora 41, MegaSync 5.2.1). When I turn the backup back on recently modified files fail to upload with the error "Failed: Access denied".

**Comment by perigozin** [comment]
My issue was I had an older version of mega (4.x.x) for months because I thought it was auto-updating. Updated to the newer version (5.6.0) and this issue is gone.
