### ISSUE TITLE
Global `.megaignore.default` filters not working

### ISSUE THREAD

**Issue by redactedscribe** [meganz/MEGAsync#1009]
In %LOCALAPPDATA%\Mega Limited\MEGAsync\\.megaignore.default, if you have for example:

```
-f:hello123.txt
```

Adding a hello123.txt file to a MEGA synchronised folder will wrongly cause it to be sent to the cloud. It looks like both the glob and regexp strategies are ignored, in other words, no filters work.

I was assuming this file would be taken into account across all full / selective syncs, and a folder's own .megaignore to add filters on top of it, but it appears .megaignore.default is having no effect at all.

Adding `-f:hello123.txt` to a folder's own .megaignore file will however prevent it from being uploaded. Only the global .megaignore.default appears broken.

Any idea? Thanks.

v5.5.0, Windows

**Comment by mattw-mattw** [comment]
That file's purpose is to supply the initial filters when a new sync is created.  It doesn't affect existing syncs.   If you need to add a new filter line to all your existing syncs, there should be a GUI assist for that.  cheers
