### ISSUE TITLE
megadesignassets submodule is inaccessible 

### ISSUE THREAD

**Issue by KottV** [meganz/MEGAsync#1010]
Hi,

If I try to clone the source recursively or update submodules, then this path (git@code.developers.mega.co.nz:megadesignassets/megadesignassets.git) seems has restricted access:
`ssh: connect to host code.developers.mega.co.nz port 22: Connection timed out`

Not sure if it's required, as there is `ENABLE_DESIGN_TOKENS_IMPORTER` option, but it breaks automated builds which pull the source from GH.

**Comment by vtmateos** [comment]
Hi,
The `megadesignassets` repository is an internal repository that contains various design tokens for the application. The Design token importer serves as a parser tool to generate artifacts and assets used during the application's build process using those designs. 

We have two options: either disable it as a submodule and hide the tool (it's not necessary) or publish the `megadesignassets` repository on GitHub and update the paths in the `.gitmodules` file accordingly.

Meanwhile, you can discard that error and switch `ENABLE_DESIGN_TOKENS_IMPORTER to OFF` in CMake file. Try again and let us know how the process goes.

Thanks.

**Comment by KottV** [comment]
Maybe it's possible to put this dependency inside the cmake? So, if it's enable the pull and use (with fetchcontent or git directly or any).

**Comment by vtmateos** [comment]
Thanks for the suggestion. You're right we will clone on demand if the DESIGN-TOKENS cmake option is enabled.
We will add it on a next version.

**Comment by hackerncoder** [comment]
Hello, the megadesignassets folder is still [in the git index as a submodule](https://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule/4185579#4185579), which means that running `git submodule update --init` will error out with `fatal: No url found for submodule path 'src/DesignTokensImporter/megadesignassets' in .gitmodules`

**Comment by KottV** [comment]
Yes, it seems not fully deleted. I had to run `git rm --cached src/DesignTokensImporter/megadesignassets` to solve that.
