### ISSUE TITLE
Error 404 on Fedora 41 repository?

### ISSUE THREAD

**Issue by basilpolicy** [meganz/MEGAsync#1012]
Hi
Latest F41 KDE with Megasync returns following error on dnf. Assumeing repo's are not active yet?

 MEGAsync                                                                                                                                           ???% |   0.0   B/s |   0.0   B |  00m03s
>>> Status code: 404 for https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml (IP: 31.216.144.5) - https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml (IP: 31.216.144.5) - https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml (IP: 31.216.144.5) - https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml (IP: 31.216.144.5) - https://mega.nz/linux/repo/Fedora_41/repodata/repomd.xml - repomd.xml
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by themateus** [comment]
It's happening here too

**Comment by rafatosta** [comment]
Fedora 41 was released yesterday. Wait a while!
