### ISSUE TITLE
Old version of mega on the official website?

### ISSUE THREAD

**Issue by RKI91** [meganz/MEGAsync#1015]
The case concerns the official megasync (Windows version) download page: **https://mega.io/desktop**
Yesterday (06.11.2024) version **5.6.0** was available for download and today (07.11.2024) the only **5.5.0** version are available. I don't understand what's going on?

**Comment by HankaMEGA** [comment]
Hello! We have identified some issues in 5.6.0; however, these are now fixed and will be released shortly. 5.6.0 is back on https://mega.io/desktop.

**Comment by RKI91** [comment]
> Hello! We have identified some issues in 5.6.0; however, these are now fixed and will be released shortly. 5.6.0 is back on https://mega.io/desktop.

Automatic update also received or will receive this version?
