### ISSUE TITLE
Drop file on Mega icon to upload it?

### ISSUE THREAD

**Issue by paul1149** [meganz/MEGAsync#1016]
Is there any way to drag and drop a file to the Mega icon to upload it and get the url? This would be a big timesaver. As for the program's GUI, I can't get it to remain open once I click away from it. I don't see a setting to change that. That means a long menu dive to upload a file.

I'm on 5.6.0 on Linux.

Thanks.

**Comment by rautamiekka** [comment]
Not a bad idea, but you can also drag-drop on the transfer manager window, and depending on your settings it could auto-upload without asking, then you can right-click the item in the `Completed` tab.

**Comment by paul1149** [comment]
A significant part of the problem is that the main interface is so ephemeral. I'm on the KDE desktop on MX Linux 23, and the window insists on opening in the far right lower corner. Then any activity out of it causes it to close. If I open the transfer window then that is persistent, but only until I actually use it to upload something, then it's gone, and I have to go through the whole multi-stage process again to upload more. On my system this is quite unworkable, and I'm looking for an easier way.

**Comment by paul1149** [comment]
Actually, the web site performs far better in this regard than the desktop prog. I may keep a tab open, or perhaps a sidebar panel item, and use it that way.
