### ISSUE TITLE
Upload/Download Rate Limit boxes are too small in v5.7.0

### ISSUE THREAD

**Issue by Eldaw** [meganz/MEGAsync#1033]
MEGAsync v5.7.0 for Windows. I'm sure the boxes for setting the rate limits could have been made a reasonable size. See screenshot below, where my limit of 2500 isn't even fully visible in the input field.

![image](https://github.com/user-attachments/assets/023fdf91-e3ed-4445-b8e8-d0fc84d1d8c7)

**Comment by vtmateos** [comment]
Hi,
We take note of that and will adjust in next versions of the app
Thanks for the feedback.
