### ISSUE TITLE
Windows client doesn't play good with high DPI displays

### ISSUE THREAD

**Issue by sumeee** [meganz/MEGAsync#11]
The popup and the settings window doesn't scale right for high DPI displays on Windows. Also some controls get larger than it should (the buttons and the vertical scroll bar) and it covers other items.
I'm using Windows 10.

Settings screenshot:
![mega_settings](https://cloud.githubusercontent.com/assets/18469119/14538821/4a9eb0aa-0286-11e6-8744-fa1c62b3cf85.jpg)

The popup window compare with the taskbar:
![mega_popup](https://cloud.githubusercontent.com/assets/18469119/14538946/d5503c3c-0286-11e6-8626-8c9349039c64.jpg)

**Comment by javiserrano** [comment]
We improved MEGAsync for HDPI displays on Windows in version 2.9.5.
Please open the issue again or create a new one if you still have these problems with the last version.
