### ISSUE TITLE
Mac client persistently "Logging in..." with unusable preferences

### ISSUE THREAD

**Issue by MTCoster** [meganz/MEGAsync#111]
When trying to launch the Mac client on macOS Sierra (10.12.5), the app appears to never log in.  Clicking on the menu bar icon generates another identical notification ("Logging in...").  I tried to access the preferences to check I had entered my password correctly, but found them stuck on the Proxy pane with all four other tabs and the apply button disabled (see attached image).  I've also included startup logs from the system Console:

```
default	14:10:24.368242 +0100	kernel		fsevents: watcher MEGAclient (pid: 11166) - Using /dev/fsevents directly is unsupported.  Migrate to FSEventsFramework
default	14:10:24.399629 +0100	MEGAclient	UNIX error exception: 17
default	14:10:24.400127 +0100	MEGAclient	0x1021ec000 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	14:10:24.403136 +0100	MEGAclient	UNIX error exception: 17
default	14:10:24.403412 +0100	MEGAclient	UNIX error exception: 17
default	14:10:24.403608 +0100	MEGAclient	0x10c610660 opened /System/Library/Keychains/SystemRootCertificates.keychain: 385940 bytes
default	14:10:24.417294 +0100	MEGAclient	Invalid serial number length (21), must be 1..20
default	14:10:24.464223 +0100	kernel		[MEGAclient pid:11166 mux-aware] starting, non-mux-aware app count 0, EG power-state: 0 3D: busy HDA: busy
```

![Preferences - MEGAsync](https://user-images.githubusercontent.com/2152582/28165218-d2821d7c-67ca-11e7-93a5-e88b5c2600c8.png)

**Comment by mjknoxie** [comment]
Same version of macOS, newly created Mega account, webui is fine, Megasync never logs in.

**Comment by yivo** [comment]
Having the same problem...

**Comment by yivo** [comment]
<img width="351" alt="screen shot 2017-07-13 at 3 10 44 pm" src="https://user-images.githubusercontent.com/7421323/28165675-77410e10-67dd-11e7-8fac-b1e8432936d4.png">

**Comment by munsuri** [comment]
Same here. Account is not new and yesterday was working fine... (no updates, can't remember any change)
I checked console logs and saw some errors:

default	12:32:52.223243 -0300	kernel	[MEGAclient pid 48177 mux-aware] exiting, non-mux-aware app count 0, runtime: 0:05:32.355
default	12:33:00.680552 -0300	kernel	fsevents: watcher MEGAclient (pid: 48213) - Using /dev/fsevents directly is unsupported.  Migrate to FSEventsFramework
default	12:33:00.703211 -0300	MEGAclient	UNIX error exception: 17
default	12:33:00.703623 -0300	MEGAclient	0x10248fc20 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	12:33:00.705907 -0300	MEGAclient	UNIX error exception: 17
default	12:33:00.706086 -0300	MEGAclient	UNIX error exception: 17
default	12:33:00.706192 -0300	MEGAclient	0x10249d170 opened /System/Library/Keychains/SystemRootCertificates.keychain: 385940 bytes
default	12:33:00.714550 -0300	MEGAclient	Invalid serial number length (21), must be 1..20
default	12:33:00.739394 -0300	kernel	[MEGAclient pid:48213 mux-aware] starting, non-mux-aware app count 0, EG power-state: 6 3D: idle HDA: idle

Info: Up to date, Mac OSX 10.12.5

**Comment by ortmann** [comment]
Dear Matt,

Apologies for this - it should be back to normal now.

Kind regards

**Comment by Prizm4** [comment]
Same problem.

**Comment by PlusA2M** [comment]
Same issue here.
