### ISSUE TITLE
How to install MEGASync on Centos 6.8?

### ISSUE THREAD

**Issue by Salamander3** [meganz/MEGAsync#112]
Hi, i'd like to know if it's possible to install MEGASync on Centos 6.8 and what would be the process to achieve it.
Thanks!

**Comment by polmr** [comment]
I'm afraid Qt version bundled with CentOS 6 is not compatible with MEGASync. However if you want to use your MEGA account and sync your files with mega, you can use the command line utility (MEGAcmd, https://github.com/meganz/sdk/tree/master/examples/megacmd). Here's the link for CentOS 6 64 bit version: https://mega.nz/linux/MEGAsync/CentOS_6/x86_64/megacmd-0.9.3-1.el6.x86_64.rpm.

**Comment by Salamander3** [comment]
I see, thanks for the info. 
Can i ask are transfer speeds to mega server any better than using their website? Their website uses about 5% of my connection speed.

**Comment by polmr** [comment]
Running a native client (MEGAcmd or MEGASync) is likely to increase performance since for starters, encryption/decryption is done natively and not within the browser. Also, for big files, memory can be more optimally used.

**Comment by Salamander3** [comment]
I'm not gonna lie i'd love to try it, but i'm very new to linux...i'd need idiot proof step by step commands to make it. I understand this is asking a lot so it's fine eventually learn this...hopefully! Thanks!
