### ISSUE TITLE
Synching files/folders with "illegal" characters (for cmd and explorer)

### ISSUE THREAD

**Issue by glachance** [meganz/MEGAsync#12]
I'll try and reproduce this if you are having any issue reproducing this error, but today in my synch folder I ended up with a folder ending in a space and a file ending with three periods (...).

NTFS doesn't have any problem with that but the Windows command line and Windows explorer were both totally confused.... (and so was I for the time it took me to understand that there was an extra space on that folder - first time i've seen that).  

I had to resort to bash to resolve the situation.

**Comment by javiserrano** [comment]
Sorry for the long time we have taken to reply :-/
Could you give us steps to reproduce the problem? That way we could analyze and fix it.
Thanks!
