### ISSUE TITLE
Can't login on Arch Linux (port blocked?)

### ISSUE THREAD

**Issue by mikeframpo** [meganz/MEGAsync#124]
I'm having trouble logging in recently on Arch Linux. I'm running megasync 3.1.4.0-1 from the AUR.

megasync stays on this screen and doesn't log me in
![megasync-login](https://user-images.githubusercontent.com/1390340/30146507-8b2fa568-93ec-11e7-820a-a7b84492d58a.png)

I'm running from a university campus. I see on [this page](https://mega.nz/help/client/megasync/general/which-ports-does-megasync-use-576c865d886688e6028b459a) that megasync uses port 6342 for communication. Would megasync fail to login if my school blocked incoming connections on this port on its firewall?

Edit: I've seen one or two other people talk about firewall issues. If this is the case, is there any sort of work around?

Thanks
-Mike

**Comment by polmr** [comment]
We've had some issues with the network library used in Arch Linux.That's been solved in the official packages (available at https://mega.nz/sync). That might solve your issue.
Port 6342 is used for communications within your computer: between your web browser/file manager and megasync. Your campus firewall won't meddle with that.

**Comment by mikeframpo** [comment]
That fixed it for me. I'll flag the AUR package as out of date.

Thanks for supporting Arch!

**Comment by maravento** [comment]
They should reopen this ticket. The bug persists
