### ISSUE TITLE
How can i remove megasync icon in system tray ubuntu 16.04?

### ISSUE THREAD

**Issue by thanhngvpt** [meganz/MEGAsync#127]
Hi all,
I want to hide megasync icon in system tray of ubuntu 16.04 but it still running in background?
Thanks

**Comment by polmr** [comment]
Short answer: you cannot.
Long answer:
You can always recompile megasync commenting all calls to 
```
trayIcon->show();
```
Also, you might want to take a look at MEGAcmd: https://mega.nz/cmd which has some of the functionality MEGAsync offers but without a GUI.

**Comment by thanhngvpt** [comment]
@polmr Thanks. Let me try with MEGAcmd
