### ISSUE TITLE
new version ✔emblems icons is too big

### ISSUE THREAD

**Issue by levinit** [meganz/MEGAsync#130]
old nautilus-megasync emblems have low resolution #93 
but new version is too big :D ，please make it smaller 
![2017-09-30 12-46-44](https://user-images.githubusercontent.com/24387319/31042582-29a1243a-a5de-11e7-9532-8796d432b37f.png)

**Comment by polmr** [comment]
hi @levinit, that's indeed rather too big... 
In tested scenarios, overlay icons are never rendered that big (compared to thumbnail). 
What's your nautilus version, OS, desktop, screen resolution ... is the ratio similar in any level of zoom?

**Comment by levinit** [comment]
nautilus 3.26.0   Gnome3.26.0  ArchLinux  1920*1080 14inch
scale 50%
![2017-10-02 19-02-05](https://user-images.githubusercontent.com/24387319/31074692-75ba0f54-a7a4-11e7-9b0f-d1ae7e4d10c1.png)
scale 135%
![2017-10-02 19-01-55](https://user-images.githubusercontent.com/24387319/31074699-79a375a6-a7a4-11e7-827f-ed7303e42f8a.png)
It will change size with ratio

**Comment by polmr** [comment]
I've been investigating. Seems that the ratio between overlay icon/thumbnail has changed upon nautilus 3.15.3 (I believe). We will take that into account and offer smaller overlays for such scenarios.
