### ISSUE TITLE
error on make

### ISSUE THREAD

**Issue by izenn** [meganz/MEGAsync#132]
Running archlinux (latest patches) i get the following error on build:

```In file included from control/CrashHandler.cpp:15:0:
google_breakpad/client/linux/handler/exception_handler.h:192:21: error: field ‘context’ has incomplete type ‘google_breakpad::ucontext’
struct ucontext context;
^~~~~~~
google_breakpad/client/linux/handler/exception_handler.h:192:12: note: forward declaration of ‘struct google_breakpad::ucontext’
struct ucontext context;
^~~~~~~~
make: *** [Makefile:5282: CrashHandler.o] Error 1
```

**Comment by polmr** [comment]
That's an issue with latest glibc. You need to replace all `struct ucontext` by `ucontext_t` and 
`siginfo_t siginfo = {0, 0, 0, {0}};	`	
by
 ```
siginfo_t siginfo;
 memset(&siginfo, 0, sizeof(siginfo_t));
```
I believe that'll do. We will deploy a fixed version soon.

**Comment by eimiss** [comment]
Arch user here as well.
Changing that requires changes in `minidump_writer.cc` file which I'm not able to do...patiently waiting for the fixed version
