### ISSUE TITLE
MEGAcmd sync command. Failed to sync folder: Already exists

### ISSUE THREAD

**Issue by yurkovych** [meganz/MEGAsync#133]
Hi, um, sorry, if it's a wrong place to ask this, but i'll be glad if you could help with MEGAcmd.

I can't get it to work. It won't sync. 'get' works, 'mkdir' works, all else works, but once i actually try to sync 2 folders, it says 'Failed to sync folder: Already exists'

i try following 'sync d:\myfolder /myfolder' 

Please help. What do i do wrong? Thanks

**Comment by yurkovych** [comment]
kinda figured it out. there was a global sync of root on mega cloud which synced everything. I'd delete this issue, but i can't see where to do it

**Comment by polmr** [comment]
Exactly, you cannot sync folders within synched folders. Btw, there's a new repo for MEGAcmd here: https://github.com/meganz/MEGAcmd, Issues should go there now ;-)
