### ISSUE TITLE
No context menu in Dolphin 17.08.2 on KDE neon 5.11

### ISSUE THREAD

**Issue by oguzhanogreden** [meganz/MEGAsync#135]
MEGA client for Linux does not create a "Get MEGA link" item in the context menu ("Service Menu" in KDE language) of Dolphin, unlike Nautilus in Gnome.

Relevant directory paths are noted [here](https://www.kubuntuforums.net/showthread.php/25740-Service-Menus-with-Dolphin/page4?p=367207&viewfull=1#post367207).

**Comment by polmr** [comment]
Just to be sure... do you have `dolphin-megasync` installed?

**Comment by oguzhanogreden** [comment]
Oops... A little slip of not looking wider than issues! Excuses.

**Comment by polmr** [comment]
No problem ;-)
