### ISSUE TITLE
Issue with feature: file versioning and folders

### ISSUE THREAD

**Issue by SB-FM** [meganz/MEGAsync#138]
I handle my account in folders - roughly 1000 of them.

The new feature creates versions of my files and in order to delete previous versions i have to go into each single folder, check if it has previous versions and then delete the previous versions of the files.

Please, for all what is holy, introduce a global way to disable file versioning all together in advanced options or a global delete for all previous versions as a rubbish bin option.

**Comment by bozonius** [comment]
May I add, that in the future, it just MIGHT be a good idea to inform users of such changes PRIOR to deploying them.  Offer, say, a 30 day feedback period before commencing rollouts.

**Comment by polmr** [comment]
As discussed here, this is on the way: https://github.com/meganz/sdk/issues/890.

**Comment by polmr** [comment]
This can be done via web now: Settings -> Advanced -> File Management -> Delete all file versions:
It'll be included in the next release of MEGAsync
