### ISSUE TITLE
Many undefined references http2.c

### ISSUE THREAD

**Issue by blackPantherOS** [meganz/MEGAsync#15]
BUILD/MEGAsync/src〉git:master〉make
cd MEGASync/ && ( test -e Makefile || /bin/qmake /usr/src/RPM/BUILD/MEGAsync/src/MEGASync/MEGASync.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/usr/src/RPM/BUILD/MEGAsync/src/MEGASync'
g++ -Wl,-O1 -o megasync SettingsDialog.o ActiveTransfer.o InfoDialog.o RecentFile.o TransferProgressBar.o UsageProgressBar.o SetupWizard.o NodeSelector.o FolderBinder.o BindFolderDialog.o UploadToMegaDialog.o PasteMegaLinksDialog.o ImportMegaLinksDialog.o ImportListWidgetItem.o CrashReportDialog.o MultiQFileDialog.o MegaProxyStyle.o AccountDetailsDialog.o DownloadFromMegaDialog.o SizeLimitDialog.o UsageWidget.o MessageBox.o InfoOverQuotaDialog.o QMegaModel.o MegaItem.o ChangeLogDialog.o GuestWidget.o StreamingFromMegaDialog.o ConfirmSSLexception.o UpgradeDialog.o PlanWidget.o InfoWizard.o PermissionsDialog.o PermissionsWidget.o attrmap.o backofftimer.o base64.o command.o commands.o db.o gfx.o file.o fileattributefetch.o filefingerprint.o filesystem.o http.o json.o megaclient.o node.o pubkeyaction.o request.o serialize64.o share.o sharenodekeys.o sync.o transfer.o transferslot.o treeproc.o user.o utils.o logging.o waiterbase.o proxy.o pendingcontactrequest.o cryptopp.o sqlite.o qt.o external.o qtthread.o mega_utf8proc.o megaapi.o megaapi_impl.o QTMegaRequestListener.o QTMegaTransferListener.o QTMegaGlobalListener.o QTMegaSyncListener.o QTMegaListener.o QTMegaEvent.o mega_http_parser.o net.o fs.o waiter.o HTTPServer.o Preferences.o LinkProcessor.o MegaUploader.o UpdateTask.o EncryptedSettings.o CrashHandler.o ExportProcessor.o Utilities.o MegaDownloader.o MegaSyncLogger.o ConnectivityChecker.o notificator.o LinuxPlatform.o ExtServer.o NotifyServer.o crash_generation_client.o exception_handler.o minidump_descriptor.o minidump_writer.o linux_dumper.o linux_ptrace_dumper.o log.o minidump_file_writer.o linux_libc_support.o file_id.o memory_mapped_file.o safe_readlink.o guid_creator.o elfutils.o string_conversion.o convert_UTF.o qtlockedfile.o qtlockedfile_unix.o MegaApplication.o moc_SettingsDialog.o moc_ActiveTransfer.o moc_InfoDialog.o moc_RecentFile.o moc_TransferProgressBar.o moc_UsageProgressBar.o moc_SetupWizard.o moc_NodeSelector.o moc_FolderBinder.o moc_BindFolderDialog.o moc_UploadToMegaDialog.o moc_PasteMegaLinksDialog.o moc_ImportMegaLinksDialog.o moc_ImportListWidgetItem.o moc_CrashReportDialog.o moc_MultiQFileDialog.o moc_MegaProxyStyle.o moc_AccountDetailsDialog.o moc_DownloadFromMegaDialog.o moc_SizeLimitDialog.o moc_UsageWidget.o moc_MessageBox.o moc_InfoOverQuotaDialog.o moc_QMegaModel.o moc_ChangeLogDialog.o moc_GuestWidget.o moc_StreamingFromMegaDialog.o moc_ConfirmSSLexception.o moc_UpgradeDialog.o moc_PlanWidget.o moc_InfoWizard.o moc_PermissionsDialog.o moc_PermissionsWidget.o moc_QTMegaRequestListener.o moc_QTMegaTransferListener.o moc_QTMegaGlobalListener.o moc_QTMegaSyncListener.o moc_QTMegaListener.o moc_HTTPServer.o moc_Preferences.o moc_LinkProcessor.o moc_MegaUploader.o moc_UpdateTask.o moc_EncryptedSettings.o moc_CrashHandler.o moc_ExportProcessor.o moc_MegaDownloader.o moc_MegaSyncLogger.o moc_ConnectivityChecker.o moc_notificator.o moc_ExtServer.o moc_NotifyServer.o moc_MegaApplication.o qrc_Resources_linux.o    -L/usr/lib -luv -lcryptopp -lsqlite3 -lrt -L/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/ /usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a -lz -lcares -lssl -lcrypto -lQtDBus -L/usr/lib -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread -ldl
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `http2_disconnect':
http2.c:(.text+0x18): undefined reference to `nghttp2_session_del'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `http2_perform_getsock':
http2.c:(.text+0xcc): undefined reference to `nghttp2_session_want_read'
http2.c:(.text+0xe2): undefined reference to `nghttp2_session_want_write'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_begin_headers':
http2.c:(.text+0x11f): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_frame_not_send':
http2.c:(.text+0x13f): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_header':
http2.c:(.text+0x163): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_data_chunk_recv':
http2.c:(.text+0x424): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `data_source_read_callback':
http2.c:(.text+0x500): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o):http2.c:(.text+0x5f9): more undefined references to `nghttp2_session_get_stream_user_data' follow
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_frame_recv':
http2.c:(.text+0x7a3): undefined reference to `nghttp2_submit_rst_stream'
http2.c:(.text+0x7ad): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0x7dc): undefined reference to `nghttp2_session_get_remote_settings'
http2.c:(.text+0x7f3): undefined reference to `nghttp2_session_get_remote_settings'
http2.c:(.text+0x8fc): undefined reference to `nghttp2_submit_rst_stream'
http2.c:(.text+0x904): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0x9c6): undefined reference to `nghttp2_session_set_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `h2_pri_spec':
http2.c:(.text+0xa3e): undefined reference to `nghttp2_priority_spec_init'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `h2_session_send':
http2.c:(.text+0xaaf): undefined reference to `nghttp2_submit_priority'
http2.c:(.text+0xabf): undefined reference to `nghttp2_session_send'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `http2_send':
http2.c:(.text+0xb4a): undefined reference to `nghttp2_session_resume_data'
http2.c:(.text+0xb5f): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0xbad): undefined reference to `nghttp2_session_resume_data'
http2.c:(.text+0xe71): undefined reference to `nghttp2_submit_request'
http2.c:(.text+0xeb4): undefined reference to `nghttp2_session_send'
http2.c:(.text+0xed1): undefined reference to `nghttp2_session_resume_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `http2_recv':
http2.c:(.text+0x1244): undefined reference to `nghttp2_session_mem_recv'
http2.c:(.text+0x1250): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0x13d9): undefined reference to `nghttp2_strerror'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_stream_close':
http2.c:(.text+0x14f1): undefined reference to `nghttp2_session_get_stream_user_data'
http2.c:(.text+0x151c): undefined reference to `nghttp2_session_set_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `Curl_http2_init.part.3':
http2.c:(.text+0x1558): undefined reference to `nghttp2_session_callbacks_new'
http2.c:(.text+0x158d): undefined reference to `nghttp2_session_callbacks_set_send_callback'
http2.c:(.text+0x159d): undefined reference to `nghttp2_session_callbacks_set_on_frame_recv_callback'
http2.c:(.text+0x15ad): undefined reference to `nghttp2_session_callbacks_set_on_invalid_frame_recv_callback'
http2.c:(.text+0x15bd): undefined reference to `nghttp2_session_callbacks_set_on_data_chunk_recv_callback'
http2.c:(.text+0x15cd): undefined reference to `nghttp2_session_callbacks_set_before_frame_send_callback'
http2.c:(.text+0x15dd): undefined reference to `nghttp2_session_callbacks_set_on_frame_send_callback'
http2.c:(.text+0x15ed): undefined reference to `nghttp2_session_callbacks_set_on_frame_not_send_callback'
http2.c:(.text+0x15fd): undefined reference to `nghttp2_session_callbacks_set_on_stream_close_callback'
http2.c:(.text+0x160d): undefined reference to `nghttp2_session_callbacks_set_on_begin_headers_callback'
http2.c:(.text+0x161d): undefined reference to `nghttp2_session_callbacks_set_on_header_callback'
http2.c:(.text+0x1631): undefined reference to `nghttp2_session_client_new'
http2.c:(.text+0x163d): undefined reference to `nghttp2_session_callbacks_del'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_invalid_frame_recv':
http2.c:(.text+0x167f): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `before_frame_send':
http2.c:(.text+0x169f): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `on_frame_send':
http2.c:(.text+0x16bf): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `Curl_http2_ver':
http2.c:(.text+0x1756): undefined reference to `nghttp2_version'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `Curl_http2_request_upgrade':
http2.c:(.text+0x18fd): undefined reference to `nghttp2_pack_settings_payload'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http2.o): In function `Curl_http2_switched':
http2.c:(.text+0x1b4f): undefined reference to `nghttp2_submit_settings'
http2.c:(.text+0x1bad): undefined reference to `nghttp2_session_upgrade'
http2.c:(.text+0x1bc3): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x1c2f): undefined reference to `nghttp2_session_mem_recv'
http2.c:(.text+0x1c39): undefined reference to `nghttp2_is_fatal'
http2.c:(.text+0x1c76): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x1c9d): undefined reference to `nghttp2_strerror'
http2.c:(.text+0x1ccf): undefined reference to `nghttp2_session_set_stream_user_data'
http2.c:(.text+0x1d05): undefined reference to `nghttp2_strerror'
/usr/src/RPM/BUILD/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/libs/libcurl.a(libcurl_la-http.o): In function `Curl_http_done':
http.c:(.text+0x69d): undefined reference to `nghttp2_session_set_stream_user_data'
collect2: error: ld returned 1 exit status
Makefile:451: recipe for target 'megasync' failed
make[1]: *** [megasync] Error 1
make[1]: Leaving directory '/usr/src/RPM/BUILD/MEGAsync/src/MEGASync'
Makefile:42: recipe for target 'sub-MEGASync-make_first' failed
make: *** [sub-MEGASync-make_first] Error 2

Someone have any suggestion? Thx

**Comment by javiserrano** [comment]
It seems that the undefined references are in `libcurl.a`. Linking `nghttp2` or rebuilding your `libcurl.a` without support for it should fix the problem.
