### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by luwes** [meganz/MEGAsync#158]
There seems to be a memory leak... Is this normal? 

<img width="540" alt="screen shot 2017-12-23 at 16 12 40" src="https://user-images.githubusercontent.com/360826/34322704-cdaae8bc-e7fc-11e7-9aca-646457ecef0f.png">

**Comment by themonkeyzen** [comment]
I reported this problem month ago and i didn't any response:
https://github.com/meganz/MEGAsync/issues/151

**Comment by rastilin** [comment]
I'm seeing this problem as well. Odds are that it's related to storing repositories inside the MEGA folder (and the problem gets worse when temp files are generated inside the MEGA folder). Using 8GB of memory for a 2.5GB account is probably excessive however.

**Comment by rastilin** [comment]
Additionally I've just updated to 3.6.0 on the OSX machine, but the problem is still happening.

**Comment by zimme** [comment]
I run into this too, but I'm using around 45GB and it's filling up my disk using swap (35GB).

**Comment by absolutlabs** [comment]
hello, is there any update on this issue ?
thanks ! :)

**Comment by Kur0x** [comment]
I have the same problem too. It takes 15G RAM in 5 days!
![image](https://user-images.githubusercontent.com/9768369/41776091-f9b37f1a-7658-11e8-8d33-f8dceda910aa.png)

**Comment by vtmateos** [comment]
Hi all,

Apologies for the possible problems that you are experiencing. In order to provide an accurate analysis of these issues, please contact our support team at support@mega.nz. They will provide you detailed notes and required information to investigate the issues.

Regards.

**Comment by TGotwig** [comment]
I use mega on MacOS Mojave for syncing my home directory except few folders in it,
I saw that it took 70gb of RAM after some time 😱
Please fix this 😓

**Comment by dedishchev** [comment]
MEGA client on my mac uses around 30gb of swap. Any updates?

**Comment by PRosenb** [comment]
I use [Rclone](https://rclone.org/mega/) on Mac instead, it works quite well.

**Comment by willvlad** [comment]
Terrible memory leakage in the Mega Mac client. Crashes my Mac Pro Mojave every time I leave it to sync. Please fix it!

**Comment by nickyhajal** [comment]
Yep, megasync using 42GB of memory on my machine. What is going on? Is this being resolved?

**Comment by z0mbix** [comment]
I think it's pretty clear this isn't getting fixed. I switched back to Dropbox (unfortunately)

**Comment by mattw-mega** [comment]
Hi, does MEGAsync use that amount of memory after just logging in, or does it increase over time after login, and what actions in your account make it increase, please?    Does it do so even if the account is idle, or only when you take certain actions?  thanks

**Comment by z0mbix** [comment]
For me, it took around 2 days of normal light use before is was around 8GB and I had to restart the client.

**Comment by Jeehut** [comment]
I'm also experiencing this problem on my new Mac mini with M1 processor. My whole computer is hanging due to this memory leakage issue. Please fix this ASAP or I will need to switch to an alternative solution. It's not acceptable that this is a known issue and there's no fix yet.

**Comment by Jeehut** [comment]
@PRosenb How did you set up rclone to do the syncing? Is there any guide I can follow? It seems like a quite complicated to configure tool. Also, I need end-to-end encryption, is that supported (by default) with rclone?

Any hints would be appreciated!

**Comment by zDEFz** [comment]
![image](https://user-images.githubusercontent.com/24463722/120315152-520b5480-c2dc-11eb-9b9f-aae040d94a83.png)
No M1 iMac 2019 late here. Running macOS Big Sur. 
Insane RAM usage.

**Comment by tadas-subonis** [comment]
Still happening on Win

![image](https://user-images.githubusercontent.com/247218/121087080-42ac6f80-c7e4-11eb-8e66-c20c396baaa3.png)

![image](https://user-images.githubusercontent.com/247218/121087097-48a25080-c7e4-11eb-8472-9bed00ccc86b.png)

**Comment by xanoni** [comment]
Same problem observed on MacOS Big Sur .... if I keep it running for a few hours, it easily consumes 20GB+ of RAM. Workaround is to restart it regularly via a cronjob.

**Comment by HaselLoyance** [comment]
Happened to me too on Windows. Occasionally it gets so bad (maxes out 16GBs of RAM) that the only thing left to do is to restart my PC, since it does not even respond to ctrl+alt+del to kill the Mega process. Got to revisit the old WIndows XP UI glitches while at it too:
![image](https://user-images.githubusercontent.com/19696509/123292238-78d23a80-d4d8-11eb-80f6-95f3b3aebf77.png)

Also, on a slightly unrelated note: accessing Mega through web browser is very slow for me too. It takes on average 5 minutes to receive my account data:
![image](https://user-images.githubusercontent.com/19696509/123292660-e1211c00-d4d8-11eb-8ca6-aba77005f8c8.png)
My only guess is that it is struggling with receiving a list of 660k+ files?

**Comment by xanoni** [comment]
So I noticed that whenever I clear the remote debris via the "Advanced" settings menu in the desktop app, my RAM usage suddenly drops massively.

![image](https://user-images.githubusercontent.com/77220130/123571029-60437800-d797-11eb-995c-039b91e98d6b.png)

**Comment by vtmateos** [comment]
Dear users,

Thanks for the feedback. Regarding the high memory usage issue, we have prepared a new version v.4.5.2 that fixes issues over 4.5.1 and 4.5.0. Check this issue  #595  for further information.

Clear SyncDebris only performs a remote deletion of the files in your Rubbish bin, so it should not be a relation with decreasing the memory usage. It just send a command to empty your SyncDebris folder inside your Rubbish.

Try this new version and check if all goes ok.

Thanks.

**Comment by xanoni** [comment]
> Dear users,
> 
> Thanks for the feedback. Regarding the high memory usage issue, we have prepared a new version v.4.5.2 that fixes issues over 4.5.1 and 4.5.0. Check this issue #595 for further information.
> 
> Clear SyncDebris only performs a remote deletion of the files in your Rubbish bin, so it should not be a relation with decreasing the memory usage. It just send a command to empty your SyncDebris folder inside your Rubbish.
> 
> If you want to check this new version, you can get it through our website. Just reinstall with latest public installer.
> The roll out for the autoupdate will take place in the following days.
> 
> Thanks.

well I can tell you that my memory usage repeatedly fell from close to 10 GB to less than 1 GB after clicking that button

**Comment by HaselLoyance** [comment]
> Dear users,
> 
> Thanks for the feedback. Regarding the high memory usage issue, we have prepared a new version v.4.5.2 that fixes issues over 4.5.1 and 4.5.0. Check this issue #595 for further information.
> 
> Clear SyncDebris only performs a remote deletion of the files in your Rubbish bin, so it should not be a relation with decreasing the memory usage. It just send a command to empty your SyncDebris folder inside your Rubbish.
> 
> If you want to check this new version, you can get it through our website. Just reinstall with latest public installer.
> The roll out for the autoupdate will take place in the following days.
> 
> Thanks.


I can say that so far I haven't seen MEGA taking up 12GB of RAM as it used to (v4.5.2), which is definitely an improvement 👍 . However, the process does still use 1.8GB of RAM just to exist:
![image](https://user-images.githubusercontent.com/19696509/123728515-f12e5800-d858-11eb-8c88-fb05fd508a03.png)
Seems a little too much for a task that does nothing in the background?

After deleting 135GB of sync debris and restarting I was able to get my RAM usage to around 1.4GB:
![image](https://user-images.githubusercontent.com/19696509/123728716-5a15d000-d859-11eb-98b9-d33c4d0e1780.png)
![image](https://user-images.githubusercontent.com/19696509/123730914-cb0ab700-d85c-11eb-8903-673ec6bf96de.png)

**Comment by xanoni** [comment]
all that sync debris is somewhat concerning tbh ... or should it not be? I also have a lot, mostly on the server side.

**Comment by vtmateos** [comment]
Hi, 
Thanks for your useful feedback, it is really appreciated. 

> After deleting 135GB of sync debris and restarting I was able to get my RAM usage to around 1.4GB:

You are right, if you have a huge amount of nodes within your SyncDebris folder, it might have a noticeable reduction in your memory usage once you clear it.

Let's try to explain roughly the process:

```
During the sync process, deletions and other sync ops could cause that sync engine moves files to one of these dirs:
.debris: A local folder with a backup of files deleted in MEGA
SyncDebris: A folder in MEGA with a backup of the files deleted in the local computer
```

MEGAsync keeps your nodes (files and folder) in ram memory during execution. Once you click **Clear the SyncDebris from settings**, it performs a wipe of that remote folder inside your Rubbish bin, deleting all the nodes from that folder and thus reducing the nodes of your account, causing a reduction of ram usage. You can also clear the file versions through that settings section and the ram will be reduced too.

We are working on reducing memory usage with several solutions for future version.

Stay tuned and thanks for your comments

**Comment by xanoni** [comment]
> .debris: A local folder with a backup of files deleted in MEGA
> SyncDebris: A folder in MEGA with a backup of the files deleted in the local computer

Ah okay, I thought the debris contained files related to sync conflicts between client and server.

But if it's ALL data deleted from the client, then the huge debris makes sense.

**Comment by jpercyasnet** [comment]
Now I see why in linux megasync uses over 800 MiB of Memory. And if I run Mega-cmd it also uses that same amount. Since I only have 8g memory it is already using almost 2g. I can no longer use raspberry pi 3, because it only has 1g memory. I am a Pro III user with 9TB of data which is over 400,000 files. Several times my system hangs when running multiple programs and my swap goes over 60%. You need to give option or force the file list to a temp space database. The only alternative right now is only run megasync and/or mega-cmd as needed and standalone.

**Comment by zDEFz** [comment]
> Now I see why in linux megasync uses over 800 MiB of Memory. And if I run Mega-cmd it also uses that same amount. Since I only have 8g memory it is already using almost 2g. I can no longer use raspberry pi 3, because it only has 1g memory. I am a Pro III user with 9TB of data which is over 400,000 files. Several times my system hangs when running multiple programs and my swap goes over 60%. You need to give option or force the file list to a temp space database. The only alternative right now is only run megasync and/or mega-cmd as needed and standalone.

Well. I'm free tier since some weeks and have migrated to an expensive SSD storage solution instead.
4x4 TB SSD. Of which 2 SSD's are having the exact same data and 8TB are used.
