### ISSUE TITLE
Speed limit does not work

### ISSUE THREAD

**Issue by ertyz** [meganz/MEGAsync#16]
Megasync 2.9.1 (Win 8.1 x64)
I set folders to sync
I set reduce limit speed to 200 KB

But folders sync on full speed (1000 KB/s) anyway

**Comment by javiserrano** [comment]
Hello,

Currently, MEGAsync only allows to set a speed limit for uploads, the limit doesn't apply for downloads.

Also, the limit is controlled at server side, it's set at the beginning of each upload and can't be modified during the transfer. So the limit set in settings when an upload starts is applied for the whole transfer.

We are working on the implementation of speed limits for both (uploads and downloads) and controlled on the client side so they could be changed in real time.

This feature should be ready and publicly available in about two months.

**Comment by javiserrano** [comment]
It has been finally scheduled for MEGAsync 3.0, that will be released on MEGA anniversary or sooner.

**Comment by pedz** [comment]
I have MEGAsync 3.1.4 on a Mac 10.11.6.  I set the limit to 50KB and it is downloading at full speed.  Is there anything I can do?  With my internet connection the size of a soda straw, this is a serious impact for me.

**Comment by vtmateos** [comment]
Dear users,

In case you experience any speed limit issue with latest 5.6.1 version, feel free to create a new ticket so the dev team can provide proper support.

Thanks for your report.
