### ISSUE TITLE
Dolphin menu messed up

### ISSUE THREAD

**Issue by DevPre24** [meganz/MEGAsync#160]
The dolphin menu is messed up on Fedora 27 KDE.
![screenshot_20180101_005041](https://user-images.githubusercontent.com/13499337/34464725-197a8e0e-ee8e-11e7-80cd-d58993979cbb.png)
![screenshot_20180101_005052](https://user-images.githubusercontent.com/13499337/34464726-1aa6d620-ee8e-11e7-9aae-a8c6084fb0d9.png)

**Comment by polmr** [comment]
Issue found, will be fixed in the next release. Thanks for reporting

**Comment by joaopauloalbq** [comment]
bug fixed

![screenshot_20181121_200712](https://user-images.githubusercontent.com/9905202/48872747-42d0f500-edc9-11e8-9fb3-3584c949be98.png)

**Comment by DevPre24** [comment]
> bug fixed
> 
> ![screenshot_20181121_200712](https://user-images.githubusercontent.com/9905202/48872747-42d0f500-edc9-11e8-9fb3-3584c949be98.png)

I can confirm, the bug was resolved months ago. I forgot to update the devs on that matter.

**Comment by polmr** [comment]
Thanks for reporting that. Closing issue
