### ISSUE TITLE
Cannot sync any local folder with MEGA folder

### ISSUE THREAD

**Issue by jabpe** [meganz/MEGAsync#17]
In [gui/BindFolderDialog.cpp](https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/gui/BindFolderDialog.cpp), always when I try to sync a local folder with a newly created MEGA folder this message is reported and I cannot sync other folders than the default one.

```
if (megaPath.startsWith(p) && ((p.size() == megaPath.size()) || p.size() == 1 || megaPath[p.size()] == QChar::fromAscii('/')))
            {
                QMessageBox::warning(this, tr("Error"), tr("The selected MEGA folder is already synced"), QMessageBox::Ok);
                delete n;
                delete node;
                return;
            }
```

**Comment by javiserrano** [comment]
Nor local folders nor MEGA folders can be synced twice. So if you are already syncing your entire Cloud Drive, it's not possible to sync any other folder (except incoming shared folders).
