### ISSUE TITLE
I can't install on Fedora 27

### ISSUE THREAD

**Issue by brunojs02** [meganz/MEGAsync#176]
I can't install MEGASync on Fedora 27, i jus get this error: megasync: symbol lookup error: megasync: undefined symbol: _ZNK8CryptoPP8Rijndael3Dec21AdvancedProcessBlocksEPKhS3_Phmj

**Comment by mikefedyk** [comment]
I can install on fedora 27 plasma, but no text shows on any buttons or menus.

**Comment by polmr** [comment]
this seems to be related to some updates in cryptopp 5.6.5. working on a solution, thanks for reporting!

**Comment by brunojs02** [comment]
Let me know when everything is working.

**Comment by tkuraku** [comment]
Same Problem Here. Thanks for the hard work!

**Comment by polmr** [comment]
You can try [this package](https://github.com/meganz/MEGAsync/files/1792363/megasync360fed27fix.zip)
It'll be released in the repository asap. In the meantime, there you have it in case you are in a hurry.

**Comment by core01** [comment]
@polmr It works, thank you!

**Comment by rgorosito** [comment]
@polmr It's works for me too. Thanks!

**Comment by brunojs02** [comment]
In my case, i run in terminal “#dnf downgrade cryptopp” and its work too

**Comment by tsvaan** [comment]
>"#dnf downgrade cryptopp"
Yes it's works. Thanks!

**Comment by polmr** [comment]
megasync package has been updated in the repository, updating solves this issue

**Comment by QuantumAnon** [comment]
Hi, I'm still having this issue with Fedora 26.
Has the update been pushed to the f26 repository?

**Comment by polmr** [comment]
@QuantumAnon we will push a new package asap. In the meantime, if you are not willing to wait, [here you have it](https://github.com/meganz/MEGAsync/files/1847639/megasync-3.6.0-5.2.x86_64.zip)

**Comment by QuantumAnon** [comment]
I've installed the update and everything is working as intended, thanks.

**Comment by Maarten14C** [comment]
Will there be a version for Fedora 28 soon? It is in beta now and megasync throws the symbol error

**Comment by polmr** [comment]
@Maarten14C  it'll be available real soon, as said here: https://github.com/meganz/MEGAsync/issues/189#issuecomment-382418127
