### ISSUE TITLE
Mac client stuck "Logging in"

### ISSUE THREAD

**Issue by buraksuran** [meganz/MEGAsync#177]
Mac client stucks after launch and shows only 2 available options on the menu bar which are "settings" and "exit". Settings option opens another window which is also stuck on Proxy panel, see attached images. On the other hand, mega.nz is fully working without any problem.
<img width="351" alt="28165675-77410e10-67dd-11e7-8fac-b1e8432936d4" src="https://user-images.githubusercontent.com/37255465/37248440-641075ba-24ca-11e8-9590-e54b813059e7.png">
![28165218-d2821d7c-67ca-11e7-93a5-e88b5c2600c8](https://user-images.githubusercontent.com/37255465/37248441-6429c100-24ca-11e8-9cc7-b033ef37b3b7.png)

**Comment by starttracker** [comment]
Same exact problem here.

**Comment by starttracker** [comment]
When I launch the Mac client on macOS Sierra (10.13.3), it gets stuck at log in without ever managing to get in.  If I click on the menu bar icon it generates an identical notification ("Logging in...").  When accessing the app preferences I also get stuck on the Proxy pane with all other tabs disabled (as in the image above).

**Comment by Prizm4** [comment]
Same problem.

**Comment by ammar094** [comment]
Same damn problem, been trying to figure it out all day. I was able to delete all the files from Library and re-install and login again but it gets stuck on the “Setup Assistant/Logging in...”

**Comment by vtmateos** [comment]
Thanks for reporting. All these issues should be already fixed. If you notice any other problem, please let us know. Apologies for the inconveniences.
Kind regards.

**Comment by spinninghamster** [comment]
This is happening to me right now. How to fix it?

**Comment by vtmateos** [comment]
Hi, apologies for the inconveniences. Please contact our support team at support@mega.nz. They will request logs from you for analysis and check any possible connectivity issue.

Thanks.
