### ISSUE TITLE
GUI, Linux, Nautilus: clicking Syncs open too many folders

### ISSUE THREAD

**Issue by themighty1** [meganz/MEGAsync#18]
Selecting Show Status->Syncs I have 4 folders listed
When I click on the folder icon, only one filemanager window opens, but if i click on the text, it opens 4 windows.

**Comment by polmr** [comment]
Which distribution are you using? Which is your desktop environment (unity/gnome-shell/kde/xfce/mate/cinnamon...)?

**Comment by themighty1** [comment]
Using Ubuntu 14.04, Gnome Classic

**Comment by polmr** [comment]
Thanks for the intel. the problem has been detected. It will be fixed soon.

**Comment by polmr** [comment]
Fixed here: https://github.com/meganz/MEGAsync/commit/4e1b3b1a7506d31eef14cf52fdad054c7983124a
