### ISSUE TITLE
Error in opensuse Leap 15

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [meganz/MEGAsync#184]
Hi, I installed all required packages and I'm receiving this error:

megasync: symbol lookup error: megasync: undefined symbol: _ZN8CryptoPP21RandomNumberGenerator34GenerateIntoBufferedTransformationERNS_22BufferedTransformationERKSsy

What could be?

Many thanks

**Comment by polmr** [comment]
This might be related to this issue https://github.com/meganz/MEGAsync/issues/176 . In the end, the binary you are using is not compiled with the correct cryptopp version. We will provide packages for Leap 15 before its release date.

**Comment by sirredbeard** [comment]
Recommend this bug be closed. Leap 15 packages are now available from https://mega.nz/sync.
