### ISSUE TITLE
md5sum error

### ISSUE THREAD

**Issue by alo0oz** [meganz/MEGAsync#187]
Connecting to download.libsodium.org (download.libsodium.org)|37.59.238.213|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-17 08:10:57 ERROR 404: Not Found.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170  100   170    0     0    135      0  0:00:01  0:00:01 --:--:--   136
Checking (again) MD5SUM for /home/mah_rakib/build/MEGAsync/src/archives/sodium-1.0.12.tar.gz
/home/mah_rakib/build/MEGAsync/src/archives/sodium-1.0.12.tar.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
Aborting execution due to incorrect MD5SUM for /home/mah_rakib/build/MEGAsync/src/archives/sodium-1.0.12.tar.gz. Expected: c308e3faa724b630b86cc0aaf887a5d4. Calculated:
6c41daf040690d9b41dc6193f3fa232b  /home/mah_rakib/build/MEGAsync/src/archives/sodium-1.0.12.tar.gz
ERROR! Please check log files. Exiting..

**Comment by polmr** [comment]
This commit on the sdk submodule fixes that (updates to 1.0.16) https://github.com/meganz/sdk/commit/24be4ea1b69db03c5ae22e60cdd036732439e8a0 . If you want to compile now, please, change the version and the checksum accordingly in src/MEGASync/mega/contrib/build_sdk.sh.
