### ISSUE TITLE
Fedora 28 forthcoming

### ISSUE THREAD

**Issue by sirredbeard** [meganz/MEGAsync#189]
Fedora 28 is nearing [release](https://fedoraproject.org/wiki/Releases/28/Schedule).

The current release of MEGAsync for Fedora 27 needs to be re-built for Fedora 28 against the updated version of cryptopp, cryptopp-6.1.0-2.

It currently fails on launch in Fedora 28 beta:
`megasync: symbol lookup error: megasync: undefined symbol: _ZN8CryptoPP20StreamTransformation16ProcessLastBlockEPhPKhm
`

**Comment by polmr** [comment]
This is currently ongoing. There will be packages for Fedora 28 in days. Thanks for reporting anyway

**Comment by sirredbeard** [comment]
Thank you very much. I am eagerly awaiting it.

**Comment by sirredbeard** [comment]
Do you have plans to release a build for RHEL 7.5 too?

**Comment by polmr** [comment]
@sirredbeard , we do provide packages for RHEL 7 at https://mega.nz/sync. Please, do not hesitate to report if you find any issues with it working on RHEL 7.5.

**Comment by Maarten14C** [comment]
it's working on f28 now, thanks!

**Comment by polmr** [comment]
Available at https://mega.nz/linux/MEGAsync/Fedora_28/x86_64/megasync-Fedora_28.x86_64.rpm

**Comment by sirredbeard** [comment]
Thank you!
