### ISSUE TITLE
./configure references build_sdk.sh that is missing

### ISSUE THREAD

**Issue by sirredbeard** [meganz/MEGAsync#190]
Line 72 of [configure](https://github.com/meganz/MEGAsync/blob/master/src/configure) references `./MEGASync/mega/contrib/build_sdk.sh`

But I can't find a script with that name.

As a result building on Linux is currently broken

> bash-4.4$ git clone https://github.com/meganz/MEGAsync.git
> Cloning into 'MEGAsync'...
> remote: Counting objects: 35773, done.
> remote: Total 35773 (delta 0), reused 0 (delta 0), pack-reused 35773
> Receiving objects: 100% (35773/35773), 53.93 MiB | 1.56 MiB/s, done.
> Resolving deltas: 100% (27534/27534), done.
> bash-4.4$ cd MEGAsync/
> bash-4.4$ cd src
> bash-4.4$ ./configure
> ./configure: line 72: ./MEGASync/mega/contrib/build_sdk.sh: No such file or directory
> ./configure: line 78: ./contrib/build_sdk.sh: No such file or directory
> ln: failed to create symbolic link '/home/hayden/Downloads/MEGAsync/src/MEGASync/mega/bindings/qt/3rdparty/libs': No such file or directory
> bash-4.4$

**Comment by polmr** [comment]
You are missing the `sdk` submodule at `src/MEGASync/mega`. you need to either clone recursively with `git clone --recursive` or once cloned, gather the submodule with: `git submodule update --init`

**Comment by sirredbeard** [comment]
Thank you!
