### ISSUE TITLE
Repository broken Ubuntu 16.04

### ISSUE THREAD

**Issue by alejosv** [meganz/MEGAsync#203]
When trying to do an `apt upgrade` in Ubuntu 16.04 it shows the following error
```
Err:2 https://mega.nz/linux/MEGAsync/xUbuntu_16.04 ./ megasync 3.6.6+6.1
  404  Not Found
```

**Comment by polmr** [comment]
There's an issue with the `+` character in the URL escaped by apt. The file is available at the repository, you can either follow the link that apt complains about and manually update megasync or get it from https://mega.nz/sync

**Comment by polmr** [comment]
It should be fixed already
