### ISSUE TITLE
Crashing on thumb generation of SVG file

### ISSUE THREAD

**Issue by haael** [meganz/MEGAsync#205]
Having this SVG file on my disk causes megasync to crash. The output from debug says about thumb generation, then segfaults.

It helps if I change the extension to *.svg_

Offending image attached as TXT.

[struct-use-12-f.txt](https://github.com/meganz/MEGAsync/files/2071440/struct-use-12-f.txt)

**Comment by polmr** [comment]
Hi @haael , what is your OS and if possible version of QT. We have reported a bug that we found in QT that caused the app to crash when trying to process a malformed svg file with some loop in it: https://bugreports.qt.io/browse/QTBUG-64425. This seems to be your case too, given that the svg seems full of nested loops: 
```
...
    <use id="useNested1" xlink:href="#useNested2">
        <use id="useNested2" xlink:href="#useNested1" />
    </use>
    <g id="useNestedGroup1" xlink:href="#useNestedGroup2">
        <use id="useNestedGroup2" xlink:href="#useNestedGroup1" />
        </g>
    <g id="useIndirectNestedGroup1">
        <use xlink:href="#useIndirectNestedGroupElem2" id="useIndirectNestedGroupElem1" />
    </g>
...
```
As a matter of fact, I've been able to reproduce it in a Ubuntu 16.04 (Qt 5.5.1). That offending svg also makes inkscape to crash. It works fine in Ubuntu 18.04 (Qt 5.9.5), or using MEGAcmd (which dont use Qt to generate thumbnails). 
Changing the extension to .svg_ prevents the generation of the thumbnail, so it is quite a nice workaround. Also, if you manage to upload the file via MEGAcmd or another OS, it will not re-generate the thumbnail as long as the file is not modified (in its content or modification date). Alternatively you can import it from here: https://mega.nz/#!tZ8QCAbb!MAavi4zIUKPqdtpF0s1v_MUZ5qYXhlg3_UL2qyBCctU

**Comment by haael** [comment]
Ubuntu version: 17.10 artful
Qt version: 5.9.1+dfsg-10ubuntu1
MEGAsync version: 3.6.6 (99a46c)

Is there some option or hack to disable thumbnail generation?

**Comment by polmr** [comment]
Currently there isn't (besides changing the extension). We are working on having a blacklist so as to disable thumbnail generation of problematic files.
