### ISSUE TITLE
Thunar Extension don't compile with Thunar >1.8

### ISSUE THREAD

**Issue by gspu** [meganz/MEGAsync#207]
qmake-qt4 MEGAShellExtThunar.pro
Project ERROR: Package thunarx-2 not found

Because Thunar >1.8 uses thunarx-3

Changing to thunarx-3 in MEGAShellExtThunar.pro
CONFIG += link_pkgconfig
PKGCONFIG+=thunarx-3 glib-2.0

results in this Error [MEGAShellExtThunar.txt](https://github.com/meganz/MEGAsync/files/2159199/MEGAShellExtThunar.txt)

**Comment by abhinavd** [comment]
Any updates on this issue? As far as I see, this still causes compile errors downstream at https://aur.archlinux.org/packages/thunar-megasync

**Comment by hobronc** [comment]
is there any development with this issue? are the thunar extension gonna be rewritten for gtk3?

**Comment by schw0reismus** [comment]
I've made [a pull request](https://github.com/meganz/MEGAsync/pull/323) which fixes the problem.
Also check [the AUR](https://aur.archlinux.org/packages/thunar-gtk3-megasync/).
