### ISSUE TITLE
Does not work on MacOS Mojave Public Beta

### ISSUE THREAD

**Issue by WebAction33** [meganz/MEGAsync#208]
Sync does not work on MacOS. After file scan, sync stopping and then nothing happen. Moreover it is make crashes with sync with Windows. No icons about sync status in Finder, no tools to create links from Finder.

**Comment by vtmateos** [comment]
Hi,
We have made some sync tests using latest dev beta (18A326g) and all works correctly, both Finder extension and sync process.

> Sync does not work on MacOS. After file scan, sync stopping and then nothing happen

Please check if your sync has been disabled. Go to Syncs tab and be sure checkbox is activated. If you are able to reproduce the problem, please send an email to support@mega.nz with detailed information to check the possible issue.

>Moreover it is make crashes with sync with Windows.

Does MEGAsync crash on Windows / macOS or both? Please, explain this point. If the program crashes, send the crash dump to support@mega.nz along with the url of the GitHub issue for analysis.

>No icons about sync status in Finder, no tools to create links from Finder.

Please, check that MEGAsync Finder extension is enabled at macOS settings. If the extension is not loaded in Finder, you will not be able to see any badge icon nor context menu option.

Hope this information helps you.

**Comment by WebAction33** [comment]
Only after update to Public Beta 2 sync complete successfully at all devices. Thank you for support
