### ISSUE TITLE
Syncing specific files 

### ISSUE THREAD

**Issue by AHLudan** [meganz/MEGAsync#21]
Hello

Is there a way to sync specific files ? , Using Syncs tab only allows for folders to be added?

And excluding folder and other files by name is not an option as they have a global effect (it doesn’t allow specific paths). [#9paths_not_working](https://github.com/meganz/MEGAsync/issues/9)

**Comment by vtmateos** [comment]
Hi,
The sync involves two folders local and remote for syncing, so if you want to achieve syncing specific files, maybe you can try to make some exclusions rules over our new .[megaignore](https://help.mega.io/es/installs-apps/desktop/megaignore) feature to accomplish your use case.

Thanks.
