### ISSUE TITLE
MegaSync doesn't show up in the system tray on KDE Plasma (Wayland session)

### ISSUE THREAD

**Issue by DevPre24** [meganz/MEGAsync#214]
Megasync behaves as no system tray is available on KDE Plasma (Wayland Session)

How to reproduce:
-Start a KDE Plasma (Wayland) session
-Open up MegaSync

On a Xorg session it behaves as expected.

![screenshot_20180716_124430](https://user-images.githubusercontent.com/13499337/42755619-4440a2da-88f9-11e8-9ef1-87f18b756b47.png)

This might help: [https://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/](https://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/)

**Comment by DevPre24** [comment]
Unfortunately this is still an issue.

**Comment by gbcox** [comment]
Experiencing the same issue.  They need to fix this.

**Comment by polmr** [comment]
What is your OS versión? Does the issue persist if you close MEGAsync (cogwheel->exit) and open it again?

**Comment by DevPre24** [comment]
> What is your OS versión? Does the issue persist if you close MEGAsync (cogwheel->exit) and open it again?

I'm on Arch Linux (Kernel: 4.14.86-1-lts, KDE Plasma: 5.14.4, KDE Frameweorks Version: 5.53.0, Qt: 5.12.0).

Note that this issue only happens when using a Plasma session, on Xorg (X11) Mega behaves as expected. 
After closing the application from the cogwhell and opening it again the issue persists.

**Comment by polmr** [comment]
I get you are using Wayland:

**Comment by polmr** [comment]
@DevPre24 Also, can you please close megasync and run it using:
```
XDG_CURRENT_DESKTOP=GNOME ./megasync
```
and tell us if the issue is fixed?

**Comment by polmr** [comment]
awesome, we will include some fix for the next version taking that into account.

**Comment by DevPre24** [comment]
Closing this issue. Fixed in 4.0.2.0-1.

**Comment by Moltkex** [comment]
This is still an issue in

**Comment by Jacob3075** [comment]
Getting a similar issue

Arch linux
kernel: 6.0.9-arch1-1
WM: hyprland 

```
Avoiding wayland
Error unsetting QT_QPA_PLATFORMTHEME vble
```

**Comment by KierPrev** [comment]
Same issue 
`Avoiding wayland
Error unsetting QT_QPA_PLATFORMTHEME vble`

**Comment by JavierDebian** [comment]
Still the issue form KDE Plasma wayland.

Fixed with a delay in the ~/.config/autostart/megasync.desktop file.

Change the Exec line for
Exec=bash -c "sleep 10 && megasync"

**Comment by Moltkex** [comment]
KDE Neon user here. It's working for me, tho with an error:
```
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 723b0436517467cf5d92ed37eea884ef
Version code: 50400.1
Module name: MEGA
Timestamp: 1722787190976
Operating system: Linux
System version:  neon 22.04/#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2
System release:  6.5.0-45-generic
System arch: x86_64
Error info:
Abortado (6) at address 0x3e800000f70
Stacktrace:
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7e9b34e969fc]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c) [0x7e9b34e969fc]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16) [0x7e9b34e42476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3) [0x7e9b34e287f3]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x90b53) [0x7e9b36490b53]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0xa701e) [0x7e9b364a701e]
/lib/x86_64-linux-gnu/libQt5Svg.so.5(_ZN12QSvgRendererC2ERK7QStringP7QObject+0x32) [0x7e9b39274972]
/usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so(+0x5cd4) [0x7e9b12149cd4]
/usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so(+0x3e4e) [0x7e9b12147e4e]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN5QIcon7addFileERK7QStringRK5QSizeNS_4ModeENS_5StateE+0x1e1) [0x7e9b35ddd811]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN5QIconC2ERK7QString+0x3a) [0x7e9b35dddbca]
/usr/bin/megasync(+0x3fb914) [0x5b2b8283d914]
/usr/bin/megasync(+0x4059d3) [0x5b2b828479d3]
/usr/bin/megasync(+0x412761) [0x5b2b82854761]
/usr/bin/megasync(+0x3a3b92) [0x5b2b827e5b92]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7e9b34e29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7e9b34e29e40]
/usr/bin/megasync(+0x3b2c75) [0x5b2b827f4c75]

```
It then stars and shows the tray icon.
