### ISSUE TITLE
Colon converted to escape sequence in filenames

### ISSUE THREAD

**Issue by haael** [meganz/MEGAsync#215]
If I create a file with a colon ":" in the filename, sync it to Mega and then sync it back to another computer, the colon is substituted with "%3a" sequence.

**Comment by dfpr** [comment]
I can confirm the same issue. I first used megasync on windows, then on linux, where the colon character inside file names is valid. The colon does appear on the file names on the web cliente but if I sync those files back they get downloaded with the escape sequence instead of the colon.
