### ISSUE TITLE
Copied files to 2nd computer - MEGAsync still want to download all

### ISSUE THREAD

**Issue by kimwue** [meganz/MEGAsync#216]
Hi,

I synced various files from computer **A** with MEGAsync (Linux Ubuntu). Now I copied those files manually to computer **B** and installed MEGAsync (Osx High Sierra). Although all files are already on computer **B**, MEGAsync tries to download all again?

Doesn't MEGAsync check just the hashcode to see those files are the same?
Is there a way to "correct" this?

And yes, the folder paths are correctly set.

Thanks,
Kim

**Comment by baizon** [comment]
Did you try a "Force a full scan"? I can't reproduce that issue.

**Comment by kimwue** [comment]
I tried a "Force a full scan" but result is still the same. How does MEGAsync compare files? Based on date only? Hashcode? Anything else I can do?

**Comment by javiserrano** [comment]
MEGAsync checks the hash (an sparse hash for big files), the size and the modification time of files. 

In this cause, I think that the modification time of files don't match and that is causing the problem.

The modification time of the files could have been changed when they were moved from computer *A* to *B*. It uses to happen specially when files are moved to FAT filesystems.

**Comment by kimwue** [comment]
Thanks a lot, issue was that I moved the files over using a FAT external drive. Did this now via NTFS and all works fine.

**Comment by udippel** [comment]
Yep. Had a similar thing, and now I am waiting for the roll-out of a new version that was promised to me which actually improves support of *FAT* file systems significantly.
