### ISSUE TITLE
Is possible to remove/disable status icon in windows?

### ISSUE THREAD

**Issue by Jorman** [meganz/MEGAsync#221]
Hi, I know that this seems strange, but there's a way to disable or remove the status icon from the folder that I've in sync?

Even with a modify to register, just to know how to do that, is my case I need to remove this status icon.

How can I do that?

Many thanks

Jo

**Comment by polmr** [comment]
Settings (cogwheel) -> Advanced -> Disable overlay icons

**Comment by Jorman** [comment]
Ouch, my bad! I searched but I never found it, was so easy!

Thank you and sorry for this stupid question
