### ISSUE TITLE
Does not sync on Ubuntu 18.04

### ISSUE THREAD

**Issue by pospi** [meganz/MEGAsync#223]
I've tried both the current version available for download, and building from latest source (`MEGAsync v3.6.7 (99a46c)`).

In both cases, the client appears to function correctly but no files are ever synced. Incoming files from other devices don't show up, and files added or modified locally are never uploaded. It seems to be "stuck" in some fashion.

Are there any known issues like this with latest Ubuntu, and/or any way I can get more debug info to troubleshoot further?

**Comment by pospi** [comment]
Ok, seems I have fixed it. Could be that the old database format differs from the new one?

Once I did `rm -Rf ~/.local/share/data/Mega\ Limited/` it started syncing again.

**Comment by polmr** [comment]
No, it should not differ. Perhaps your cache got corrupted for some reason. `Settings->Advanced->Force a full scan` would probably have been enough.

**Comment by pospi** [comment]
Nah, that wasn't working... Tried it a few times. The mystery prevails!

**Comment by texadactyl** [comment]
Xubuntu 18.04.1 with latest Mega x64 installed.
Ran into same issue: 2 phones and a Mac were syncing fine.  Out of the blue, my Xubuntu box stopped syncing.

Did not work: ```Settings->Advanced->Force a full scan```

Verified as working: ```rm -rf $HOME/.local/share/data/Mega\ Limited/``` and reregister with the web site.

**Comment by chuxau** [comment]
> Xubuntu 18.04.1 with latest Mega x64 installed.
> Ran into same issue: 2 phones and a Mac were syncing fine. Out of the blue, my Xubuntu box stopped syncing.
> 
> Did not work: `Settings->Advanced->Force a full scan`
> 
> Verified as working: `rm -rf $HOME/.local/share/data/Mega\ Limited/` and reregister with the web site.

I think the problem is a simple and silly one.  Basically, the synch client installs with a setting that does not enable syncs.  So, the initial sync is done, but no further update syncs will happen.

So, go to Settings --> Syncs ... and simply tick the checkbox besides the folder to sync to enable regular update syncs

**Comment by polmr** [comment]
Syncs are enabled by default. However, there might be some reasons for a sync to be automatically disabled (e.g: the local folder is deleted, accessible). I'm guessing here, but could it be possible that you are syncing some location that might not be mounted by the time MEGAsync starts (e.g: an external pendrive)?

**Comment by texadactyl** [comment]
Finally able to reproduce the "suddenly stops syncing" bug.  Please note that this happens only when something goes haywire in the SOURCE of the upload.

In my case, I was syncing between a locally-attached automatically-mounted USB 1TB drive and the megasync cloud.  All was well.  Then, somebody unplugged the drive without a proper `umount` command.  Megasync and others, obviously, complained.  The USB drive was reconnected and remounted.  Megasync stopped complaining but did not resume syncing.

Successful work-around:
1. Exit megasync using the desktop icon/app.
2. rm -rf $HOME/.local/share/data/Mega*
3. Restart megasync.
4. Re-register desktop app using existing login (richard.elkins@gmail.com) to megasync @ mega.nz.

This will (hopefully) not happen again as I have reorganized my storage using a new larger SSD and retired the USB disk for other reasons.

**Comment by texadactyl** [comment]
My Xubuntu installation up-to-date:

----- Ubuntu release -----
Description:	Ubuntu 18.04.2 LTS
Codename:	bionic
----- OS kernel name/release/version -----
4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
----- Machine hardware platform -----
x86_64
----- Video information -----
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: x11 (X.Org 1.19.6 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile version: 4.2 Mesa 18.2.8
----- Audio information -----
Audio:     Card Intel 7 Series/C216 Family High Definition Audio Controller driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.15.0-48-generic

**Comment by texadactyl** [comment]
My guess is that the megasync client on Ubuntu is not recovering from a local source failure under specific conditions (E.g. any read() error).  When encountering such an error, the client should re-position in its working list back to the beginning, once the local source is available again.  A forced local storage re-scan might be in order.

**Comment by texadactyl** [comment]
@pospi When you removed the tree, you worked around the issue, not fixed it.  I am certain that you had to restart the client and re-register to get syncing again.
