### ISSUE TITLE
MEGASYNC CLIENT DOES NOT TAKE DOENLOAD

### ISSUE THREAD

**Issue by BBijaya** [meganz/MEGAsync#224]
i tried downloading file but the megasync does not take the download even if i select the tick mark saying 
(Download using the MEGA desktop app for faster downloads)
either i have to manually put the url in megasync or download using browser.

**Comment by javiserrano** [comment]
There have been some problems in this feature, but they should be already solved if you are using the last version of MEGAsync (3.6.7). Please try again. If it still doesn't work for you, let me know the web browser that you are using and we will try to reproduce and fix the problem.

**Comment by polmr** [comment]
Unable to reproduce. Please, ensure you have MEGAsync running, and listening to the expected ports. The output of 
```
netstat -pan | grep megasync | grep -i listen
``` 
should be something like 
```
tcp        0      0 127.0.0.1:6341          0.0.0.0:*               LISTEN      XXX/megasync       
tcp        0      0 127.0.0.1:6342          0.0.0.0:*               LISTEN      XXX/megasync       
```
If that is correct, please refer this issue to support@mega.nz. They will guide you to provide required information and log file to be analyse and find out the cause of your issue.

Kind regards.

**Comment by MrNeon** [comment]
Found the problem, uMatrix was blocking requests to 127.0.0.1. Allowing them solves this issue.
I've used megasync with uMatrix on before. Must have been a change to uMatrix that started the problem.

**Comment by jediafr** [comment]
Hi,

I'm having the same issue with Megasync ( 3.7.1.0-2) not picking up downloads from Mega pages opened on chromium (Version 69.0.3497.92 (Official Build) Manjaro Linux (64-bit)).

my ports : 
tcp        0      0 127.0.0.1:6342          0.0.0.0:*               LISTEN      2490/megasync       
unix  2      [ ACC ]     STREAM     LISTENING     23024    2490/megasync        /run/user/1000/at-spi2-0CHIPZ/socket
unix  2      [ ACC ]     STREAM     LISTENING     23020    2490/megasync        /home/xxx/.local/share/data/Mega
unix  2      [ ACC ]     STREAM     LISTENING     23019    2490/megasync        /home/xxx/.local/share/data/Mega

I dont have umatrix.
