### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by tjbrn** [meganz/MEGAsync#233]
Trying to loggin in a account protected by two-factor authentication give an "Unknown Error"

megasync 3.6.6.0-3
4.18.9-arch1-1-ARCH

**Comment by polmr** [comment]
You need to update to a newer version of MEGAsync. 2FA support was added in 3.7.1: https://github.com/meganz/megasync/blob/master/build/MEGAsync/MEGAsync/debian.changelog
You can download the latest official version for Arch Linux from https://mega.nz/sync

**Comment by chisNaN** [comment]
Sorry for adding comment to this topic
so i guess its possible to enable 2fa for mega accounts?
