### ISSUE TITLE
Bug that is overloading HDD

### ISSUE THREAD

**Issue by slrslr** [meganz/MEGAsync#237]
Hello, i have downloaded https://mega.nz/linux/MEGAsync/Debian_9.0/amd64/megasync-Debian_9.0_amd64.deb
And installed it, it is megasync:amd64 3.7.1+3.1

Linux Kernel is Debian 4.15.4-1~mx17+1

I select MegaSync to be automatically started and after i login session within a like a minute i see my HDD is overutilized 100% and the cause is megasync process. This utilization takes for minutes and my PC eventually lagging. When killed megasync, the HDD stop making noise and all good.

I forgot to execute "lsof" command if it shows something useful, i do not know. Also do not know how to enable debug logging and where to find the log?

**Comment by polmr** [comment]
So .. you 
- installed megasync
- logged in
- configured a sync folder which is not mounted (??? how did you that? what did you exactly synced?) 

If you mount a folder that's synced the synchronization stops:
let's say, you select to sync `/media/afolder`, which is not mounted (it is just a folder). This will cause all the files in your remote synced folders to be downloaded in /media/afolder (causing a high use on your HDD). 
Then you mount some device into `/media/afolder`. megasync detects the folder has changed and stops synchronization. (files are no longer downloaded, HDD usage stops).
You need to ensure that you have your folder mounted before setting the synchronization, and to have it mounted before MEGAsync start running!

**Comment by slrslr** [comment]
Thank you for the reaction. I have found that i was wrong (i am sorry) in my initial explanation. The Sync directory is on the system drive, not on ext. drive. So far i no longer see the high HDD usage of the megasync, so i assume it was possibly normal activity. Thank you
