### ISSUE TITLE
He's on Windows, I'm a Mac.

### ISSUE THREAD

**Issue by iojanis** [meganz/MEGAsync#239]
I'm using MEGAsync on my two Mac machines. Mainly for syncing Ableton Live Project files with my partner. We noticed a strange error! We're naming our files always with the first letter of our name and a version number to prevent data loss. But sometimes he still works on a file, while I have already opened it. The Problem felt something like this:

He edited the file, 
I opened it,
He saved it to the same file,
MEGAsync loaded it up,
and tried to download it to my Computer,
it failed and the file was gone.

AFTER that... it wouldn't sync again from his side. 
But my synchronisation was still working fine. 

Then he had to open preferences -> sync and toggle the folder off, restart the client and again toggled the folder to on. Then he was able to sync again to the folder.

WHAT THE FUCK IS HAPPENING?

**Comment by vtmateos** [comment]
Hi,

Sorry for the inconveniences.

Please contact to support@mega.nz. They will guide you to provide required information and log file to be analyse and find out the cause of your issue.

Kind regards.
