### ISSUE TITLE
Stuck at "Logging in"..

### ISSUE THREAD

**Issue by spinninghamster** [meganz/MEGAsync#240]
I can't login with both Mac app and web interface. I have the same issue like:
https://github.com/meganz/MEGAsync/issues/177

Anyone know how to fix this? We urgently need to access the files..

**Comment by vtmateos** [comment]
Hi,

Sorry for the inconveniences.

Please contact to support@mega.nz. They will guide you to provide required information and log file to be analyse and find out the cause of your issue. The problem could be a temporary server side issue. If the problem persists, follow steps aforementioned and contact support for a deep analysis.

Kind regards.
