### ISSUE TITLE
Sync hidden files ?

### ISSUE THREAD

**Issue by MagixInTheAir** [meganz/MEGAsync#247]
I see hidden files (especially the ones with names starting with a dot) aren't synced with my cloud folder, and can find no option for that.

Is there any technical limitation against doing so ?
Could an opt-in option be integrated in order to sync hidden files in MegaSync ?
Thanks

**Comment by vtmateos** [comment]
Hi,
You can configure exclusion rules, files, etc at Advanced tab in Settings dialog. Files starting with dot are excluded by default. If you want to sync them, just remove the rule ".*"

Regards.

**Comment by asidirop** [comment]
If you remove the rule ".*" in order to sync hidden files, then this causes the MEGA to produce multiple (infinite?) instances of each folder. It probably follows the "." directory. There is a bug here.

**Comment by planetsLightningArrester** [comment]
> If you remove the rule ".*" in order to sync hidden files, then this causes the MEGA to produce multiple (infinite?) instances of each folder. It probably follows the "." directory. There is a bug here.
> I run ubuntu 18.04.

Not sure if I'm too late, but I just removed the ".*" and added "." and ".." to prevent MEGA Sync to upload these specifics folders. Using W10.

**Comment by mattw-mega** [comment]
"." and ".." are excluded from sync consideration at a very low level in MEGAsync, it's not necessary to add those to your exclusion list.  I've also just tested the latest MEGAsync (4.2.5) on W10 and cannot reproduce the issue - please make sure you are running that version, and if you can reproduce it, please let us know the local and remote folder structure, and sync config, that will exhibit the problem.  Thanks

**Comment by planetsLightningArrester** [comment]
> "." and ".." are excluded from sync consideration at a very low level in MEGAsync, it's not necessary to add those to your exclusion list. I've also just tested the latest MEGAsync (4.2.5) on W10 and cannot reproduce the issue - please make sure you are running that version, and if you can reproduce it, please let us know the local and remote folder structure, and sync config, that will exhibit the problem. Thanks

I'm sorry, I think I didn't make my self clear. I don't have a issue. I was just saying the way I did to make it work: removed the ".*" and added "." and "..".

But anyway thanks for the info about  "." and ".." being unnecessary to add.

**Comment by MoonsofMoons** [comment]
I wanted to specifically backup only a hidden directory (a sub-directory of my /home/.config/ directory on a Linux machine). Could not find a way to do it since the desktop Mega application has its own file browser that ignores hidden folders. I was able to work-around by making a symlink to the directory and then pointing Mega at that.

**Comment by TakisAngelides** [comment]
I fixed this issue by modifying the .megaignore file within the folder I wanted it to sync hidden files. The text I removed from that file was specifically only: -:.*
