### ISSUE TITLE
Help create restrictions for firewall rules.

### ISSUE THREAD

**Issue by tele1** [meganz/MEGAsync#251]
For example I want block outgoing connections with gufw / ufw firewall.
But I don't know which IP or which ports to unlock.

Is typing IP to firewall  is  good idea?

**Comment by maravento** [comment]
Create an acl with all mega urls and block them with squid-cache. example:

```
# content of mega.lst 
# https://help.mega.io/security/data-protection/official-domains
.mega.io
.mega.nz
.mega.co.nz
.megapay.nz
```
and
```
acl megablock dstdomain "/path_to/mega.lst"
http_access deny megablock
```
