### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [meganz/MEGAsync#259]
i've downloaded Version '4.0' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. 
the *CFBundleVersion* and *CFBundleShortVersionString* entries in your Info.plist file are missing.

all apps on macOS are supposed to contain valid version information.

looking at your source, i guess you could add them in installer_mac.sh with something like 

/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${PROJECT_DIR}/${INFOPLIST_FILE}"

**Comment by robertleeblairjr** [comment]
> i've downloaded Version '4.0' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all.
> the _CFBundleVersion_ and _CFBundleShortVersionString_ entries in your Info.plist file are missing.
> 
> all apps on macOS are supposed to contain valid version information.
> 
> looking at your source, i guess you could add them in installer_mac.sh with something like
> 
> /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${PROJECT_DIR}/${INFOPLIST_FILE}"

I came here to submit an issue for the versioning information since it conflicts with their appcast, as well. Thanks.

**Comment by core-code** [comment]
there are 157 open issues and no one has responded on this problem in 4 months, so i think our only bet on getting this fixed is sending a pull request...

**Comment by robertleeblairjr** [comment]
> there are 157 open issues and no one has responded on this problem in 4 months, so i think our only bet on getting this fixed is sending a pull request...

I believe you're correct. Maybe they just use this repo for periodic internal development uploads and may address bug submissions but there's no feedback or collaboration. LOL. It would probably be easier to just contact them directly at mega.nz.

**Comment by core-code** [comment]
@mattw-mega i've sent a PR to fix this issue

**Comment by core-code** [comment]
i can confirm that the official macOS download for 4.2.2 finally contains a version number. thanks

**Comment by core-code** [comment]
note that the version number embedded into version "4.3.0.8" is only "4.3.0". 

is it cropped to 3 digits?
