### ISSUE TITLE
Systray icon is too pixelated/blurry in 4K displays (NON Hi-DPI panels)

### ISSUE THREAD

**Issue by sl1pkn07** [meganz/MEGAsync#26]
a pic:

![](http://wstaw.org/m/2016/07/30/Screenshot_20160730_154705.png)

on Plasma 5 (KDE KF5)

**Comment by polmr** [comment]
Sorry for the late response. I'm unable to reproduce this with plasma. however, I've found that plasma doesn't adjust megasync icon properly (megasync icon is replaced by a generic icon) when tweaking the appearance (e.g. increaseing panel size). Restarting megasync solves this.

**Comment by polmr** [comment]
In any case. The icon has a fixed size of 22x22. Although I am unable to reproduce such visible scale issues, it is clear that it won't scale perfectly given its fixed nature, although it'll be unnoticed in most cases. We are not using scalable icons to prevent compatibility issues with all different qt versions and all the desktop environments avaiable.

**Comment by sl1pkn07** [comment]
my desktop is 4k, if this help you

**Comment by polmr** [comment]
ok, that's why you notice ... this is something we'll consider, thanks @sl1pkn07.

**Comment by sl1pkn07** [comment]
any notice?

greetings

**Comment by polmr** [comment]
Hi, we have included support for high resolution screens in linux (by allowing Megasync UI to scale), for distros shipping QT >=5.6. However we aren't using scalable icons yet. This is in our TODO list with a not so high priority. We'll work on that eventually, thanks for the reminder!

**Comment by majidazimi** [comment]
I think [this ](https://ask.fedoraproject.org/en/question/99739/black-background-of-megasync-client-icon-in-system-tray/)is also a similar problem. I'm facing it currently on Fedora 25 KDE with the latest updates.

**Comment by aldomann** [comment]
@polmr it would be nice if that also allowed to manually change the icons for those who want to have cohesive systray icons.

**Comment by polmr** [comment]
Icons are hardcoded into the executable. Installing them separately will certainly increase complexity in installers and could potentially create some issues. Plus, what's wrong with red? ;-). In any case, if someone really ... really want to change those, he can always compile megasync himself. However, we are considering using scalable icons to solve the pixelated appearance.

**Comment by baizon** [comment]
@majidazimi I had the same issue. It's because the icon is loaded before the kde notification area. I just wrote a simple script [(mesasync.sh)](https://github.com/baizon/Scripts/blob/master/megasync.sh) that delays the start, and now everything works fine.

**Comment by polmr** [comment]
This branch https://github.com/meganz/desktop/tree/svglinuxstatusIcons uses svg status icons. Unfortunatelly we've found some incompatibilities with certain distributions/desktop environments and svg icons (e.g: Gnome Shell in Fedora 25)

**Comment by sl1pkn07** [comment]
@polmr 404

**Comment by sl1pkn07** [comment]
i think i can fix the issue changing this icons:

https://github.com/meganz/MEGAsync/blob/4cfa9c42a38c003e29eebbb5ce56f996fcba3f6a/src/MEGASync/gui/images/22_uptodate.png
https://github.com/meganz/MEGAsync/blob/4cfa9c42a38c003e29eebbb5ce56f996fcba3f6a/src/MEGASync/gui/images/22_synching.png
https://github.com/meganz/MEGAsync/blob/4cfa9c42a38c003e29eebbb5ce56f996fcba3f6a/src/MEGASync/gui/images/22_paused.png
https://github.com/meganz/MEGAsync/blob/4cfa9c42a38c003e29eebbb5ce56f996fcba3f6a/src/MEGASync/gui/images/22_logging.png
https://github.com/meganz/MEGAsync/blob/4cfa9c42a38c003e29eebbb5ce56f996fcba3f6a/src/MEGASync/gui/images/22_warning.png

with others with major resolution (256x256px for example) in compile time

i need test it

**Comment by sl1pkn07** [comment]
YEA. work it!

![spectacle m11222](https://user-images.githubusercontent.com/462213/29252158-4984912a-8062-11e7-9c03-9d3024e0eb9b.png)


![22_logging](https://user-images.githubusercontent.com/462213/29252198-f7c5e252-8062-11e7-824c-bdd74ffa6f0d.png)
![22_paused](https://user-images.githubusercontent.com/462213/29252177-aae06d04-8062-11e7-84c8-65ffe9b09528.png)
![22_synching](https://user-images.githubusercontent.com/462213/29252178-ad14cd5e-8062-11e7-84b1-cbed2c2b6768.png)
![22_uptodate](https://user-images.githubusercontent.com/462213/29252179-af6977f8-8062-11e7-9678-22ae16b1fc8c.png)
![22_warning](https://user-images.githubusercontent.com/462213/29252181-b1aabe8c-8062-11e7-967a-4ab8971f6cc4.png)

~~~bash
convert -density 157 -resize 256 login_ico.ico 22_logging.png
mv 22_logging-0.png 22_logging.png
rm 22_logging-*.png
convert -density 157 -resize 256 tray_pause.ico 22_paused.png
mv 22_paused-0.png 22_paused.png
rm 22_paused-*.png
convert -density 157 -resize 256 tray_sync.ico 22_synching.png
mv 22_synching-0.png 22_synching.png
rm 22_synching-*.png
convert -density 157 -resize 256 app_ico.ico 22_uptodate.png
mv 22_uptodate-0.png 22_uptodate.png
rm 22_uptodate-*.png
convert -density 157 -resize 256 warning_ico.ico 22_warning.png
mv 22_warning-0.png 22_warning.png
rm 22_warning-*.png
~~~
(-density 157 is for the pixel density of my display)

exist SVG files for that images? for making a better conversion

**Comment by polmr** [comment]
we will probably include svg icons in the next release (soon to come)

**Comment by sl1pkn07** [comment]
with 64x64px gets the same look as 256x256

changing the script posted avobe acording of this

greetings

**Comment by polmr** [comment]
svg tray icons have been incorporated in version 3.5.0
