### ISSUE TITLE
Shared folder copied to new drive - now client want to upload entire directory to cloud

### ISSUE THREAD

**Issue by Beamboom** [meganz/MEGAsync#262]
I did a replacement of the home disk, and copied my entire home directory (including MEGAsync directory) to the new drive and mounted that on /home. But now when I boot into the new home, the client want to upload the entire directory up to the cloud. Is there a way to avoid this?

File system: ext4, nonencrypted
OS: Ubuntu 18.10

**Comment by polmr** [comment]
MEGAsync cache & preferences (included synced paths) are stored at `$HOME/.local/share/data/Mega Limited/MEGAsync`. They synchronizations you had settled in your previous installation should have been restablished. You can remove that entire directory and login and reconfigure MEGAsync again.

**Comment by Beamboom** [comment]
Aha! There's stuff stored under .local. Now that explains it - thank you so
much for that info!


Den man. 28. jan. 2019 kl. 10:13 skrev polmr <notifications@github.com>:
