### ISSUE TITLE
Hard to click on the download in the queue list

### ISSUE THREAD

**Issue by brystfire08** [meganz/MEGAsync#263]
Since the last update most of the time there is no response in clicking on a download in list. I am trying to click a download in the queue then right click to move it to top. I have to click multiple times just to have the file in queue highlighted.

There are about 400 items in my queue if that may cause the issue.

I am using windows 7 Professional 32 bit.

**Comment by polmr** [comment]
Hi @brystfire08 , this is a known issue that will be fixed in next release. In the meantime, there's one trick to overcome that: try to press the mouse, then move it a little bit (a single pixel should do) and then release it. Thanks for reporting anyway.

**Comment by vtmateos** [comment]
Please try our new version (4.0.2) from https://mega.nz/sync. It should solve all the aforementioned issues
