### ISSUE TITLE
Individual transfer pause doesn't work after the v.4 update.

### ISSUE THREAD

**Issue by LSmyrnaios** [meganz/MEGAsync#266]
Hallo,

After updating to the v.4, I noticed that I can no longer pause an individual tranfer...
Why was this functionality removed?
Please re-add this functionality, it's very-very usefull if you want to skip a big file.

Also, could you add an option to un-track a file when you see it being transfered? (Maybe a different issue could be opened for this, but it's related to the pause/skip functionality.)

Thanks

**Comment by LSmyrnaios** [comment]
After re-checking I found that the functionality is there, it's just harder to use it because you have first to left-click several times the wanted file to select it and then right-click and choose "Pause transfer".
So, the problem now is that firstly you cannot just right-click the wanted file, but you have to left-click it to select it first.
Secondly, the left-click doesn't work well since you have to click several times in spesific places of the interface in order for the wanted file to be selected.

**Comment by vtmateos** [comment]
There is a bug with context menu options and row selection at Transfer manager with MEGAsync version 4.0.1. It will be fixed in next MEGAsync version. Apologies for the inconveniences. Stay tunned for future updates.
Kind regards.

**Comment by vtmateos** [comment]
Please try our new version (4.0.2) from https://mega.nz/sync. It should solve all the aforementioned issues

**Comment by LSmyrnaios** [comment]
I confirm the bug was fixed, thank you.

As for the "un-track a file" request, I have opened a new [issue](https://github.com/meganz/MEGAsync/issues/363)
