### ISSUE TITLE
Cannot install Megasync on Debian 10

### ISSUE THREAD

**Issue by Dvlnst** [meganz/MEGAsync#267]
Hello,

I've tried to install Debian 9 and Ubuntu 18.10 versions. Neither of both woked due libraw15 dependency. Debian Buster is using libraw19. Any idea of how to solve it? 

Thank you.

**Comment by polmr** [comment]
Hi @Dvlnst , we will provide packages for Debian 10 version soon. In the meantime you can always compile it yourself following instructions here: https://github.com/meganz/MEGAsync/blob/master/README.md .

**Comment by Dvlnst** [comment]
Thanks for the quick reply @polmr. That's what I did and It works fine.

**Comment by wvagner** [comment]
Hi @polmr ! Any news on providing packages for Debian? Regards

**Comment by msnjuegos** [comment]
Hi, I have the same problem and I can't compile it. Any news respect the new version?

**Comment by mexsudo** [comment]
I too need to have this fixed. unable to compile.... status update please!

**Comment by Dvlnst** [comment]
Hi folks,

Did you all clone and compile the project in a directory without whitespaces? There is some little issues inside /src/configure bash script. You have two options:

1 - **As a workaround** - Clone and compile the project inside a directory without whitespaces (e.g. /home/user/projects/MEGAsync). Works fine.

or

2 - Fix configure script - Variable archives (archives=$root_dir/archives) must be (archives="$root_dir/archives") and must be used inside "" to create/remove directories and keep full paths:

 - line 75: mkdir $archives --> mkdir "$archives"
 - line 48-101: rm -fr $archives --> rm -fr "$archives"
 - line 83: -o $archives --> -o "$archives"

Kind regards.

**Comment by msnjuegos** [comment]
After the command "make" and several minutes, the last output displayed in terminal is
make[1]: Leaving directory '/home/alan/opt/MEGAsync/src/MEGASync'
And megasync is not installed yet. I tried your advices.

**Comment by polmr** [comment]
There are Debian 10 packages available at https://mega.nz/sync
