### ISSUE TITLE
translate error

### ISSUE THREAD

**Issue by 13dev** [meganz/MEGAsync#27]
in src/MEGASync/gui/translations/MEGASyncStrings_pt.ts Line: 2210

is
<translation>ssistente de configuração - MEGAsync</translation>

change to:
<translation>Assistente de configuração - MEGAsync</translation>

**Comment by vtmateos** [comment]
Thanks for pointing out! Will be fixed in next release.

**Comment by 13dev** [comment]
No Problem !
Mega is the Best :)!
