### ISSUE TITLE
Tray icon is gone on MEGAsync linux 4.0.2.

### ISSUE THREAD

**Issue by bungabunga** [meganz/MEGAsync#276]
I'm using MEGAsync on Ubuntu 18.10. After update to 4.0.2. the tray icon is gone. The program is running normally, only tray icon is missing.

**Comment by polmr** [comment]
This is some known issue with 18.10 package linking against qt4 instead of qt5. It will be fixed asap. In the meantime, remember you can display the main interface by launching MEGAsync again. Apologies for the inconvenience and thanks for reporting that.

**Comment by bungabunga** [comment]
fixed with the new version. thanks!
