### ISSUE TITLE
Problem dependencies on Ubuntu 19.04 (libraw16)

### ISSUE THREAD

**Issue by emanuc** [meganz/MEGAsync#279]
> sudo apt install ./Scaricati/megasync-xUbuntu_18.10_amd64.deb
> Lettura elenco dei pacchetti... Fatto
> Generazione albero delle dipendenze       
> Lettura informazioni sullo stato... Fatto
> Nota, viene selezionato "megasync" al posto di "./Scaricati/megasync-xUbuntu_18.10_amd64.deb"
> Alcuni pacchetti non possono essere installati. Questo può voler dire
> che è stata richiesta una situazione impossibile oppure, se si sta
> usando una distribuzione in sviluppo, che alcuni pacchetti richiesti
> non sono ancora stati creati o sono stati rimossi da Incoming.
> Le seguenti informazioni possono aiutare a risolvere la situazione:
> 
> I seguenti pacchetti hanno dipendenze non soddisfatte:
>  megasync : Dipende: libraw16 (>= 0.16.0) ma non è installabile
> E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

**Comment by reckerswartz** [comment]
@emanuc
 https://packages.ubuntu.com/bionic/amd64/libraw16/download

http://security.ubuntu.com/ubuntu/pool/main/libr/libraw/libraw16_0.18.8-1ubuntu0.2_amd64.deb

will resolve the issue.

**Comment by polmr** [comment]
There's a package for Ubuntu 19.04 already available [here:](https://mega.nz/linux/MEGAsync/xUbuntu_19.04/amd64/megasync_4.0.2_amd64.deb)
