### ISSUE TITLE
Make macOS menu icon normal size

### ISSUE THREAD

**Issue by jaredreich** [meganz/MEGAsync#28]
It's too small, looks out of place, and messes with my mac zen... ;)

<img width="370" alt="screen shot 2016-08-12 at 7 34 27 pm" src="https://cloud.githubusercontent.com/assets/8563847/17640735/d1197af2-60c3-11e6-9201-4d09763f02d1.png">
(See the Telegram icon size for correct size)

Great work team MEGA!

**Comment by vtmateos** [comment]
Dear user,

Tray icon seems to be correctly displayed over 5.6.1 version. Feel free to test and it the UI issue is reproducible on your side, feel free to create a new issue to we can help you.

Thanks for your report.
