### ISSUE TITLE
Create a snap package?

### ISSUE THREAD

**Issue by emanuc** [meganz/MEGAsync#280]
The advantage of snap packages is that you can include dependencies, so you no longer have problems with broken or unresolvable dependencies on various versions of Ubuntu or not.

[https://snapcraft.io/](url)

**Comment by besoeasy** [comment]
Still waiting !

**Comment by sed-i** [comment]
Duplicates #155.

**Comment by emanuc** [comment]
> Duplicates #155.

**Comment by emanuc** [comment]
> Duplicates #155.

Closed, thanks
