### ISSUE TITLE
Portable megasinc on Windows?

### ISSUE THREAD

**Issue by sindzicat** [meganz/MEGAsync#283]
Hello.

I use MEGAsync on my work computer (Windows 7). Anybody can do smth on my computer when I alive. Theoretically I can to log out every time at the end of work day, but I'd like to place mega on an encrypted drive. Is this possible to get a portable version of MEGAsync?

As alternative MEGAsync may ask special password on the first start after the computer was turned on.

Andrey.

**Comment by javaarchive** [comment]
Me too, I need to upload a large amount of files, using mega sync on a computer I have no admin rights on.

**Comment by sindzicat** [comment]
I made Mega portable using [these instructions](https://www.thumbapps.org/2016/06/MEGA-Sync-Client-free-cloud-uploader-downloader-portable.html). But I didn't create a portable installer. All works fine for me.

**Comment by Himusaki** [comment]
> I made Mega portable using [these instructions](https://www.thumbapps.org/2016/06/MEGA-Sync-Client-free-cloud-uploader-downloader-portable.html). But I didn't create a portable installer. All works fine for me.

Can u teach me also how can i create mega portable?
