### ISSUE TITLE
Dependency is not satisfiable: libraw16 (>= 0.16.0)

### ISSUE THREAD

**Issue by webzorg** [meganz/MEGAsync#289]
I got this error: `Dependency is not satisfiable: libraw16 (>= 0.16.0)` while installing on Debian testing which should have even newer packages than Ubuntu 18.10 does. I have 2fa activated and I cannot use megasync until this issue is resolved.

**Comment by Dvlnst** [comment]
Duplicate #267

**Comment by polmr** [comment]
There are Debian 10 packages available at https://mega.nz/sync

**Comment by webzorg** [comment]
Thank you!

**Comment by Ultome** [comment]
Hello,
I am using the Debian 10 .deb file and I am getting this exact error. What should I do? I also tried to build it from source but it doesn't appear to install anything on my computer (it takes time though). Any suggestion?

**Comment by warloxian** [comment]
Same here. Using Parrot sec and same error

**Comment by NewsunBanjade** [comment]
#565 See This Here is Solution

**Comment by Soyasi** [comment]
ln -s /usr/lib64/libraw.so.20 /usr/lib64/libraw.so.16 funciona en opensuse
