### ISSUE TITLE
Notes on Linux instructions in README.md

### ISSUE THREAD

**Issue by Logic-gate** [meganz/MEGAsync#29]
Addendum and Notes to/on Linux instructions

* `qmake-qt4` fails `qmake` for Qt5 succeeds.
*  While running `build_sdk.sh` -- `c-ares` fails on some systems due to a missing CFLAG. Granted not all systems will face this issue, a notice in README would do. I would also like to inquire as to why `c-ares` and other pkgs and libs are in the dependency list while `build_sdk` has specific instructions to build it from source?
* Dependencies are debian-based/Ubuntu downstream pgk names. i.e. Downstream `libcrypto++-dev`vs upstream `cryptopp`. Having upstream pgks would make it easier for those on non-debian/ubuntu distros.
* OpenGL is not in the dependencies. I am assuming that this is due to dependency amplification and it is also assumed that OpenGL libs, especially devel-libs will get installed with an already stated dep. 

NOTE: Built on Solus

**Comment by polmr** [comment]
@Logic-gate thanks for the inputs.

> qmake-qt4 fails qmake for Qt5 succeeds.

Compiling with qt5 resulted in problems in the integration with the different desktops. It is still not recommended. However, for some distributions 'qmake' command does not exists when installing qt4 (whereas qmake-qt does). A word on that will be added

>While running build_sdk.sh -- c-ares fails on some systems due to a missing CFLAG. Granted not all systems will face this issue, a notice in README would do. 

Which flag? Would you care to elaborate this one (paste a log) please? 
>I would also like to inquire as to why c-ares and other pkgs and libs are in the dependency list while build_sdk has specific instructions to build it from source?

As a general rule, we tend to use system libs. However, in order to solve the situations where either the library is missing or problematic, build_sdk.sh provides the means to download and compile the library.

> Dependencies are debian-based/Ubuntu downstream pgk names. i.e. Downstream libcrypto++-devvs upstream cryptopp. Having upstream pgks would make it easier for those on non-debian/ubuntu distros.

Although I agree that upstream names would be more ... generic, we indicate the packages for the most common distribution. Finding out the corresponding packages for other distros should be pretty foward for the interested parties. Anyway, the text will be reviewed to address this. 

>OpenGL is not in the dependencies. I am assuming that this is due to dependency amplification and it is also assumed that OpenGL libs, especially devel-libs will get installed with an already stated dep.

AFAIK, OpenGL is not a direct dependency.

**Comment by Logic-gate** [comment]
Thank you for clarifying my inquisitive-it's 3am-I-need-to-sleep line of questions.

> Which flag? Would you care to elaborate this one (paste a log) please?

```
/c-ares-1.11.0 # ./configure
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking whether to enable debug build options... no
checking whether to enable compiler optimizer... not specified (assuming yes)
checking whether to enable strict compiler warnings... no
checking whether to enable compiler warnings as errors... no
checking whether to enable curl debug memory tracking... no
checking whether to enable hiding of library internal symbols... yes
checking whether to expose internal static functions for testing... no
checking for path separator... :
checking for sed... /usr/bin/sed
checking for grep... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ar... /usr/bin/ar
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking whether to build with code coverage support... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
configure: using CFLAGS: -mtune=generic -march=x86-64 -ftree-vectorize -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fno-omit-frame-pointer -fstack-protector-strong --param ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -feliminate-unused-debug-types -Wno-error -Wp,-D_REENTRANT
configure: CFLAGS error: CFLAGS may only be used to specify C compiler flags, not macro definitions. Use CPPFLAGS for: -D_FORTIFY_SOURCE=2
configure: error: Can not continue. Fix errors mentioned immediately above this line.
```

The odd thing about the macro(`D_FORTIFY_SOURCE=2`) is that it's usually frowned upon seeing as how if the check fails, it will cause run-time errors. But it seems to work flawlessly on https://solus-project.com. Note this only affects `c-ares`.

**Comment by polmr** [comment]
There's something weird here... -D_FORTIFY_SOURCE=2 is only added to CXXFLAGS (not to CFLAGS which causes cares configuration to complaint). I can reproduce this with `export CFLAGS=-D_FORTIFY_SOURCE=2`. Do you have a clean environment? Could it be that solus adds default CFLAGS??

**Comment by Logic-gate** [comment]
Interesting...

Unfortunately no, I have played more 

I did a duckduckgo search(because google is too mainstream *shrugs*) and found the gcc pkg in solus..this was in the change log. Note they are exporting/replacing the fortify_source. 

```

diff --git a/actions.py b/actions.py
index aef7d72..1cd4f8c 100644
--- a/actions.py
+++ b/actions.py
@@ -21,8 +21,8 @@ def setup():
     shelltools.cd (BuildDir)
 
     # Because GCC is a dope.
-    cflags = get.CFLAGS().replace("-D_FORTIFY_SOURCE=2", "")
-    cxxflags = get.CXXFLAGS().replace("-D_FORTIFY_SOURCE=2", "")
+    cflags = get.CFLAGS().replace("-D_FORTIFY_SOURCE=2", "").replace("-fexceptions", "")
+    cxxflags = get.CXXFLAGS().replace("-D_FORTIFY_SOURCE=2", "").replace("-fexceptions", "")
 
     shelltools.export("CFLAGS", cflags)
     shelltools.export("CXXFLAGS", cxxflags)
```
Source: https://git.solus-project.com/packages/gcc/commit/?id=373c6f8

It seems that I have overreacted when I stated "c-ares fails on some systems" . It should be, "one system". Though, I am pretty sure some Arch flavors have a similar setup. Anyway, thanks for taking the time and reviewing this...it is much appreciated.

**Comment by polmr** [comment]
This sounds like a "you do it secure or ... you do it secure" kind of enforcement. We can add a word on this particular situation. Thank you for your inputs.

**Comment by Logic-gate** [comment]
Will do. 

I made http://ma.tc/ehuboqatec.md listing the needed instructions for Solus. It might help some from other communities still scratching their heads as why it wont build properly. 

Note: the paste is there to stay, no expiry period.
Thank you.

I think it's fair to say that this issue is closed...

**Comment by polmr** [comment]
I've updated the readme with all the stuff discussed here -link for instructions included- (it will not be updated inmediately, but will be there eventually). Thanks @Logic-gate.
