### ISSUE TITLE
MEGAsync download old image file after in place resize

### ISSUE THREAD

**Issue by andrewpros** [meganz/MEGAsync#291]
Hi.
My issue is, every time i resize an image in place with XnView and overwrite it MEGAsync starts immediately to re-download the old one, so i had like 310kb jpg image, resized it, the size was 177kb, but MEGAsync reverted it.
I can even close MEGAsync, resize the image and overwrite, run MEGAsync again and it will still re-download the old one.
It works with every overwritten image.

**Comment by vtmateos** [comment]
Hi,

If you are able to reproduce it, please contact our support team: support@mega.nz for further investigation.

Thank you.
