### ISSUE TITLE
Compile error on ARM

### ISSUE THREAD

**Issue by dragonnn** [meganz/MEGAsync#3]
MEGAsync is first full open-source so I want to install it on my Rassberry Pi 2 but in CrashHandler.cpp they is some platform specific code :/. 

                   #else
                        #error NOT_SUPPORTED
After compiling that lines it compiles fine and works.

**Comment by javiserrano** [comment]
Thank you very much for your report.

Could you check if this code just before the lines you have posted fixes the problem?
``` 
            #elif defined(__arm__)
                ucontext_t* uc = (ucontext_t*) secret;
                pnt = (void*) uc->uc_mcontext.arm_pc;
```

I currently don't have a RPI2 to test. I will try to do it as soon as possible.

**Comment by polmr** [comment]
Based on my experience, compilation is fine for Raspberry Pi (Raspbian 8.0). As a matter of fact, Raspbian 8.0 is now supported and a client can be downloaded at: https://mega.nz/#sync
