### ISSUE TITLE
Cannot view the full excluded paths in Settings->Advanced (UI-bug).

### ISSUE THREAD

**Issue by LSmyrnaios** [meganz/MEGAsync#305]
There's no bar to slide to the right in order to see the full paths which are already excluded.

I am running MEGAsync on Ubuntu 18.04

**Comment by polmr** [comment]
This will likely be related to scaling issues that have been addressed for the incoming new version of MEGAsync. In the meantime, you'd probably be able to scroll using mouse wheel.

**Comment by LSmyrnaios** [comment]
Nope, there is no way to scroll right, only down.

**Comment by polmr** [comment]
Reproduced. Will be fixed in the next release

**Comment by LSmyrnaios** [comment]
I confirm, it was fixed in v.4.1.1
