### ISSUE TITLE
Update outdated libcurl in 3rdparty.zip 

### ISSUE THREAD

**Issue by kenkit** [meganz/MEGAsync#315]
There was a bug I came across in my other project involving libcurl , almost all older versions when running google tests. "SEH Exception" the newer versions old libcurl don't have this bug.
The same bug was present when running download tests with mega sdk.

**Comment by Vascom** [comment]
You can build and use megasync dinamically linked with system curl.

**Comment by kenkit** [comment]
That's what I did to get around that bug, Closing since this is no longer an issue, but it can be a pain if you don't know whats causing it. I spent months on another project trying to solve this because I couldn't figure why the exception was occurring.

**Comment by Vascom** [comment]
This is problem of bundling libs.
Always unbundle 3rdparty libs as more as possible and all will work excellent.
