### ISSUE TITLE
 [macOS Catalina Beta 2]

### ISSUE THREAD

**Issue by chrisspiegl** [meganz/MEGAsync#316]
I am running the MEGAsync client on macOS Catalina Beta 2 and my main issue right now is that I am not able to upload any files with the interface or add a sync folder.

The steps I am doing:

1. Start MEGAsync
2. Click on Menu Bar Icon
3. Click Gear Icon
4. Click either "Upload" or "Add Sync"
5. "Upload" just does nothing (the app seems to choke for a moment)
6. "Add Sync" opens the interface to choose the two folders, where I an choose the "MEGA folder" but when I click on "Choose" for the "Local folder" nothing happens at all (again the app seems to freeze a little bit).

I have tried giving the app Full Disk Access but that does not seem to change anything. I have tried googling but I was not successful.

I'd appreciate any help possible. ❤

MEGAsync Version: 4.1.1 (30853f9)

**Comment by vtmateos** [comment]
Thanks @chrisspiegl for the detailed report. We're working on a fix for the issue. The problem is caused accessing `NSOpenPanel`.

If you want to keep using MEGAsync please use non-beta macOS versions (e.g Mojave) in the meantime.

Thanks again and apologies for the inconveniences.

**Comment by vtmateos** [comment]
Hi @chrisspiegl ,

It seems that new Catalina beta from July 2 fixed the issue. Details of the release are: `macOS Catalina 10.15 beta 3 (19A501i)` Could you check if the problem is already fixed for you?

Thank you.

**Comment by chrisspiegl** [comment]
@vtmateos, you are correct. The new beta of Catalina fixed the issue already. Guess that's one point for just waiting for the final (or close to final) release before starting to fix stuff.

Thanks for the notification about this, installed, tested, all good to go for now.
