### ISSUE TITLE
Windows Context Menu "Upload to MEGA" Setting Toggle

### ISSUE THREAD

**Issue by hl2guide** [meganz/MEGAsync#319]
Please consider adding a setting for enabling/disabling the "Upload to MEGA" context menu item for Windows Explorer files.

![context-menu](https://user-images.githubusercontent.com/17044982/60221773-4af09600-98be-11e9-9ee8-ca41be0d8922.png)

**Comment by MatLcq** [comment]
Hello, 
This has been marked as completed, so I guess there's a setting to toggle the context menu integration.
But I can't find it. 
Can somebody help?
Thanks
