### ISSUE TITLE
Too many open files, Glib-Error

### ISSUE THREAD

**Issue by feliarana** [meganz/MEGAsync#32]
Hi! Currently trying to sync my pc with Linux Mint 17.3 64bits with Mate Desktop
Everytime I restart the computer, the MEGA session account must be loged in again. When I do it, the megasync icon turns gray, like if there is no internet (internet is working fine). I tried to open the settings option and the app crashes.

I traced the error:

---

GLib-ERROR **: Creating pipes for GWakeup: Too many open files

Trace/breakpoint trap

---

Any ideas?

**Comment by polmr** [comment]
Hi feliarana. 
The ammount of files opened by megasync should be limited to a feasible number.
Please write to support@mega.nz explaining your issue and attach a log. In order to obtain it, kill all instances of megasync and execute it again with:
`megasync --debug > ~/megasync.log`

**Comment by feliarana** [comment]
I have just send the email with the debug file. Thanks!
