### ISSUE TITLE
Folder sync is not enabled by default

### ISSUE THREAD

**Issue by ZdenoPavlik** [meganz/MEGAsync#322]
When I install megasync and clone folder data are downloaded from cloud.
Unfortunately, automatic synchronization is disabled by default, thus no further  synchronization is done.

https://codeyarns.com/2016/02/13/megasync-client-not-syncing/

**Comment by polmr** [comment]
2016, MEGAsync 2.6.1? Please, ensure you are running the latest MEGAsync for your OS (For Ubuntu, that should be 4.1.1). Get it from https://mega.nz/sync
When you configure a synchronization it should be enabled. However, bear in mind that MEGAsync will disable synchronization with folders that are not accessible (e.g: you set a synchronization with a pendrive, and by the time MEGAsync starts, the pendrive is not mounted).

**Comment by ZdenoPavlik** [comment]
Lost connection to synced folder could be the problem, folder is on external harddrive.
Thanks for hint, I will check that properly! So far this issue is solved by this.

Thank you!

**Comment by mkuhring** [comment]
I'm having the same issue with network drives. Immo it would be better or at least more convenient, if syncs reactivate automatically when the synced folder becomes available again. Maybe optionally per sync? It happened to me a few times now but I only noticed several days later. So it is not syncing for a while, although the network folder is available most of the time. Even when I'm notice that files are missing on other computers, it always takes me some time to remember that a deactivated sync might be the problem. At least disabled syncs should be indicated more prominently, e.g. as a warning flag in the popup, and not just be hidden in the options.
