### ISSUE TITLE
Where's the changelog?

### ISSUE THREAD

**Issue by Fish-Git** [meganz/MEGAsync#330]
## Please provide a CHANGELOG with each new release so we can see what we're getting

It is standard good practice to review a product's [changelog](https://en.wikipedia.org/wiki/Changelog) before installing a new version so you can know what to expect (e.g. security issues fixed, behavioral changes, etc).

Many people, like me, are very reluctant to install a new version of something without knowing beforehand what changes were made to the new version.

### A git commit log is _not_ the type of changelog that human beings need.

&nbsp;
Some examples of what I am talking about:
* https://github.com/SDL-Hercules-390/hyperion/releases
* https://www.prestosoft.com/edp_buildhistory.asp#10.0
___

(https://keepachangelog.com/en/1.0.0/)

## What is a changelog?
A changelog is a file which contains a curated, chronologically ordered list of _notable changes_ for each version of a project.

## Why keep a changelog?
To make it easier for users and contributors to see precisely what _notable changes_ have been made between each release (or version) of the project.

## Who needs a changelog?
**People do!** Whether consumers or developers, the end users of software are human beings who care about what's in the software. When the software changes, people want to know why and how.

**Comment by polmr** [comment]
Here's something you can use. It's intended for linux packages, but it applies to non linux versions too. https://github.com/meganz/MEGAsync/blob/master/build/MEGAsync/MEGAsync/megasync.changes

We might want to consider populating https://github.com/meganz/MEGAsync/releases with that info. Thanks for your inputs @Fish-Git !

**Comment by Fish-Git** [comment]
> Here's something you can use. It's intended for linux packages, but it applies to non linux versions too. https://github.com/meganz/MEGAsync/blob/master/build/MEGAsync/MEGAsync/megasync.changes

_**Beautiful!**_

That's _exactly_ what I was looking for!&nbsp;`:)`

> We might want to consider populating https://github.com/meganz/MEGAsync/releases with that info.

As long as it is a _complete_ list of changes for the Release, then _yes please!_ Thanks!&nbsp;`:)`

> Thanks for your inputs @Fish-Git!

You're very welcome, @polmr.&nbsp;`:)`

I very much appreciate your positive attitude towards this issue.

Thanks again.
___
(p.s. On Windows, the system tray icon's tooltip displays the version, but it wouldn't hurt to also provide an "About..." menu item too (or an 'About' tab on the Settings dialog). Purely optional of course. But I thought I'd mention it.)

**Comment by Fish-Git** [comment]
> We might want to consider populating https://github.com/meganz/MEGAsync/releases with that info.

p.s. The GitHub "Release" page _can_ be _**edited**_ you know! (hint! hint!) &nbsp; `;-)`

**Comment by polmr** [comment]
> (p.s. On Windows, the system tray icon's tooltip displays the version, but it wouldn't hurt to also provide an "About..." menu item too (or an 'About' tab on the Settings dialog). Purely optional of course. But I thought I'd mention it.)
Just in case you haven't seen it: you can click on the cogwheel in the main UI and About MEGAsync...

**Comment by Fish-Git** [comment]
> Just in case you haven't seen it: you can click on the cogwheel in the main UI and About MEGAsync...

I'm not seeing that in my version:

![image](https://user-images.githubusercontent.com/1486786/61979603-26fd9e80-afa9-11e9-9d5c-4f59dc56c158.png)

**Comment by halfluke** [comment]
Glad I found this discussion.
I'm a bit worried because I've started using an "update checker" software (Sumo) and it's telling me that version 4.2.0 (and today 4.2.2.0) of Megasync for Desktop (Windows) exist.
In fact, it can be downloaded from some "general purpose / software download" websites, but no trace in the github releases page (last version seems to be 4.1.1.0, for windows), and the official mega page binary is 4.2.0 instead.
I understand that the releases page may need to be updated, but considering that a software like Megasync could be a "target", and considering that can be compiled from source with unpleasant easter eggs, couldn't we have a SHA checksum on the Mega official download page for the binary?

**Comment by Fish-Git** [comment]
> ... but no trace in the github releases page (last version seems to be 4.1.1.0, for windows) ...

**The problem is even worse than that, @halfluke:**

The [GitHub Releases page](https://github.com/meganz/MEGAsync/releases) only contains the _source code_, but not any actual binaries! (e.g. https://github.com/meganz/MEGAsync/releases/tag/v4.1.1.0_Win)

I suspect most people, like myself, expect the GitHub Releases page to contain not only the source, but more importantly the _**binaries!**_ (i.e. either the MEGAsync.exe app itself or else an installer of some kind).

And, as previously mentioned (which is the whole purpose of this GitHub Issue), an itemized list of significant changes too, _**[such as the ones in the changes log](https://github.com/meganz/MEGAsync/blob/master/build/MEGAsync/MEGAsync/megasync.changes)**_ that @polmr mentioned.

I sincerely hope this issue isn't going to be forgotten and brushed aside as a non-priority item!

IMHO it _very much_ should be a _**top-priority**_ item! (since it's so important and so easy to resolve).

As Nike says...
<p align="center">
  <img src="https://user-images.githubusercontent.com/1486786/62249756-01ed9f00-b3a0-11e9-8b22-ebc3823c6e0a.png">
</p>

&nbsp; &nbsp; &nbsp; `;-)`

**Comment by Fish-Git** [comment]
> ... couldn't we have a SHA checksum on the Mega official download page for the binary?

_**Agree 100%!!**_

**Comment by Perkolator** [comment]
> I'm not seeing that in my version:

You need to right-click the systray icon and then you can select "about". BTW. that info window shows a "new in this version" list.

***

So what's up with the whole mess of not having a changelog and client application that always says "No update available at this time" when manually started the update check from the settings window?

The 4.2.2.0 version (at least for Windows) has been out for at least over a week, no changelog anywhere. Client didn't see that update when tried everyday. And now, I just downloaded the installer again and to my surprise it's 4.2.3.0 version!! This is ridiculous.

I just recently started to use MEGA and I have installed version 4.2.0. I'm also one of those people that refuses to update unless there's a changelog.

Unfortunately too many developers don't understand the importance of changelogs (and even proper changelogs!), its functionality is not just to inform the users of the changes, but to let users test the changes!

So, the question stands; where's the changelog?

**Comment by polmr** [comment]
# Here: https://github.com/meganz/MEGAsync/releases

Note: there's a separated release for each OS. Hope that covers your expectations. Let us know if you find any issue there.

**Comment by Perkolator** [comment]
Excellent! Although I noticed that Windows 4.2.0.0 version is not there..

And it would be a good practice to add a link to the changelog on the https://mega.nz/sync download page. Right under all the platform download buttons (there's two places, on top and bottom of the page) would be fantastic.

THANKS!

**Comment by Perkolator** [comment]
Hmm, on closer inspection, the changelogs for 4.2.2.0 and 4.2.3.0 are identical. I don't think that that is the actual case though. Bit of a rough start for this changelog. I wonder what the differences are actually. Please don't go the "google way" (just "enchancements and bug fixes" listed on pretty much all app versions).

**Comment by Perkolator** [comment]
I wouldn't be so happy right now. 

All of these share the same changelogs:
- 4.2.2.0 and 4.2.3.0
- 4.1.0.0 and 4.1.1.0
- 4.0.1.0 and 4.0.2.0, both have 6 same items, plus 2 new on 4.0.2.0
- 4.0.0.0 and 4.0.1.0
- 3.7.0.0 and 3.7.1.0
- 3.5.3.0 and 3.5.3.3
- 3.4.0.0 and 3.5.0.0
- 3.1.0.0 and 3.1.2.0
- and then I grew tired of comparing...

This is not a good changelog, not at all!

**Comment by polmr** [comment]
Notice, some changelog are similar because the differences between one an another were not considered worth an item in the changelog (those should be understandable and meaningful for most users) but updating the version was. For a finer grain diff between version, you can always  benefit from MEGAsync being an open source github hosted project and see it for yourself: https://github.com/meganz/desktop/compare/v4.2.2.0_Win...v4.2.3.0_Win . Hope that covers your requirements

**Comment by Perkolator** [comment]
It's not about my requirements, it's yet another developer that doesn't understand how/why proper changelogs should be constructed. Having same changelog for different versions is not proper changelog publishing. It creates confusion, doubt, and for example it's harder to test and report issues for a certain version.

**Comment by Perkolator** [comment]
Every version should have its own changelog, however small the changes are.

**Comment by Fish-Git** [comment]
@Perkolator wrote:
> I wouldn't be so happy right now.
> 
> All of these share the same changelogs:
> 
> * 4.2.2.0 and 4.2.3.0
> ...
> * 3.4.0.0 and 3.5.0.0
> * 3.1.0.0 and 3.1.2.0
> * and then I grew tired of comparing...
> 
> This is not a good changelog, not at all!

Wow. I hadn't noticed that.

I agree completely (100%), Perkolator. &nbsp; This does not bode well.&nbsp;`:(`

@polmr wrote:
> some changelog are similar because the differences between one and another were not considered worth an item in the changelog ... but updating the version was.

If the change was significant enough that a new version was released, then the changes should be mentioned in the changelog. That's just common sense.

Perkolator wrote:
> Every version should have its own changelog, however small the changes are.

Again, I have to agree 100%.

I can only hope that this poor first attempt at providing a changelog improves _significantly_ in future releases.

I do however applaud polmr's attempt to address the problem. We do appreciate you trying. We just feel that you can do better.

FWIW it does get easier as time goes by and you slowly get into the practice of always providing one.

**Comment by Perkolator** [comment]
> I do however applaud polmr's attempt to address the problem. We do appreciate you trying. We just feel that you can do better.

Yes, absolutely 100% same sentiments here. Million thanks for polmr already.. little more and it will be good.
