### ISSUE TITLE
Debian/Ubuntu repository signing keys have expired

### ISSUE THREAD

**Issue by RogueScholar** [meganz/MEGAsync#334]
```bash
W: An error occurred during the signature verification. The repository is not updated and the 
previous index files will be used. GPG error: https://mega.nz/linux/MEGAsync/xUbuntu_19.04 ./ 
InRelease: The following signatures were invalid: EXPKEYSIG 4B4E7A9523ACD201 
MegaLimited <support@mega.co.nz>
```

Any idea on when a new signing key will be implemented and exactly where the public key will propagate from?

**Comment by sahsanu** [comment]
Seems they replaced the expired key, after adding the new key it is working fine again (at least using KDE Neon (Ubuntu 18.04)).

`wget -O - https://mega.nz/linux/MEGAsync/xUbuntu_18.04/Release.key | sudo apt-key add -`

**Comment by Justsar** [comment]
In my case with Ubuntu 16.04 fine worked, thanks! But need to change the version of the distribution in the link.

**Comment by repsorp** [comment]
@sahsanu perfect :+1:

Works fine with Ubuntu 19.04:

 wget -O - https://mega.nz/linux/MEGAsync/xUbuntu_19.04/Release.key | sudo apt-key add - 

Thanks

**Comment by Salzy** [comment]
The key for Debian 10 is still expired
https://mega.nz/linux/MEGAsync/Debian_10.0/Release.key

>pub   rsa2048 2014-07-31 [SC] [expired: 2019-07-30]      BF8B66E01192CBA2E72201294B4E7A9523ACD201
uid           MegaLimited <support@mega.co.nz>
sub   rsa2048 2014-07-31 [E] [expired: 2019-07-30]
sub   dsa1024 2014-07-31 [S] [expired: 2019-07-30]
sub   elg2048 2014-07-31 [E] [expired: 2019-07-30]
sub   elg1024 2014-07-31 [E] [expired: 2019-07-30]
>

**Comment by cuissi** [comment]
> The key for Debian 10 is still expired
> https://mega.nz/linux/MEGAsync/Debian_10.0/Release.key
> 
> > pub   rsa2048 2014-07-31 [SC] [expired: 2019-07-30]      BF8B66E01192CBA2E72201294B4E7A9523ACD201
> > uid           MegaLimited [support@mega.co.nz](mailto:support@mega.co.nz)
> > sub   rsa2048 2014-07-31 [E] [expired: 2019-07-30]
> > sub   dsa1024 2014-07-31 [S] [expired: 2019-07-30]
> > sub   elg2048 2014-07-31 [E] [expired: 2019-07-30]
> > sub   elg1024 2014-07-31 [E] [expired: 2019-07-30]

Same here, but while searching I noticed a Mega e-mail sent asking Debian users to download and reinstall the .deb package in order to update keys!

**Comment by curvatura99** [comment]
I would add to delete the old key once the new key is installed.

**Comment by Dvlnst** [comment]
I removed the expired key, download and reinstall debian 10 package but the error persists.

**Comment by curvatura99** [comment]
@Dvlnst

I would install the new key based on the posts from 
sahsanu and repsorp above.

**Comment by polmr** [comment]
The signing key for Debian based repositories expired. We have updated all them except for Debian 10 and Raspbian 9.0. Will do shortly. Thanks for you patience. Once done, reinstalling from https://mega.nz/sync will fix that error. More info: https://mega.nz/blog_55

**Comment by polmr** [comment]
Packages for Debian 10 already available. Reinstalling will fix the issue.

**Comment by Dvlnst** [comment]
Working now, thanks @polmr

**Comment by caumons** [comment]
This issue still happens with Ubuntu 14.04 and blocks system updates. I have to remove the `/etc/apt/sources.list.d/megasync.list` in order to successfully run an `apt-get update` or else it keeps giving a GPG error. I've even re-installed the client with no luck.

**Comment by polmr** [comment]
Ubuntu 14.04 won't receive updates. Removing `/etc/apt/sources.list.d/megasync.list` is ok in this case. We'd recommend you to update your system.

**Comment by caumons** [comment]
OK @polmr, thank you for your response. Unfortunately, there are other software dependencies to be resolved before updating the system to a newer Ubuntu version (it's a development machine). So, for the moment, I'll just remove the `/etc/apt/sources.list.d/megasync.list`.

**Comment by estebandelaf** [comment]
Ok in Debian 10

`wget -O - https://mega.nz/linux/MEGAsync/Debian_10.0/Release.key | sudo apt-key add -`

Thanks.

**Comment by nutpantz** [comment]
The repository 'https://mega.nz/linux/MEGAsync/xUbuntu_20.04 ./ InRelease' is not signed.
: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by caraka** [comment]
GPG error: https://mega.nz/linux/MEGAsync/xUbuntu_20.04 ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 03C3AD3A7F068E5D

Can we get a key uploaded/updated, please?

**Comment by sahsanu** [comment]
@caraka did you add the key?

`wget -O - https://mega.nz/linux/MEGAsync/xUbuntu_20.04/Release.key | sudo apt-key add -`

**Comment by caraka** [comment]
I did indeed, and the release file is not signed, same as nutpantz above.

**Comment by rursache** [comment]
for people looking to install megacmd on a raspberry pi, just run `wget -O - https://mega.nz/linux/repo/Raspbian_11/Release.key | sudo apt-key add -` and then `sudo apt update && sudo apt install megacmd -y`

**Comment by kyletay321** [comment]
Struggling to install on my old Chromebook running Debian 11 - thinking it may be a key issue? Error: E: Unsupported file /path/to/downloaded/package.deb given on commandline
