### ISSUE TITLE
Cloud folder size larger than local size

### ISSUE THREAD

**Issue by Unknow0059** [meganz/MEGAsync#336]
As the title states, the size of a folder in the cloud drive is larger than the size of the folder on my computer.

![Screenshot_1](https://user-images.githubusercontent.com/25656892/62672459-30a3e080-b971-11e9-8ebb-06256c8da289.png)

Not sure what else I could provide that'd be helpful.

**Comment by Unknow0059** [comment]
When I go inside the folder, select all items, and click Info, it tells me the folder's only 27.51 GB.
![download](https://user-images.githubusercontent.com/25656892/62832356-0a956f00-bc03-11e9-8391-79497419a011.png)
Yet the Total Size is 40.32 GB. There's nothing on the Rubbish Bin, either.

**Comment by Perkolator** [comment]
If you look at the first screenshot, it says "Current Versions: 27.51 GB", which is identical to your second screenshot "Total size". Why? In the second screenshot you have selected only all the newest versions of all items. In the first screenshot, add the "Previous versions: 12.81 GB" to your "Current Versions: 27.51 GB" and you get the "Total size: 40.32 GB".

So, in short, you have versioning enabled and older versions (12.81 GB) of your items take space from MEGA.

**Comment by Unknow0059** [comment]
I see. I didn't notice that versioning was a thing. Thanks.
