### ISSUE TITLE
Download List Error (Windows)

### ISSUE THREAD

**Issue by RS55** [meganz/MEGAsync#337]
I am a Windows 10 user, I previously had 1709 and decided to do a clean installation of 1903. I had MegaSync 4.1.1 installed before, when updating the windows I went to version 4.2.3 and it turns out that when adding certain links and close the application, these do not appear again, when you put the link back in the application the files appear to me as if they were never gone besides continuing with the download.

What happens? Is it an application error, a configuration or something? The second I doubt it because I try to download something from my own folder in mega and that does keep it in the download list

**Comment by AnaIsabelTorres** [comment]
Hello.
I have the same issue. The links disappear when I close the application and when I add them again continues using the file I was downloading.

**Comment by AngelPhenix** [comment]
Yep, exact same situation as @AnaIsabelTorres here. The only way to get the download back is to put it in the queue again.

**Comment by karimsaieh** [comment]
i got the exact same problem with Windows 1903 and Mega 4.23

**Comment by vtmateos** [comment]
Apologies for the inconveniences and thanks for pointing that out. The bug has been confirmed and will be fixed in next MEGAsync version. Please, stay tuned.

Thanks.
