### ISSUE TITLE
hello megasync master dont compile anymore.

### ISSUE THREAD

**Issue by javashin** [meganz/MEGAsync#339]
https://gist.github.com/javashin/6a4967f11c8d08be191de11aa01461f1

 emerge --info
Portage 2.3.71 (python 3.6.9-final-0, default/linux/amd64/17.1/desktop/gnome/systemd, gcc-9.2.0, glibc-2.30, 5.2.8-jsX x86_64)
=================================================================
System uname: Linux-5.2.8-jsX-x86_64-Intel-R-_Core-TM-_i5-4200M_CPU_@_2.50GHz-with-gentoo-2.6
KiB Mem:     8037888 total,   1681424 free
KiB Swap:   11422700 total,  11327212 free
Timestamp of repository gentoo: Wed, 14 Aug 2019 15:30:01 +0000
Head commit of repository gentoo: eeb706909562fbab1e0139f14b0bb8f53880a5a3
Timestamp of repository poly-c: Wed, 14 Aug 2019 06:38:11 +0000
sh bash 5.0_p7
ld GNU ld (Gentoo 2.32 p2) 2.32.0
ccache version 3.7.2 [disabled]
app-shells/bash:          5.0_p7::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.0::gentoo
dev-lang/python:          2.7.16-r102::lto-overlay, 3.6.9-r1::lto-overlay, 3.7.4-r2::lto-overlay
dev-util/ccache:          3.7.2::gentoo
dev-util/cmake:           3.15.2::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r3::gentoo, 1.15.1-r2::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.32-r1::gentoo
sys-devel/gcc:            9.2.0::gentoo
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r5::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.30::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-metamanifest: no
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1

localrepo
    location: /usr/local/portage
    masters: gentoo

4nykey
    location: /var/lib/layman/4nykey
    masters: gentoo
    priority: 50

Gnome-3-32-X
    location: /var/lib/layman/Gnome-3-32-X
    masters: gentoo
    priority: 50

bobwya
    location: /var/lib/layman/bobwya
    masters: gentoo
    priority: 50

deepin
    location: /var/lib/layman/deepin
    masters: gentoo
    priority: 50

flatpak-overlay
    location: /var/lib/layman/flatpak-overlay
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    masters: gentoo
    priority: 50

linxon
    location: /var/lib/layman/linxon
    masters: gentoo
    priority: 50

lto-overlay
    location: /var/lib/layman/lto-overlay
    masters: gentoo mv
    priority: 50

miramir
    location: /var/lib/layman/miramir
    masters: gentoo
    priority: 50

mv
    location: /var/lib/layman/mv
    masters: gentoo
    priority: 50

pg_overlay
    location: /var/lib/layman/pg_overlay
    masters: gentoo
    priority: 50

poly-c
    location: /var/lib/layman/poly-c
    masters: gentoo
    priority: 50

reagentoo
    location: /var/lib/layman/reagentoo
    masters: gentoo
    priority: 50

sattvik
    location: /var/lib/layman/sattvik
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    masters: gentoo
    priority: 50

tlp
    location: /var/lib/layman/tlp
    masters: gentoo
    priority: 50

vampire
    location: /var/lib/layman/vampire
    masters: gentoo
    priority: 50

wayfire-desktop
    location: /var/lib/layman/wayfire-desktop
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=bfd -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/vmware-installer"
CPPFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=bfd -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=bfd -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"
DISTDIR="/var/db/repos/gentoo/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=bfd -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=bfd -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.UTF-8"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
LINGUAS="en"
MAKEOPTS="-j3"
PKGDIR="/var/db/repos/gentoo/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="10bit X a52 aac acl acpi adplug alsa amd64 animation-rtl apng applet archive berkdb bluetooth branding bs2b btrfs bzip2 cairo caja calf cdda cdr cleartype_hinting cli colord crypt cue curl custom-cflags custom-optimization cxx dav1d dbus device-mapper dga dri dri3 drm dts dvd dvdr eds egl emboss encode evo exif f2fs fam fat fbcon fdk ffmpeg ffmpeg-codecs flac fontconfig fortran fuse gbm gdbm gif git glamor gles gles1 gles2 gnome gnome-keyring gnome-online-accounts gnuefi gpm gstreamer gtk gtk3 hddtemp hfs http http2 iconv icu image-converter infinality introspection ipv6 ithreads jbig jfs jpeg jpeg2k jumbo-build kms ladspa lame lash lcms ldap libass libcaca libcanberra libdrm libkms libnotify libsamplerate libsecret libtirpc lm_sensors lto lua lvm lz4 lzma lzo mad magic mda-lv2 mdadm mng mod modern-top modplug mp3 mp4 mpeg mtp multilib native-cflags native-headset nautilus ncurses network networkmanager nls nptl nsplugin ntfs ofono-headset ogg openal opengl openh264 openmp opus pam pango pcre pdf pgo plugin-checksum plugin-fishlim plugin-sysinfo plymouth png policykit portaudio postproc ppds pulseaudio python rar raw readline reiser4 reiserfs resolvconf rubberband sdl sdl2 seccomp sensord sensors smpeg sndfile sound spell split-usr ssl startup-notification svg systemd systray tcpd theora threads tiff tracker truetype udev udf udisks unicode upower usb uxa vaapi vdpau vorbis vpx vulkan wavpack wayland webp wifi wxwidgets x264 x265 xattr xcb xfs xinerama xml xmp xpm xpresent xv xvid xvmc zlib zstd" ABI_X86="64 32" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" CURL_SSL="nss" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput" KERNEL="linux" L10N="en en-US" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" NETBEANS_MODULES="apisupport cnd groovy gsf harness ide identity j2ee java mobility nb php profiler soa visualweb webcommon websvccommon xml" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-2" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_7" PYTHON_TARGETS="python2_7 python3_6 python3_7" QEMU_SOFTMMU_TARGETS="*" QEMU_USER_TARGETS="*" RUBY_TARGETS="ruby26" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

**Comment by javashin** [comment]
compiled before with no problems

et-misc/megasync-9999::4nykey was built with the following:
USE="nautilus -dolphin -thunar" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"

**Comment by polmr** [comment]
Please, in order for anyone to help you, you might want to include the steps you used to compile, and post the errors you were given. Thanks for your understanding...
