### ISSUE TITLE
desktop client on macOS catalina beta does not detect file changes and downloads duplicate files from cloud

### ISSUE THREAD

**Issue by alectprasad** [meganz/MEGAsync#342]
Steps to reproduce
1. batch rename files in a folder
2. client does not detect changes
3. restart client to force sync

result
client randomly downloads duplicate files

**Comment by vtmateos** [comment]
Hi @alectprasad !!

Apologies for the inconveniences. Thanks for reporting the issue. It seems that there might be some issues with filesystem notifications within MEGAsync and new macOS Catalina changes regarding partitions, separating system data from user data.

We're working on fixing these issues. Please, contact our support team at support@mega.co.nz so we can keep track of your issues and provide you the best solution.

Thanks.

**Comment by vtmateos** [comment]
Hi @alectprasad ,

We've release a new MEGAsync version available through our website which contains some fixes and improvements for MEGAsync on macOS Catalina. Please, give it a try. It will be publicly released via autoupdate during the following days.

Kind regards.
