### ISSUE TITLE
megasync 4.2.5 linux build failed

### ISSUE THREAD

**Issue by Vascom** [meganz/MEGAsync#351]
```
BUILDSTDERR: control/Preferences.cpp:1034:60: error: 'STORAGE_STATE_UNKNOWN' is not a member of 'mega::MegaApi'
BUILDSTDERR:  1034 |     int value = settings->value(storageStateQKey, MegaApi::STORAGE_STATE_UNKNOWN).toInt();
BUILDSTDERR:       |                                                            ^~~~~~~~~~~~~~~~~~~~~
```
As I see this was added in commit https://github.com/meganz/MEGAsync/commit/14f6ac99ae6216fe5cf30f1e6f61bce1e570a30f

I use sdk 3.6.2a.

How to solve problem?

**Comment by polmr** [comment]
You'd rather use the correct `sdk` submodule (i.e `fcd2f0e`): You can see it at https://github.com/meganz/MEGAsync/tree/v4.2.5.0_Win/src/MEGASync. You can have git do it for you with:
```
git submodule update
```
In any case, that commit correspond to 3.6.2b (the `tag` and release notes are currently missing but will be added shortly, apologies for the inconvenience).

**Comment by Vascom** [comment]
Thanks.
3.6.2b works.
