### ISSUE TITLE
Centos7 Fresh install failed

### ISSUE THREAD

**Issue by Tumurtogtokh** [meganz/MEGAsync#352]
Hi, 

Installing MegaSync on a fresh Centos7 gave me an error: 

Loading mirror speeds from cached hostfile
 * base: centos.serverspace.co.uk
 * centos-sclo-rh: mirror.sov.uk.goscomb.net
 * centos-sclo-sclo: centos.serverspace.co.uk
 * epel: ftp.nluug.nl
 * extras: mirror.bytemark.co.uk
 * updates: mirror.sov.uk.goscomb.net
--> Finished Dependency Resolution
Error: Package: megasync-4.2.4-1.1.x86_64 (/megasync-CentOS_7.x86_64)
           Requires: libraw.so.5()(64bit)

I then tried to install Libraw. Here it is:
sudo yum install LibRaw
Loaded plugins: fastestmirror, langpacks, nvidia
#### NVIDIA ####
Repository cuda is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: centos.serverspace.co.uk
 * centos-sclo-rh: mirror.sov.uk.goscomb.net
 * centos-sclo-sclo: centos.serverspace.co.uk
 * epel: mirror.bytemark.co.uk
 * extras: mirror.bytemark.co.uk
 * updates: mirror.sov.uk.goscomb.net
Package LibRaw-0.19.2-1.el7.x86_64 already installed and latest version

What should I do to install megasync?

Many thanks,

Tumurtogtokh

**Comment by Vascom** [comment]
LibRaw-0.19.2-1.el7.x86_64 contain libraw.so.19 you need to rebuild megasync.

**Comment by Vascom** [comment]
I will add megasync to rpmfusion repo soon.
Now you can test scratch build if you want.

**Comment by subhammridha** [comment]
It seems that the megasync RHEL package works in CentOS 7.7. Also, the RHEL package somehow does not requires any version of libraw as a dependency.

**Comment by polmr** [comment]
RHEL package links libraw statically. We will post a new version for CentOS 7 that solves this, asap. Apologies for the inconveniences.

**Comment by Tumurtogtokh** [comment]
Thank you for your replies. A while ago, I have installed and used MegaSync on Centos7 on a different computer. But that machine did not have NVidia card. If that helps you. 

I like using Megasync. I hope I will use it soon with new version.

**Comment by subhammridha** [comment]
It seems megasync installer for CentOS has been updated to use the new version of libraw. Thanks a lot.

**Comment by polmr** [comment]
Issue solved. Thank all for reporting that.

**Comment by Vascom** [comment]
Now you can try megasync from rpmfusion repo.
At that moment package pushed to nonfree updates testing repo.
