### ISSUE TITLE
Tray icon not shown in GNOME Shell 3.34

### ISSUE THREAD

**Issue by articlecat** [meganz/MEGAsync#353]
MEGAsync doesn't show a tray icon in GNOME Shell 3.34. The application opens as a window, and there is no way to close the window without exiting MEGAsync, which stops synchronization entirely.

This problem exists even though the [KStatusNotifierItem/AppIndicator Support](https://github.com/ubuntu/gnome-shell-extension-appindicator) extension was installed.

**Comment by articlecat** [comment]
The tray icon works properly again. Unfortunately, I am unable to pin down which update resolved the issue.

**Comment by articlecat** [comment]
No longer showing again. Not sure what happened.

**Comment by articlecat** [comment]
Resolved in GNOME Shell 3.34.1.

**Comment by Barraguesh** [comment]
Happens to me in Fedora 33 since a year or so, reported it on #522
