### ISSUE TITLE
Performance Bug: Login takes minutes.

### ISSUE THREAD

**Issue by LSmyrnaios** [meganz/MEGAsync#358]
Hi, login takes 3 to 5 minutes on Windows 10.
MEGAsync version: 4.2.5

Can you speed it up?
Thanks

**Comment by user8446** [comment]
On my machine it logs-in in seconds

**Comment by LSmyrnaios** [comment]
After updating manually (as the in-app update doesn't work) from v.4.3.1 to v.4.3.3, the problem was solved.
