### ISSUE TITLE
[Inquiry] Emblems in Thunar on Ubuntu

### ISSUE THREAD

**Issue by WammKD** [meganz/MEGAsync#364]
I may just be missing something (in which case, sorry for the noise clutter) but I'm running Ubuntu 18.04 and installed a fairly vanilla Thunar (the plugins `thunar-archive-plugin` and `thunar-volman` were also installed).

I downloaded the MEGAsync client from https://mega.nz/sync and that's worked just fine.

I also installed the Thunar plugin from the same link; it's added options to upload folders to MEGA and view the MEGA files in the browser to context menus but doesn't provide emblems to the files in the MEGA folder to indicate their state.

It's been a while since I installed it but, back when I used Nemo, the extension had emblems that could tell you the state of files in terms of download/upload/etc.

Is that also true for Thunar? If so, am I missing anything, possibly? Let me know if there's anything that would make uncovering this easier and I'm happy to provide; thanks!

**Comment by polmr** [comment]
emblems are not supported for Thunar I am afraid, due to some technical reasons.

**Comment by WammKD** [comment]
Drat;that was my worry…

Are the technical reasons limitations of Thunar (mostly just curious, at this point)?

Since that question won't likely affect the original question, I'm gonna close this ticket, just so you guys don't have it dangling around for long and cluttering up your other open issues. Thanks a ton for the quick response, @polmr!

**Comment by polmr** [comment]
You welcome! To satisfy your curiosity, this ticket summarizes it: https://mail.xfce.org/pipermail/thunar-dev/2017-April/005027.html
