### ISSUE TITLE
MEGASync client support for HiDPI monitors

### ISSUE THREAD

**Issue by ffhaddad** [meganz/MEGAsync#37]
In Linux (Gnome 3.20 in my case), the MEGASync client does not scale on HIDPI displays causing everything to appear really tiny.

**Comment by polmr** [comment]
Hi @ffhaddad, we have just released a version (2.9.10) which supports HIDPI for distrubutions supporting qt>=5.6

**Comment by ffhaddad** [comment]
Wow, that was quick! I'll install it this weekend and provide an update. You rock!

**Comment by lubo08** [comment]
Not work for me in Linux Mint 18.1

**Comment by polmr** [comment]
> ...supports HIDPI for distrubutions supporting qt>=5.6
Linux Mint 18.1 features 5.5
