### ISSUE TITLE
Where does MEGAsync store my credentials? 

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAsync#400]
On my Windows office PC I don't have admim rights, however I was able to unpack the MEGAsync installer and run it without any issue. Shortly after  I also  found there is a specific [procedure](https://mega.nz/help/client/megasync/general/can-i-change-the-install-location-of-megasync-or-run-it-from-portable-media-576c8036886688e7028b4581):

> on Windows you can install it on your PC and then copy the generated folder (%localappdata%\MEGAsync) to a USB stick and run from it, or copy to another location on your PC you have access to.

Now I wonder if MEGAsync hashes the user credentials together with device information?    
Put it another way: if someone copies   `%localappdata%\MEGAsync` or an equivalent folder to another computer, will they be able to access my MEGA files  without being asked for email/password or will MEGAsync detect it has been started from a different device?

Of course I could do some self-experiments, but I'd rather have your technical point of view.

**Comment by mattw-mega** [comment]
%localappdata%\MEGAsync is just the program installation, it does not include any account data.   Your account data (a local copy of the node tree, plus your transfers in progress etc) is stored at %localappdata%\Mega Limited\MEGAsync.    That account data is encrypted though, using https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata  so you (or anyone else) first needs to be logged into windows under your windows user account before they could use those files, and resume your MEGAsync session.    Note that you can also terminate the session via webclient, and then it can't be resumed regardless.

**Comment by steve4444** [comment]
Thanks
