### ISSUE TITLE
MEGASync Not Auto-Updating To v4.3.0

### ISSUE THREAD

**Issue by sanjaylord** [meganz/MEGAsync#407]
Hello there, I just heard from a friend that v4.3.0 of the MEGASync desktop app is now available to download from your site but when I try to auto-update the older version of the app (v4.2.5) which I have installed on my PC from App Settings, it says "No update available at this time" even though clearly there is a new version available. It doesn't even send a request to the server for the new version. Please do look into this issue as it might be affecting your users world-wide.

**Comment by jDally987** [comment]
Same here. I use the chocolatey package; but didn't even know there was an update from 2 weeks ago till I randomly stumbled upon the github releases

**Comment by sanjaylord** [comment]
> Same here. I use the chocolatey package; but didn't even know there was an update from 2 weeks ago till I randomly stumbled upon the github releases

Got a response from MEGA support. Seems they push the update in batches to ensure the release is bug-free otherwise it might affect the entire user base at once and they wish to avoid that. Should be rolled out within a few weeks otherwise you can manually install it from their website.

Screenshot: https://i.postimg.cc/B6t5XJMR/screenshot-173.png
