### ISSUE TITLE
megasync behaviour in Linux when no systray available

### ISSUE THREAD

**Issue by sedimentation-fault** [meganz/MEGAsync#41]
When someone uses _megasync_ in Linux, in a window manager without any standard systray application (say, _fvwm2_), then one starts _megasync_ from the command line of an _xterm_, _megasync_ starts and...nothing.

The user who uses it for the first time (we are _all_ first-time users at some point in a software's life-cycle!) is left in the dark: _megasync_ seems to be running OK, even the debug output indicates that it _is_ doing something and probably what it is doing is its job - but there is _no icon, no feedback_. Is it logging in? Is it synchronizing? Is it reading/writing? Is all OK? Did I miss anything during compilation/installation?

I had to search for _days_, under the almost certain impression that _megasync_ is NOT functioning correctly, until I found some blog that displayed, step-by-step AND with _screenshots_, how installation of _megasync_ looks like in a GNOME/KDE environment - an environment that comes with a systray application by its very definition. The screenshot '_megasync_ docs into your systray' was a revelation to me! There was no sign at all for me that _megasync_ does such a thing by default - up to that point!

You should do something about this use case - I cannot imagine that it is too odd. There _are_ people in the Linux world who dislike systrays, but would like to use a syncing application like _megasync_. **In case there is no systray running, _megasync_ should at least issue a warning to the user, so he knows what is going on and what is needed.** 

FYI, as soon as I installed [stalonetray](http://stalonetray.sourceforge.net/), all is well. _stalonetray_ (a systray application, but not the only one around...) displays the _megasync_ icon and the icon informs me about what is going on. All fine! :-)

**To the _FVWM_ users out there reading this, here is how you can incorporate _stalonetray_ to your window manager:**

Add the lines:

```

#-----------------------------------------------------------------------
# Starts a system tray "module"
#-----------------------------------------------------------------------
#
DestroyFunc FuncStartSysTray
AddToFunc FuncStartSysTray
+ "I" Test (x stalonetray) PipeRead `echo Exec exec stalonetray \
-d all \
--grow-gravity SE \
--kludges fix_window_pos,force_icons_size,use_icons_hints \
--background="grey67"`
+ "I" TestRc (Match) Wait stalonetray


#-----------------------------------------------------------------------
# Starts system tray applets like network, sound, etc
#-----------------------------------------------------------------------
DestroyFunc FuncStartSystrayApplets
AddToFunc FuncStartSystrayApplets
+ "I" PipeRead 'echo SetEnv systray_started `ps -e |grep -c stalonetray`'
+ "I" Test (EnvMatch systray_started 0 ) break
# volume
+ "I" Test (x volumeicon) exec exec volumeicon
# battery
+ "I" Test (x fdpowermon) exec exec fdpowermon
# network
+ "I" Test (x nm-applet) exec exec nm-applet
# bluetooth
+ "I" Test (x bluetooth-applet) exec exec bluetooth-applet

#-----------------------------------------------------------------------
# stalonetray
#-----------------------------------------------------------------------
Style stalonetray !Title
Style stalonetray HandleWidth 2
Style stalonetray EWMHUseStackingOrderHints
Style stalonetray Sticky
Style stalonetray WindowListSkip
Style stalonetray StaysOnBottom
```

to your ~/.fvwm2rc file. Then add the lines

```
+   "I" Test (Init) FuncStartSysTray
 +  "I"     Test (Init) FuncStartSystrayApplets
```

to your _InitFunction_, i.e. somewhere under the line:

`AddToFunc InitFunction`

To let _FvwmButtons_ (in case you use it) swallow _stalonetray_, add something like:

*FvwmButtonsRows        3
# The '1x3' makes stalonetray occupy 1 column and 3 rows in FvwmButtons,
# resulting in a nice vertical tooltray.

*FvwmButtons (1x3, Swallow(NoClose, UseOld, SwallowNew) "stalonetray" 'Test (x stalonetray) FuncStartSysTray'

to _~/.fvwm2rc_.

You also need a configuration file for _stalonetray_. This is _~/.stalonetrayrc_. My _~/.stalonetray_ file contains:

```
transparent true
window_layer bottom
grow_gravity NW
icon_gravity NW
scrollbars vertical
no_shrink true
tint_level 0
tint_color white
log_level info
parent_bg false
icon_size 18
sticky true
window_layer normal
window_strut auto
window_type normal
geometry 4x12
skip_taskbar false
```

but YMMV.

**PS.** You might want to add the above to your FAQ.

**Comment by polmr** [comment]
Megasync is designed to give the same user experience in all the different supported systems: Windows, Mac, and the different Linux flavours. The ecosystem in the latter is as huge as it gets. Covering all cases is not something bearable nor intended. That's why, at the moment, we are "stuck" with the systray. The same goes for the FAQ. However, we do really appreciate the inputs and your words for the FVWM community. I think it's great to have them here as reference for those who want to install a systray for using megasync.

**Comment by sedimentation-fault** [comment]
I understand. No problem.

I am not trying to get you out of the "systray thing". But please put some message after _megasync_ starts, along the lines of:

> "Searching for a system tray to dock the megasync icon...
> No systray found. _megasync_ is running fine without one,
> but you will not be able to monitor what it does through its icon.
> If you find this behavior difficult to follow, you might want 
> to install a systray application and make sure it is running,
> before you start _megasync_."

I mean, _megasync_ tries to dock into a systray anyway. In doing so, it either succeeds, or fails. My point is that you should output a message like the above, when it fails - instead of failing to dock silently.

**Comment by polmr** [comment]
Two comments on this: following @sedimentation-fault comments, a message on startup in systems without systray has been added. Also, in megasync >= 2.9.10,  re-executing megasync will show the main interface. This way, we keep the systray behaviour and support environments without systray.
