### ISSUE TITLE
Not logging/syncing with VPN on (network manager)

### ISSUE THREAD

**Issue by Barraguesh** [meganz/MEGAsync#411]
Yesterday, after the update (normally I use it with my VPN without problems) I realized nothing was syncing. After lot of tries and debugging in the VPN DNS (I thought it may be blocking MEGA) I realized that if the VPN was on, MEGA didn't connect, if it was logged it, it couldn't upload or sync and if it was just opened, it was stuck on logging in.
Using Fedora 31. Working before this last update, no change on config.

**Comment by mattw-mega** [comment]
If you could supply some logs so we can look into this, that would be great.  Either via the 'Upload bug report' in the Settings dialog, or if you have some expertise, have a look in your logs folder in the MEGAsync folder, and send us a small relevant portion of MEGAsync.log where the networking is failing. thanks

**Comment by Barraguesh** [comment]
So I did a `sudo dnf upgrade --refresh` and now it works like it did before. Did you push any update or it was an update in another Fedora module? Anyway, seems fixed now, thanks for the help, congrats on the product!

**Comment by eschewary** [comment]
> If you could supply some logs so we can look into this, that would be great. Either via the 'Upload bug report' in the Settings dialog, or if you have some expertise, have a look in your logs folder in the MEGAsync folder, and send us a small relevant portion of MEGAsync.log where the networking is failing. thanks

I'm experiencing the same issue as OP but I'm running Windows 10. Is there a way I can get the logs or perform the equivalent of a 'sudo dnf upgrade --refresh'? How can I troubleshoot the VPN connection error? Thank you.
