### ISSUE TITLE
Duplicates for MegaSync Folders in Windows Explorer Navigation Pane

### ISSUE THREAD

**Issue by hl2guide** [meganz/MEGAsync#424]
E.g.

![A](https://user-images.githubusercontent.com/17044982/77685612-cb7c2880-6fef-11ea-92c5-9e7e9162c55a.PNG)

Please consider adding cleanup logic for duplicate items (same paths).

**Comment by Raptor2213** [comment]
Seems to have recurred.
![image](https://github.com/meganz/MEGAsync/assets/707513/03872a66-5d4a-47f7-add3-2273f8e4e1ed)
