### ISSUE TITLE
Why MEGAsyns doesn't support multiple syncs on the same folders ?

### ISSUE THREAD

**Issue by yevhenii8** [meganz/MEGAsync#427]
Supposing I have 10 folders in my MEGA cloud. Three of them are synced from PC, four from Andorid devices, others are synced manually. 
So, I have three folders synced with cloud on my PC.
![image](https://user-images.githubusercontent.com/13679188/78460807-a7de6f80-76cc-11ea-94a3-946614b67208.png)

But additionally, from time to time I would like to have the whole cloud synced with external hard drive. I connect it to my PC and try to add it to MEGAsync.
![image](https://user-images.githubusercontent.com/13679188/78460842-09064300-76cd-11ea-9b96-539663f962b0.png)

I've read manual page & help page. And figured out that it isn't allowed to do this way. Now I have to do this:
1) Remove all previously added folders.
2) Connect hard drive and add it to synced folders.
3) Sync it.
4) Disconnect hard drive.
5) Restore previous folders.

Are there any workarounds / approaches here to easy this ? 

Thank you!

**Comment by steve4444** [comment]
Interesting question. Maybe a title like the error message would be a bit clearer:

Why can't a synced folder be inside another synced folder?
