### ISSUE TITLE
Critical security issue: access on all cloud files, change of password without asking the current one

### ISSUE THREAD

**Issue by LSmyrnaios** [meganz/MEGAsync#446]
Hi, I would like to report a security issue with the Desktop app and suggest a solution.

Potential security issue: 
An attacker accesses **ALL** of your cloud files (even those not synced with your PC!!) and/or changes your password.

Cases:
1. Let' s say you have your PC open, and you have to leave it for a few minutes and leave it unlocked (either you forget, or it's an emergency which leaves you no time for that).
2. A person can open your PC (when he knows your password or you don't have one or it's a shared PC) and you have automatic-login for your MEGAsync app.

Result:
The attacker could just browse though / replace / delete **ALL** of your cloud files by opening them from the app's menu: "three dots --> Cloud Drive"! This can be done even if the user has the "MEGAsync browser extention".
Another critical security issue is that the attacker could also simply change your password, without needing to know your current one, as the app does not asks for that!

Solution:
In order to limit the exposure in the the above security issue, MEGAsync-Desktop could:
1. Have an auto-locker, just like in the Android-app.
The first time the user opens the app, either starts it or just opens it, if the app start automatically on logon), he would have to enter a password.
The user could also choose the app to lock automatically every `a number of` minutes.
While in lock-mode, the app could still apply transfers, or not, depending on user choice, but consider the following:
  a) If file-transfers are allowed during lock-mode, the attacker could replace / delete the cloud-files and get the newly synced ones, without having to gain access on the account.
  b) If the file-transfers are not allowed, the user would have to enter the password each time he wanted to sync his files. Of course, files being transferred when the app locks, should finish transferring or at least pause and not get cancelled mid-way through.
2. Ask for your current password before changing it into a new one.

The Viber's example:
[Viber](https://www.viber.com/en/), the messaging app, made a desktop version a while back, which suffered from, a similar issue.
The attacker could access all of the user's messages synced with that device.
Even worse for them, there was no "logout" choice to limit the security issue a bit, even inconveniently like in MEGAsync (having to enter both email and password each time).
So, they made an auto-locker, like the one I am describing above, which does not interrupt receiving messages during lock-mode, but requires the user to enter a password when opening the app or `number of` minutes have passed without actively using it.

P.S.
Maybe the "Github Issues" is not the best place to report security issues, but you don't have a [Github security policy](https://github.com/meganz/MEGAsync/security/policy).
The issue I describe, is a common one, that any attacker already knows just by using the software himself.. but you should consider creating a policy for future security reports, with guidelines on where the reports should be sent.

Please provide a fix soon.

Thank you

**Comment by LSmyrnaios** [comment]
Hi, is there a plan on when this security issue will be addressed?
It's a shame that this is still unresolved after 6 months, for a product advertised as "secure".

**Comment by warp16** [comment]
I would email them at security@mega.nz, they unfortunately don't seem to check this board often. 

As for the security concerns, I get the impression that many end users get locked out of their accounts after forgetting their passwords and not keeping the recovery key, so MEGA decided to make certain things not as strict as they could be in order to accommodate these users.

**Comment by ortmann** [comment]
After someone with bad intentions had access to your PC in the way you describe (even only for a few minutes), your MEGAsync password is the _least_ of your concerns. End-to-end encryption is only as secure as the weakest endpoint, and a compromised PC is a _very_ weak endpoint indeed.

**Comment by LSmyrnaios** [comment]
@ortmann I have to disagree, as many people these days have a "work-PC" without personal data inside, but with connection to their cloud and vise-versa (a "personal-PC" with connection to their work-cloud for remote work).
So, most often, an attacker would have access only to half of the life of the victim, but with the MEGAsync flaw, he can have access to its whole life....

**Comment by ortmann** [comment]
No matter how you look at it, you _have_ to keep the endpoint secure.

Giving attackers an opportunity to install a backdoor on your endpoint device
is the beginning of the end of the security of everything located on that device 
or being accessed from that device - your proposed password change locker does   
not even begin to mitigate that.
