### ISSUE TITLE
Unable to securely log in

### ISSUE THREAD

**Issue by galexman** [meganz/MEGAsync#449]
I just had this problem appear today with MEGAsync when I opened my PC and the program tried to log in on startup. I got this message on my screen:

> MEGA is unable to connect securely through SSL. You might be on a public Wi-Fi with additional requirements. (Issuer: Let's Encrypt Authority X3)

the message box has three options, one that says "I don't care", "Retry" and "Logout".
This is my main desktop computer which is connected via ethernet so there's no WiFi involved. Is it safe to just press I don't care and connect "not securely" to my account or should I wait? Also it's worth mentioning that I can log in to my account just fine from the website on the browser.
Any help is much appreciated.

**Comment by chrullrich** [comment]
I just had the same happen, and after a few minutes, the warning message disappeared on its own and the client apparently logged in. However, when I close and reopen it, the warning reappears.

**Comment by aConar** [comment]
Same problem here, inspecting the logs I found:
CURLMSG_DONE with error 90: SSL public key does not match pinned public key [net.cpp:1966]
WARN Invalid public key? [net.cpp:1972]
cURL DEBUG:  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway. [net.cpp:1626]

**Comment by chrullrich** [comment]
The certificate that MEGAsync gets was issued by Let's Encrypt about three hours ago (2020-05-30T11:01:11Z). A benign explanation is that MEGAsync pins certificates until a short window before their expiration, and in this case the certificate was renewed early by accident.

**Comment by chrullrich** [comment]
And now the certificate changed to one issued by Comodo, one that MEGAsync seems to like much better than the LE one because it doesn't complain about it. So was the LE a configuration mistake (a dev server that shouldn't have been there)? I have a support request open at MEGA, let's see what they say.

**Comment by chrullrich** [comment]
Response from MEGA:

> Hello,
> 
> We apologize about it, it has been a temporary error.
> 
> Our sysadmins have been working hard to solve it, you should be able to login now. Please reaload your account and tell us if the issue persists.
> 
> Thank you for your patience.
> 
> Kind Regards,
> MEGA Support

**Comment by galexman** [comment]
Hello again,

It seems it was a temporary issue indeed. The client is now working just fine.
Thank you to everyone for helping out in this, and to the people working behind the scenes to fix this.
