### ISSUE TITLE
Incorrect TLS certificate accepted automatically

### ISSUE THREAD

**Issue by chrullrich** [meganz/MEGAsync#450]
When MEGAsync receives a server certificate that does not match its pinned public key, it shows a warning message about this and offers three options: Don't care, Retry, Logout. The default button in this message box is "Retry". If the user does not interact with this message, then after five minutes MEGAsync proceeds as if  "Don't care" had been selected.

This is a security issue because the user might decide to leave the computer before noticing the error message (as can happen if MEGAsync starts automatically at logon and the user has business elsewhere) or be tricked into doing so. When they return the message will be gone and MEGAsync will work as if nothing was wrong.

See #449 about an incident that happened today.

**Comment by mattw-mega** [comment]
I've checked the code and tested it - the default is Retry, and there is no timeout set for the dialog.  I've been waiting 10 minutes now and it it still waiting for input.   You can check the code yourself in MegaApplication.cpp:
```                    sslKeyPinningError->setButtonText(QMessageBox::Yes, trUtf8("I don't care"));
                    sslKeyPinningError->setButtonText(QMessageBox::Cancel, trUtf8("Logout"));
                    sslKeyPinningError->setButtonText(QMessageBox::Retry, trUtf8("Retry"));
                    sslKeyPinningError->setDefaultButton(QMessageBox::Retry);
                    int result = sslKeyPinningError->exec();
```  Most likely, your dialog received a stray click or keyboard input. thanks

**Comment by chrullrich** [comment]
OK, I can't reproduce it this morning (using an SSL interception proxy), so I suppose it wasn't real after all. I'm fairly sure there wasn't stray input yesterday because the second time I was specifically waiting for the message to disappear (which it did). I suspect the explanation is that yesterday, while they were working to fix the wrong certificate, some retry requests from MEGAsync happened to get a good one. Strangely, both times it happened after five minutes (+/- a few seconds at most).

Anyway, thanks for checking, and have a nice day.
