### ISSUE TITLE
Error On Startup:  Application does not start

### ISSUE THREAD

**Issue by jshand2015** [meganz/MEGAsync#476]
I am running on arch linux 64 bit.

the version on megasync I am using is 4.3.3

the error I get is:

megasync: error while loading shared libraries: libraw.so.19: cannot open shared object file: No such file or directory

arch Linux has now updated the libraw package to version 0.20.1-1

**Comment by alfredo-ardito** [comment]
I confirm the same issue about libraw.so.19 missing

**Comment by walle214** [comment]
I confirm this issue too

**Comment by emberquill** [comment]
I was able to get it running for now by installing [libraw19](https://aur.archlinux.org/packages/libraw19), but this is a workaround at best. It should be rebuilt against libraw20.

**Comment by legendary-mich** [comment]
Same issue here. I downgraded the libraw package for now as it is used only by megasync and imagemagick.
```
sudo pacman -U /var/cache/pacman/pkg/libraw-0.19.5-3-x86_64.pkg.tar.zst
```

**Comment by jshand2015** [comment]
is there a way to know which version of libraw that arch Linux is using each time megasync is updated or anytime any of the dependencies are updated, especially libraw.  seems to be the only one for now.  Automatic symlink for example??

**Comment by jshand2015** [comment]
looks like latest update has fixed this issue so far.  load ok

**Comment by vtmateos** [comment]
Yes, apologies for the inconveniences. Please update your MEGAsync package and arch linux distro and it will work. Thanks.

**Comment by jshand2015** [comment]
i am now using OpenSUSE tumbleweed.  the version of libraw is now 0.20.x

can you please adjust megasync to require this new version
