### ISSUE TITLE
MEGAsync on macOS Big Sur 11 Public Beta (20A5343j) stopped syncing

### ISSUE THREAD

**Issue by yasithab** [meganz/MEGAsync#482]
Hello,

If you are using MEGAsync on **macOS Big Sur 11 Public Beta (20A5343j)** and if it stopped syncing, it might occur due to sync paths automatically uncheck.

I contacted MEGA support and they asked me to verify it. It worked! Thank you!

I'm posting this because it could save some time :)

<img width="1704" alt="macOS" src="https://user-images.githubusercontent.com/9078175/89782403-d82e9280-db32-11ea-970c-915e813ea442.png">

**Comment by vtmateos** [comment]
Thanks for taking time to test MEGAsync with latest public beta of Big sur, it is really appreciated. If you notice any issue or misbehaviour, do not hesitate to contact us ;)
