### ISSUE TITLE
Do or Don't Use HTTP

### ISSUE THREAD

**Issue by asheroto** [meganz/MEGAsync#484]
![image](https://user-images.githubusercontent.com/49938263/92297746-015efa80-ef08-11ea-9461-7b573f16f75e.png)

I installed megasync on Windows from scratch, and it had "Don't use HTTP" checked by default.  I found this option and unchecked it.  My download and upload speed significantly improved.  Why would this be checked by default?

client v4.3.3

**Comment by mattw-mega** [comment]
Some proxies and/or ISPs interfere with the http headers when not using https.

**Comment by asheroto** [comment]
Does MegaSync encrypt traffic either way?  My ISP doesn't interfere with anything.  :-D

**Comment by mattw-mega** [comment]
Yes - but we don't know if your ISP will interfere.  If you know it doesn't, you can turn that off and you'll have lower CPU usage due to those requests not having that extra layer of encryption.   The file data being sent/received is encrypted anyway under the file's own key.  cheers

**Comment by asheroto** [comment]
Does "Don't use HTTP" mean it uses HTTPS?

**Comment by mattw-mega** [comment]
Yes

**Comment by asheroto** [comment]
OK, thank you.
