### ISSUE TITLE
MEGAsync re-uploads photos after reconnection to SD card

### ISSUE THREAD

**Issue by pbielefeldt** [meganz/MEGAsync#485]
Hi all!

First, let express my gratitude for providing this great product. Thank you!
However, I have an issue that I already encountered on my Moto G6, and now I see the same behaviour on a Huawei Y6s, so it's maybe a more general issue. I have an SD-Card plugged in, and my camera's default storage location is `/storage/<UID>/DCIM/Camera`. In *MEGAsync*, I activated Camera Uploads, and assigned this folder as 'local camera folder'. As expected, it syncs all pictures to the *Camera Uploads* folder at mega.

Unfortunately, after a re-boot of the phone (and maybe in other cases, too), the SD is no longer recognized by MEGAsync – at least, that is my understanding. This triggers two things: First, MEGAsync stops auto-uploading pictures taken.

More critically: When I re-activate the Camera Upload feature, I have to select the SD card as a local storage again. MEGAsync will crawl the folder again, *and then upload* __all pictures in DCIM/Camera__ *again*, with the suffix `_1.jpg` appended. 

Hence, whenever my phone re-starts, MEGAsync produces about 1GB of totally futile traffic, brings disorder to my photos folder and causes annoying extra work for me. I'd greatly appreciate if the programme could be altered to avoid this behaviour. If you think I can provide any helpful information, please contact me.

Best

P_Bielefeldt

**Comment by vtmateos** [comment]
Hi @pbielefeldt ,

I think you are referring to Android app based on your comments. You should forward your issue to the Android repo at
https://github.com/meganz/android, because this repo is for desktop sync client for macOS, linux and windows.

Regards.
