### ISSUE TITLE
Git-tag releases

### ISSUE THREAD

**Issue by osvein** [meganz/MEGAsync#5]
Tagging new version releases is standard git procedure. Without tags, one would have to browse the commit history and find the commit ID in order to get older versions of the software or reference it from build scripts like PKGBUILDs.

[Git tagging is a simple task](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and [it can even be done directly from GitHub](https://help.github.com/articles/about-releases/), so I don't see why one wouldn't tag releases.

**Comment by javiserrano** [comment]
Thank you for notifying us about the lack of tags, it wasn't on purpose.
I have just pushed to the repo all tags we have and I have added some recent ones that were missing.
