### ISSUE TITLE
Files that begin with an underscore are skipped from syncing  

### ISSUE THREAD

**Issue by sysadmin1337** [meganz/MEGAsync#50]
It's not included in excluded files but still isn't being synchronized. I need to sync these application files that start with an underscore to use them on another pc.

Edit: maybe it was because my application was running.

**Comment by polmr** [comment]
That's weird. MEGAsync does support synching files starting with "_". 
@sysadmin1337, could you please elaborate a bit more? What's on your exclusion list, which OS are you using, which version of megasync are you using (test with the lattes first please), ...

If you want to provide sensible information, please write to support@mega.nz describing your issue with all the information you can gather.
