### ISSUE TITLE
I have in windows 10 MEGAprivate ERROR DUMP

### ISSUE THREAD

**Issue by DainonihRam** [meganz/MEGAsync#502]
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 132b5db355454c4da77c7c94bbe544b8
Version code: 4305.0
Timestamp: 1603466577839
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: e5ef0c9ef432c706ef8f195ac603ed3a
Version code: 4305.0
Timestamp: 1603124167516
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 3c45bdb1808023c77818c2fc7e2659b2
Version code: 4305.0
Timestamp: 1602961149582
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 6d2d3384c306cd18488b7b54e140f3b6
Version code: 4305.0
Timestamp: 1602959316629
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
#1 ----------
#2 ----------
#3 ----------
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 55a9eb975c9004e961b177fccc9f0416
Version code: 4305.0
Timestamp: 1602942686421
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: ee4adeb0f9232785c8205dcacd66568a
Version code: 4305.0
Timestamp: 1602913104264
Module name: MEGAsync.exe
Operating system: Windows 6.1.7600
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
#1 ----------
#2 ----------
#3 ----------
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: c5ca152e998251f88329280f58c3b20e
Version code: 4305.0
Timestamp: 1602879641151
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: f18a963e2413c51ae3a6ab02cda3bfeb
Version code: 4305.0
Timestamp: 1602858775752
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
#1 ----------
#2 ----------
#3 ----------

**Comment by DainonihRam** [comment]
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 93fe0117a760754a066dc8ca4eafa2f0
Version code: 4305.0
Timestamp: 1603554726399
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
#1 ----------
#2 ----------
#3 ----------
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 060ab52b20500f65516c530ff0291753
Version code: 4305.0
Timestamp: 1603466834611
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 132b5db355454c4da77c7c94bbe544b8
Version code: 4305.0
Timestamp: 1603466577839
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: e5ef0c9ef432c706ef8f195ac603ed3a
Version code: 4305.0
Timestamp: 1603124167516
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 3c45bdb1808023c77818c2fc7e2659b2
Version code: 4305.0
Timestamp: 1602961149582
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 6d2d3384c306cd18488b7b54e140f3b6
Version code: 4305.0
Timestamp: 1602959316629
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
#1 ----------
#2 ----------
#3 ----------
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 55a9eb975c9004e961b177fccc9f0416
Version code: 4305.0
Timestamp: 1602942686421
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: ee4adeb0f9232785c8205dcacd66568a
Version code: 4305.0
Timestamp: 1602913104264
Module name: MEGAsync.exe
Operating system: Windows 6.1.7600
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
#1 ----------
#2 ----------
#3 ----------
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: c5ca152e998251f88329280f58c3b20e
Version code: 4305.0
Timestamp: 1602879641151
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: f18a963e2413c51ae3a6ab02cda3bfeb
Version code: 4305.0
Timestamp: 1602858775752
Module name: MEGAsync.exe
Operating system: Windows 10.0.19041
Error info:
Unhandled exception 0xC0000005 at 0x126ACC(MEGAsync.exe)
Stacktrace:
#0 0x126ACC (MEGAsync.exe)
#1 ----------
#2 ----------
#3 ----------

**Comment by vtmateos** [comment]
Hi, Thanks for reporting. Please, may I ask you to contact our support team (support@mega.co.nz) and explain your problem? We already receive the crash reports if you send it to us from MEGAsync. Thanks.
