### ISSUE TITLE
Sync is not working anymore after pc standby (Linux)

### ISSUE THREAD

**Issue by JoshuaDietz** [meganz/MEGAsync#508]
Hello,

I'm using the sync client on Manjaro Linux. It works fine until the laptop was in standby. Then the client is just not syncing changes anymore. To fix it I have to quit the client and start it again.
It would be really nice if this could be fixed since it's pretty annoying to restart the client every time you shut the lit of your laptop especially if you forget that you have to restart the client and it does not sync anymore without any notice.

Thanks in advance

**Comment by pidgeon777** [comment]
Also on Windows it seems that when the PC goes to standby, then MEGAsynch goes to idle too, and it starts scanning and downloading files again only when logging back into windows.

**Comment by JoshuaDietz** [comment]
It looks like the issue is resolved for me after an update to MEGASync 4.3.7. I will take a closer look in the next days but for now it looks good.

**Comment by mattw-mega** [comment]
Hi @pidgeon777 ,  when your PC goes to standby mode (called Sleep now in the windows interface, it seems), everything stops, not just MEGAsync - the computer isn't really on anymore, but it can be woken up quickly and resume apps from where they left off.   You probably want to change your windows "Power & Sleep" settings to just turn off the screen to save power, but leave the PC running (so MEGAsync remains running), and maybe choose a low power setting.  thanks

**Comment by pidgeon777** [comment]
Ok, I will try with that to see what happens and let you know the outcome, but it won't solve the MEGAsync crashing issue.

Or, if you prefer, that could be a nice workaround but I would consume more power just to avoid MEGAsync crashing.

The real question, would be: why those crashes, and how to fix them?

I am available to conduct all the necessary tests to help with your fixing process.

**Comment by JoshuaDietz** [comment]
Okay, I tested it for a while now and the update did not fix the issue for me. But I think I found the solution:
After I raised the number of max_user_watches in linux I did not have the issue anymore as far as I can tell. How to change it is explained  [here](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc) for most linux distributions and [here](https://gist.github.com/tbjgolden/c53ca37f3bc2fab8c930183310918c8c) respecitvely for Arch/Manjaro
