### ISSUE TITLE
Tray icon not detected on startup

### ISSUE THREAD

**Issue by Barraguesh** [meganz/MEGAsync#522]
I'm using Fedora 33 with the GNOME extension AppIndicator and KStatusNotifierItem Support. Before a couple of updates, Mega detected the tray icon at start-up and started minimized, some months ago Mega is starting with the "A tray icon couldn't be find" message and it stays as an open app.

Closing Mega and starting it again makes it go to the tray icon so I suppose it has to do with Mega booting up before the extension does.

**Comment by gnumanx** [comment]
I've experienced the identical behavior on Archlinux with GNOME 3.38.2

**Comment by Barraguesh** [comment]
> I've experienced the identical behavior on Archlinux with GNOME 3.38.2

Has it been fixed for you? Reinstalled Fedora 33 and it still happens. I'm on 3.38.4

**Comment by Barraguesh** [comment]
Since I installed Fedora 34 it doesn't happen anymore. Would like more communication from the MEGA team about fixed issues...
