### ISSUE TITLE
xcopy causes megasync to download instead of upload

### ISSUE THREAD

**Issue by AlexMartin17** [meganz/MEGAsync#532]
Hello. I’ve noticed a strange behaviour today.
I was working on a script in Windows 10 which uses xcopy command through cmd.exe to move files. It was executing successfully but it wasn’t replacing the file and I was 99% sure that xcopy is somehow bugged. Then I’ve noticed that the particular directory which I worked in was included in my Megasync and the app was downloading the previous version of the file instead of uploading the modified. Normally if you copy paste a file it does upload it to mega as new file but apparently using xcopy it does restore the previous. Is that normal?

**Comment by facundoq** [comment]
Maybe you are hitting #70 ? Check that xcopy is setting the date of the files correctly.

**Comment by AlexMartin17** [comment]
> Maybe you are hitting #70 ? Check that xcopy is setting the date of the files correctly.

I turned off megasync and used xcopy again and the modification time was correct

**Comment by mattw-mega** [comment]
Hi @AlexMartin17 , @facundoq  , you may like to know we have a big update coming for MEGAsync which fixes this - uploading or downloading is based on which side of the sync changed, not on mtimes of files. You can read about it and perhaps help test it here: https://github.com/meganz/MEGAsync/issues/770 thanks
