### ISSUE TITLE
Can't type a path in upload selector

### ISSUE THREAD

**Issue by thany** [meganz/MEGAsync#537]
To reproduce:

1. Go to the transfer manager
2. Press the Add button in the top-right corner
3. Select "Upload"
4. Try typing in a full path like D:\Photos like below.

![image](https://user-images.githubusercontent.com/152227/107893494-e28b7800-6f2b-11eb-85ab-546c4f58ac03.png)

As soon as you type in the `:` character, it'll go back to the initial text.

This is annoying, because I might know the path from the top of my head, and typing it in might be a lot faster than navigating to it from here (...to it from this rather useless directory, might I add).

Pasting a full path over the selected text also does nothing. Because instead of remembering it, I might have copied the full path from another program like, say, explorer.

**Comment by vtmateos** [comment]
Thanks for your feedback. This is a custom select dialog that allows to select files and folders at the same time, otherwise, native ones does not let you do that. We will consider your suggestion to adjust paths at line edit and improve your specific case.

**Comment by thany** [comment]
@vtmateos So please explain why this issue gets closed then?
