### ISSUE TITLE
Completed tab only shows "new completed"

### ISSUE THREAD

**Issue by thany** [meganz/MEGAsync#539]
Look at this:
![image](https://user-images.githubusercontent.com/152227/107893863-cee11100-6f2d-11eb-8cd3-713151a1f748.png)

Looks like 2 completed files, doesn't it?

Now let's click that tab:
![image](https://user-images.githubusercontent.com/152227/107893883-e15b4a80-6f2d-11eb-8961-7bc1b8967c68.png)

Yeah, no, that's a bit more, innit?

What bloody good is it to show only the amount of completed file since I last had that tab visible? Show the total number of completed files. The same suggestion goes for the Upload & Download tabs. Show a number on them as well.

Oh and don't show "999+", that's bollocks. If you have space to render a `+`, you have space to render another digit. Show the real, actual, accurate, total number of files on that tab.

A number like "new things added on this tab since you've last seen me" on those tabs not useful in any scenario I can personally imagine. So please either do enlighten me on this, or fix it.

**Comment by vtmateos** [comment]
Thanks for the feedback on that. We are working on new features and improvements for the transfer manager, so I will forward your feedback to UI team for analysis and consideration. Stay tuned!

**Comment by thany** [comment]
@vtmateos So please explain why this issue gets closed then?
