### ISSUE TITLE
"This process is taking longer than expected"

### ISSUE THREAD

**Issue by LSmyrnaios** [meganz/MEGAsync#543]
Hi, for a few days now, MEGAsync has become very slow when syncing files and logging-out.
It shows the message in the title and just hangs there for many minutes.
Nothing has changed from my side, either with networking or file-systems.

**Comment by PhilosAccounting** [comment]
I think I've had the same issue, if your issue was specifically on Linux. I rebooted it and it worked fine. Are you trying to sync across multiple devices?

**Comment by LSmyrnaios** [comment]
Yes, I am syncing files between a remote Ubuntu 18.04 and a Windows 10 machine.
I tried restarting the program and re-logging-in, in both machines but nothing changed.
I will try a system reboot on Linux, hope it fixes the issue. Thanks.

**Comment by LSmyrnaios** [comment]
I tried one more time (without restarting the Linux machine) and it just worked fine this time.
I guess they had a server-issue that got resolved in the meantime.
