### ISSUE TITLE
MEGAsync's connectivity monitoring triggers WiFi channel scans and causes network latency

### ISSUE THREAD

**Issue by josephvusich** [meganz/MEGAsync#546]
When connected to WiFi, the sync client triggers scans of the surrounding WiFi networks every 60 seconds. As the radio does not transmit while scanning, this manifests as recurring latency spikes 50-100ms above the running average, lasting about 1-2 seconds every minute. I have only investigated this on Mac OS, and cannot confirm if other platforms are affected.

The culprit appears to be [`checkNetworkInterfaces()`](https://github.com/meganz/MEGAsync/blob/6c3cd451b6f51d75b56b3e6f5a7bda04d7d516c5/src/MEGASync/MegaApplication.cpp#L2646) which is triggered by [`periodicTasks()`](https://github.com/meganz/MEGAsync/blob/6c3cd451b6f51d75b56b3e6f5a7bda04d7d516c5/src/MEGASync/MegaApplication.cpp#L3025). The goal of this method seems to be detecting IP address changes by checking for a change in the number of network adapters, and/or a new IP associated with any adapter. The way in which this information is determined doesn't seem ideal, since `ifconfig` and `ipconfig getifaddr en1` return the same type of data without triggering a channel scan.

The frequency seems to be controlled by the preference entry `STATE_REFRESH_INTERVAL_MS`, however editing `MEGAsync.cfg` is non-trivial due to the obfuscated format. Creating a config editor to experiment with different values is a road I haven't gone down yet.

This behavior of MEGAsync with regards to Mac OS specifically has been [documented](https://community.ui.com/questions/Dropped-Packets-every-60s/34bffcdc-5c94-437e-b67b-ab83230571bb) online multiple [times](https://apple.stackexchange.com/questions/263638/macbook-pro-experiencing-ping-spikes-to-local-router#comment513273_348574) over the past couple of years, and does not seem specific to my setup.

I've included the relevant logs below, complete with timestamps for ease of comparison:

<details>
  <summary>Ping log</summary>

```
# ping 192.168.1.1 --apple-time
00:09:31.956186 64 bytes from 192.168.1.1: icmp_seq=4345 ttl=64 time=1.692 ms
00:09:32.956884 64 bytes from 192.168.1.1: icmp_seq=4346 ttl=64 time=1.737 ms
00:09:34.009654 64 bytes from 192.168.1.1: icmp_seq=4347 ttl=64 time=51.799 ms
00:09:35.063427 64 bytes from 192.168.1.1: icmp_seq=4348 ttl=64 time=100.601 ms
00:09:35.964565 64 bytes from 192.168.1.1: icmp_seq=4349 ttl=64 time=1.383 ms
00:09:36.967712 64 bytes from 192.168.1.1: icmp_seq=4350 ttl=64 time=1.712 ms
```
</details>

<details>
  <summary>WiFi driver log</summary>

_(To enable WiFi logging, hold Option and click the WiFi menu, then select "Enable WiFi Logging")_
```
# tail -f /var/log/wifi.log
Wed Feb 24 00:09:33.653 AutoJoin: <airportd[12345]> Successful cache-assisted scan request for MEGAclient with channels {(
Wed Feb 24 00:09:33.653     <CWChannel: ...> [channelNumber=7(2GHz), channelWidth={20MHz}, active],
Wed Feb 24 00:09:33.653     <CWChannel: ...> [channelNumber=36(5GHz), channelWidth={40MHz(+1)}, active]
Wed Feb 24 00:09:33.653 )} took 0.2745 seconds, returned 3 results
Wed Feb 24 00:09:33.917 Driver Event: <airportd[12345]> _bsd_80211_event_callback: SCAN_CACHE_UPDATED (en1)
Wed Feb 24 00:09:33.917 AutoJoin: <airportd[12345]> Successful cache-assisted scan request for MEGAclient with channels {(
Wed Feb 24 00:09:33.917 )} took 0.2636 seconds, returned 5 results
Wed Feb 24 00:09:34.732 Driver Event: <airportd[12345]> _bsd_80211_event_callback: SCAN_CACHE_UPDATED (en1)
Wed Feb 24 00:09:34.732 AutoJoin: <airportd[12345]> Successful cache-assisted scan request for MEGAclient with channels {(
Wed Feb 24 00:09:34.733 )} took 0.8151 seconds, returned 2 results
Wed Feb 24 00:09:35.781 AutoJoin: <airportd[12345]> Successful cache-assisted scan request for MEGAclient with channels {(
Wed Feb 24 00:09:35.781 )} took 1.0486 seconds, returned 0 results
Wed Feb 24 00:09:36.583 Driver Event: <airportd[12345]> _bsd_80211_event_callback: SCAN_CACHE_UPDATED (en1)
Wed Feb 24 00:09:36.583 AutoJoin: <airportd[12345]> Successful cache-assisted scan request for MEGAclient with channels {(
Wed Feb 24 00:09:36.583 )} took 0.8017 seconds, returned 3 results
Wed Feb 24 00:09:36.675 AutoJoin: <airportd[12345]> Successful cache-assisted scan request for MEGAclient with channels {(
Wed Feb 24 00:09:36.675 )} took 0.0918 seconds, returned 0 results
Wed Feb 24 00:09:36.681 Info: <airportd[12345]> Filtering BSSID from scan results because location services is disabled, pid 67890 (MEGAclient)
```
</details>

<details>
  <summary>MEGAsync log</summary>

```
# tail -f "~/Library/Application Support/Mega Limited/MEGAsync/logs/MEGAsync.log"
02/24-08:09:33.067368 0x12345abcd DBG  Active network interface: lo0 [:-1]
02/24-08:09:33.067385 0x12345abcd DBG  Ignored IPv4: 127.0.0.1 [:-1]
02/24-08:09:33.067404 0x12345abcd DBG  Active network interface: en0 [:-1]
02/24-08:09:33.067411 0x12345abcd DBG  Active network interface: ap1 [:-1]
02/24-08:09:33.067412 0x12345abcd DBG  Active network interface: en1 [:-1]
02/24-08:09:33.067421 0x12345abcd DBG  IPv4: 192.168.1.10 [:-1]
02/24-08:09:33.067456 0x12345abcd DBG  Active network interface: bridge0 [:-1]
02/24-08:09:33.067525 0x12345abcd DBG  Local network adapters haven't changed [:-1]
```
</details>

**Comment by vtmateos** [comment]
Thanks for the detailed report @josephvusich, it is really appreciated. 

I've digging into that and it seems the culprit is the call to [`QNetworkConfigurationManager::updateConfigurations()`](https://github.com/meganz/desktop/blob/8be168a555c41403e3328d00e9faf84781601975/src/MEGASync/MegaApplication.cpp#L2213) which is call at 60s interval (`STATE_REFRESH_INTERVAL_MS` triggers `periodicTasks()`each 10s) causing a WLAN scan to obtain current state of network configurations.

We will work to fix this issue and relax the calls to update network configurations.

**Comment by icstyle** [comment]
Any update on this? When will it put into release code? It's really annoying to close MEGAsync everytime I want to do cloud gaming and reopen it afterwards. Thanks
