### ISSUE TITLE
Can't we choose to exclude specific sub-folders from syncing ?

### ISSUE THREAD

**Issue by sheerlox** [meganz/MEGAsync#55]

**Comment by polmr** [comment]
At the moment you can define exclusions in Advanced/Settings. However, bear in mind that at the moment those exclusions affect to file or folder names. If you include a folder name here, all occurrences of that folder will be skipped, no matter their location. Things such as "folder/subfolder" are not allowed. We are working on including more flexible exclusions with regular expressions and complete paths and the like

**Comment by SherlockStd** [comment]
Is this will be done for v3.0 ?

**Comment by TigersWay** [comment]
Any news about this?

**Comment by MartinacPlus** [comment]
Is the selective exclude/include of folders/subfolders present in the current version 3.6.0 of the MEGAsync client?
In Advanced/Settings I can exclude a whole folder, but it is not possible to include a sub-folder of this excluded folder - at least I get an error when trying to do so ("The selected local folder is already synced.").

**Comment by dobry-op** [comment]
Hi
Where can I get a man about regular expressions for exclusions? Thanks

**Comment by LewisMojica** [comment]
Hi!
this feature It's already working in the version 3.6.7 in Settings/Advanced 💃

**Comment by reyjaleel** [comment]
what about exclusion based on file size for CLI usage

**Comment by Rober19** [comment]
**This is an example**

![image](https://user-images.githubusercontent.com/28882108/60407541-d305c280-9b80-11e9-84ff-095ec5afbc58.png)

**Comment by atreeon** [comment]
Hi, I'm trying to exclude any build directories in my android directory, I've tried
`*/android/build/*`
`**/android/**/build/**`
`/android/**/build/`
I haven't had any luck.  Is this possible?  What would be the correct syntax

**Comment by mattw-mega** [comment]
Only the name of the folder (or file), not its path, is compared.  You might want to specify just `build`, or change the folder name to something a bit less likely to have a clash.   To remove files already synced you should  be careful since it's a two-way sync, and normally removing in the cloud will also remove your local version.    I'd recommend unticking the sync checkbox in settings (and click the Apply button, on windows) first.  Then remove those in the cloud, then tick the sync box again.

**Comment by atreeon** [comment]
Unfortunately I cannot specify the name of the `build` folder but it might just about be ok doing it that way.  It would be nice if you could specify specific patterns to exclude files - it would really reduce the time syncing as I could exclude more files.

**Comment by yanivm** [comment]
For anyone still interested in this feature in 2020 - see [MEGA's FAQ page under "Can I exclude specific folder(s) and file(s) when I sync?"](https://mega.nz/help/client/megasync/syncing/can-i-exclude-specific-folder-s-and-file-s-when-i-sync-576c83d1886688e7028b4583), where they essentially say: **Settings** -> **Advanced** -> **Add** (under "Excluded file and folder names")

(this just worked for me, using client version 4.3.3 in Windows 10)

**Comment by Mr1262** [comment]
Okay 
Thanks 🙏

**Comment by KamillaPup** [comment]
Is this still not a thing? It's been six years and you still can't finetune syncs?

**Comment by mattw-mega** [comment]
Hi @KamillaPup , you may like to check issue #770 which details how we are adding a very flexible mechanism to fine-tune your syncs.  thanks
