### ISSUE TITLE
debian bullseye install problem

### ISSUE THREAD

**Issue by rolo48** [meganz/MEGAsync#553]
I have a Problem to install megasync desktop app in debian bullseye (testing). Problem is libraw19. 

root@KanotixHPBox:/home/roland/Downloads# dpkg -i megasync-Debian_10.0_amd64.deb
Vormals nicht ausgewähltes Paket megasync wird gewählt.
(Lese Datenbank ... 270814 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von megasync-Debian_10.0_amd64.deb ...
Entpacken von megasync (4.4.0-1.1) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von megasync:
 megasync hängt ab von libc-ares2 (>= 1.11.0~rc1); aber:
  Paket libc-ares2 ist nicht installiert.
 megasync hängt ab von libmediainfo0v5 (>= 0.7.56); aber:
  Paket libmediainfo0v5 ist nicht installiert.
 megasync hängt ab von libraw19 (>= 0.16.0); aber:
  Paket libraw19 ist nicht installiert.
 megasync hängt ab von libzen0v5 (>= 0.4.31-2~); aber:
  Paket libzen0v5 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes megasync (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für mailcap (3.69) werden verarbeitet ...
Trigger für desktop-file-utils (0.26-1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.17-2) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 megasync
root@KanotixHPBox:/home/roland/Downloads# apt -f install
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Abhängigkeiten werden korrigiert … Fertig
Die folgenden Pakete werden ENTFERNT:
  megasync

**Comment by sakethv-mega** [comment]
Hello, please try and check if this one helps
`ln -s /usr/lib/x86_64-linux-gnu/libraw.so.{20,19}`

**Comment by ncarrier** [comment]
@sakethv-mega I doubt this will work since it's dpkg which is blocking the installation of the package, while your trick will only solve potential real time issues.

On my side, I installed megasync by compiling it, it worked fine under bullseye.

**Comment by rolo48** [comment]
Problem gelöst, Paket "libraw19  " manuell installiert 
http://ftp.de.debian.org/debian/pool/main/libr/libraw/libraw19_0.19.2-2_amd64.deb
Tip von hier: https://forum.sparkylinux.org/index.php?topic=5540.0
