### ISSUE TITLE
configure ( compile for Linux )

### ISSUE THREAD

**Issue by tele1** [meganz/MEGAsync#56]
From MEGAsync-1.0.38.0_Linux to Master
I have

```
$ pwd
/home/tele/Downloads/TEST/MEGAsync-master/src
[tele@localhost src]$ ./configure
./configure: line 68: ./MEGASync/mega/contrib/build_sdk.sh: No such file or directory
./configure: line 74: ./contrib/build_sdk.sh: No such file or directory
ln: failed to create symbolic link ‘/home/tele/Downloads/TEST/MEGAsync-master/src/MEGASync/mega/bindings/qt/3rdparty/libs’: No such file or directory
```

I read README.md
Building:

```
sudo apt-get install build-essential autoconf automake m4 libtool qt4-qmake make libqt4-dev libcrypto++-dev libsqlite3-dev libc-ares-dev
sudo apt-get install libnautilus-extension-dev

cd src
./configure
qmake MEGA.pro
lrelease MEGASync/MEGASync.pro
make
```

**Comment by polmr** [comment]
Have you run `git submodule update --init --recursive` after cloning the repository?

**Comment by tele1** [comment]
Not, I seen this only in old Readme file.
Exist way download submodule hand, without git ?

**Comment by tele1** [comment]
Now I see in REadmi link, i will check.

**Comment by polmr** [comment]
> Exist way download submodule hand, without git ?
Yes, although it is highly disregarded: You can browse at https://github.com/meganz/MEGAsync/ to the submodule src/MEGASync/mega. This will open the sdk submodule at the commit in which is linked. You can download it as a zip manually. Then unzip its contents into src/MEGASync/mega.

**Comment by tele1** [comment]
I tested on Manjaro Linux
I download 
https://github.com/meganz/MEGAsync
and 
https://github.com/meganz/sdk
and I unpack sdk to MEGAsync-master/src/MEGASync/mega/

Link I get hand from "mega" link in this repository

```
cd MEGAsync-master/src
./configure
qmake MEGA.pro
lrelease MEGASync/MEGASync.pro
make
```


Compiled with success  !   👍 

I don't know how download will work with git,
so probably you have right with "  git submodule update --init --recursive  "
Before I download only https://github.com/meganz/MEGAsync 
manualy / hand from this website and I had .../src/MEGASync/mega/ empty

Please note about this in README.md in " Linux compilation " section.

**Comment by tele1** [comment]
You can close. :-)
