### ISSUE TITLE
Replacing some files sometimes ends up permanently deleting them

### ISSUE THREAD

**Issue by ZdrytchX** [meganz/MEGAsync#561]
If I'm running an app that saves documents to the cloud folder, replacing the old document sometimes results in a permanent deletion. The only way to recover once the application has closed is to go through the website and navigate to the trash and recover the latest date for the file.

When I say "sometimes" it does it every time once it has started doing this issue until the computer is restarted.

**Comment by sakethv-mega** [comment]
Hello, can you please check if by any chance the timestamp on the updated file is older than the timestamp of the file on the cloud drive?

**Comment by ZdrytchX** [comment]
Will do if I encounter the issue again (I havent been using megasync lately)
