### ISSUE TITLE
Dependency is not satisfiable: libraw19 (>= 0.16.0)

### ISSUE THREAD

**Issue by NewsunBanjade** [meganz/MEGAsync#565]
I'm Trying To Install MegaSync on Kali linux 2021. Debian Version 10. This Error Dependency is not satisfiable: libraw19 (>= 0.16.0)
. Shows In terminal.

**Comment by NewsunBanjade** [comment]
Actually I solved This Issue by installing  libraw19_0.19.2-2_amd64.deb from 

http://ftp.br.debian.org/debian/pool/main/libr/libraw/libraw19_0.19.2-2_amd64.deb

install it with sudo dpkg -i libraw19_0.19.2-2_amd64.deb

**Comment by sailinggalaxians** [comment]
This issue exists in Mageia 8 as well.
We have libraw20.

Attaching my spec-file and build log if that helps.
