### ISSUE TITLE
New update looking for old lib (Linux)

### ISSUE THREAD

**Issue by RPINerd** [meganz/MEGAsync#567]
When launching megasync:
`megasync: error while loading shared libraries: libicuuc.so.68: cannot open shared object file: No such file or directory`

The current version of icu is 69 not 68

**Comment by polmr** [comment]
Hi @RPINerd .
It seems you are using a rolling release distro and current MEGAsync package needs updaing. 
Would you mind specifying what is your OS? Arch linux? 
We will provide a new package asap. Thanks for reporting that.

**Comment by RPINerd** [comment]
Ah yes I am, it is EndeavourOS but basically it's a GUI installer for Arch linux

**Comment by sakethv-mega** [comment]
Hello there, our team has built the updated packages and they will be made available soon. Thank you.

**Comment by RPINerd** [comment]
`/usr/bin/ld: warning: libicuuc.so.68, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to `u_isspace_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to `u_isalnum_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to `u_toupper_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to `u_isalpha_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to `u_tolower_68'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1206: megasync] Error 1
make[1]: Leaving directory '/home/chris/.cache/yay/megasync/src/MEGAsync/src/MEGASync'
make: *** [Makefile:47: sub-MEGASync-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: megasync`
So I'm guessing this 4.5.x update was supposed to address this, however I'm getting build failures. is the "try using -rpath or -rpath-link" something I can actually implement to work around this?
I also tried to completely reinstall from scratch and the same error message occurs
