### ISSUE TITLE
Windows: difference in folder capitalization is associated with silent sync failure

### ISSUE THREAD

**Issue by MarkDBlackwell** [meganz/MEGAsync#57]
Today, using two computers: A (running Windows 7) and B (running Windows XP), I experienced the following issue. (Admittedly, this report may contain more details than strictly necessary.)

Here are some steps to reproduce the problematic behavior:

1. _Without_ syncing running on A and B, I created folder `try-sync-fail` on A, and folder `Try-Sync-Fail` on B (both at the root of their respective MEGA folders). (These two names differ only in their capitalization.)
1. Within folder `try-sync-fail` on A, I created file `file.txt` containing the text, "thing" (followed by line-feed, LF).
1. Within folder `Try-Sync-Fail` on B, I created the same-named file `file.txt` also containing the text, "thing" (also followed by LF).
1. On A, I started the MEGAsync program, and waited for it to report that its syncing was complete.
1. On B, I started the MEGAsync program, and similarly waited for it to report that its syncing was complete.
1. On B, I opened an editor, and changed the text of the same file (`file.txt`) from "thing" to "thing one" (followed by LF), and then exited the editor.
1. On A, I opened an editor, and changed the text of the same-named file (`file.txt`) from "thing" to "thing two" (notice the difference—followed by LF), and then exited the editor.
1. I observed the following: on neither A nor B did the MEGAsync program reconcile this folder and file, but instead:
    1. It left each of the two folder names (differing in capitalization) just as they were (without creating others); and
    1. It left each of the two files' (differing) contents, just as they (last) had been edited.

However, additional files added to either A or B did correctly sync. Each such file did appear in the other computer.

**Comment by polmr** [comment]
Older versions of megasync experienced such issues with upper/lower-case.  Please, ensure you have megasync in its latest version in all your computers.

**Comment by MarkDBlackwell** [comment]
@polmr hovering over the MEGAsync icon in the system tray (a white M inside a red circle) on the two computers produces the following results:
1. On Windows 7: "MEGAsync 2.9.10 / Up to date"; and
1. On Windows XP: "MEGAsync 2.9.10 / Up to date".

**Comment by polmr** [comment]
newer versions released. not reproducible.
