### ISSUE TITLE
v4.5.0.0 for Linux missing

### ISSUE THREAD

**Issue by brackenhill-mob** [meganz/MEGAsync#572]
Is support coming or being dropped?

Mac version put up 10 days ago at time of writing

TIA

**Comment by sakethv-mega** [comment]
A new version v4.5.1 for Linux is coming soon. Thank you.

**Comment by decoomanj** [comment]
Any updates on the release-date?

**Comment by Perkolator** [comment]
Bad changelogs, client "check update" doesn't work properly, missing platform updates...

**Comment by decoomanj** [comment]
We are now at v4.5.2 for Win and OSX? Eagerly awaiting the Linux release to fix some crashes....

**Comment by sakethv-mega** [comment]
Hello there, we are going to release v4.5.3 for Linux along with Windows and OSX. They are currently under testing and we aim to release them by next week or two. Thank you for your patience.

**Comment by decoomanj** [comment]
Thank you for the release! It fixed an annoying bug which made my client crash on a daily basis. Keep up the good work :1st_place_medal:

**Comment by sakethv-mega** [comment]
Thank you !!!
