### ISSUE TITLE
libicuuc.so.68 Build Failure

### ISSUE THREAD

**Issue by RPINerd** [meganz/MEGAsync#574]
```
/usr/bin/ld: warning: libicuuc.so.68, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to 'u_isspace_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to 'u_isalnum_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to 'u_toupper_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to 'u_isalpha_68'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libpdfium.so: undefined reference to 'u_tolower_68'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1206: megasync] Error 1
make[1]: Leaving directory '/home/chris/.cache/yay/megasync/src/MEGAsync/src/MEGASync'
make: *** [Makefile:47: sub-MEGASync-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: megasync
```
So I'm getting build failures when trying to install the latest MEGASync from the AUR. Is the "try using -rpath or -rpath-link" something I can actually implement to work around this?
I also tried to completely reinstall from scratch and the same error message occurs

**Comment by RPINerd** [comment]
I've taken some time to do my own sleuthing and maybe I overlooked something obvious.. the first line for the error above suggests that the version of gcc being used during building is what's actually looking for icu68. GCC 10.2.0 is from late 2020 if memory serves, the latest is 10.3.0 from April 8th 2021. Maybe that newer version has sorted out this old dependency version?

The other thing I'm going to try this evening is explicit install of the libpdfium, something on the AUR git page just gave me a hunch that it might be an easy troubleshooting point to do on my own.

**Comment by diabolusss** [comment]
Hi, have you managed to work around this or downgrade is the only option?

**Comment by RPINerd** [comment]
> Hi @RPINerd, have you managed to work around this or downgrade is the only option?

So I haven't tried uninstalling icu68, but I never removed v69 and there have been several large updates since I made this post so it's possible that the issue has been resolved

**Comment by diabolusss** [comment]
Thanks for a reply. Actually, clean build have helped me.

**Comment by RPINerd** [comment]
This is still an ongoing issue with any update to either icu or megasync, I constantly have to refer back to this issue ticket to remember how to fix things whenever theres an update

**Comment by Rmano** [comment]
@RPINerd  tried the cleanbuild, it does not work (now the error is about `/usr/lib/libpdfium.so: undefined reference to `u_isspace_75'` ... what's happening with this library?

**Comment by RPINerd** [comment]
> @RPINerd  tried the cleanbuild, it does not work (now the error is about `/usr/lib/libpdfium.so: undefined reference to `u_isspace_75'` ... what's happening with this library?
> 

I still have occasional install issues, but it has gotten better. Anecdotally, the constant ic version change issue hasn't been a problem but occasionally libodium throws a fit. I've found the best course of action is just wait a few days and update again. Specifically if you're running Arch too, update all the base packages and then update the aur in a separate operation. I don't know why but this has fixed a failing install before for me.

**Comment by Rmano** [comment]
Well, I tried it, but it still failed... I'll wait. I have a manjaro distro. Everything updates correctly minus Megasync. Well... Thanks anyway.

**Comment by RPINerd** [comment]
> I have a manjaro distro.

I know the linux world is already overflowing with opinionated attacks on distros, but I left manjaro a long time ago because it was regularly breaking with updates or not actually getting the latest versions  of some things. If you're happy with it, more power to you, just maybe consider giving something like EndeavourOS a spin? 

Switching might not fix this issue as my desktop is getting the error you posted while my laptop is fine, both running Arch, so I'm not blaming Manjaro for your troubles 😄

**Comment by Rmano** [comment]
I will look at EndeavourOS, but my experience with Manjaro has been very good (at least, with my Gnome flavour). The only things that give problems are MegaSync and (for other issues) PaloAlto GlobalConnect.

By the way, I found a solution: uninstall `megasync`, then uninstall `libpdfium`, then reinstall megasync-bin. It's not the best thing, but hey, it's working.
