### ISSUE TITLE
Uploading files already present in the account

### ISSUE THREAD

**Issue by sixtyfive** [meganz/MEGAsync#575]
Hi,

I'm having a peculiar issue with MEGAsync where it keeps uploading things that really should not be uploaded. I suspect I might have caused it by moving everything to a new harddrive locally in a way that the filestamps are now of the day when I copied from the old to the new harddrive. After then instructing MEGAsync to use the new location, it began uploading everything to my account - even though the files were already in there and of the same size (and same contents). I configured a small subfolder to let it happen and go through, and lo and behold, all files were uploaded and replaced by identical copies.

So it seems that files are not getting hashed or sync'd based upon their sizes, but strictly based on filestamps. Also I found no way of simply disabling uploads completely to get around the problem. Setting an upload bandwidth of 0kB/s causes the upload bandwidth limit to be disabled, which might require another Issue to be opened.

In case it matters:

- Arch Linux
- versioning disabled
- account is Pro III

Any help would be appreciated!

**Comment by sakethv-mega** [comment]
Hello, the only way to completely stop sync operation is to disable the sync path by going to Settings > Syncs and unticking the check box next to the sync path. Thank you.

**Comment by sixtyfive** [comment]
Did you read what the actual problem is?

**Comment by ortmann** [comment]
It is correct that the sync algorithm assumes that a file has changed whenever it finds a changed timestamp during a rescan (and a rescan has to happen in this scenario). Normally, it is a relatively rare corner case an unmodified file has its timestamp bumped, and verifying that would require reading the file in full. We generally discourage copying synced folders without timestamp preservation (unfortunately, /bin/cp requires an extra flag, -p, to accomplish this).

**Comment by sixtyfive** [comment]
`/bin/cp requires an extra flag, -p, to accomplish this`

Yes that was my mistake that I'll readily admit to. Okay, so since this seems to be a use case that you have no plans of covering, could you point me to the part of the code where the timestamp comparison is made so I that I can myself try to implement a size check there instead?
