### ISSUE TITLE
One or More Sync Have Been Disabled

### ISSUE THREAD

**Issue by asheroto** [meganz/MEGAsync#581]
Getting this even though my account is paid.  Restarted app, restarted computer, all syncs are enabled, but message persists.

![image](https://user-images.githubusercontent.com/49938263/119277005-d5dd8680-bbe2-11eb-8849-1ffe90d22e9b.png)

**Comment by sakethv-mega** [comment]
Hello, if possible, can you please reply back with the screenshot of the syncs tab? Thank you.

**Comment by asheroto** [comment]
![image](https://user-images.githubusercontent.com/49938263/119312649-3e0a8780-bc38-11eb-92ed-fe919aeb8264.png)

**Comment by sakethv-mega** [comment]
Hello there, can you please email support@mega.nz from your registered email address so that we can investigate further? Thank you.

**Comment by asheroto** [comment]
Okay, thank you. Closing this for now.
