### ISSUE TITLE
Linux v4.5.0 c11a688 forgets sync settings

### ISSUE THREAD

**Issue by DurhamDecLab** [meganz/MEGAsync#585]
As title, Gentoo Linux, every time software restarts it forgets all synced folders, have to re-add them.

**Comment by sakethv-mega** [comment]
Can you disable MEGAsync on startup, launch the app manually after booting and check if that makes any difference? Also, advise us of the MEGAsync version that you are running. Thank you

**Comment by DurhamDecLab** [comment]
Hi, it's v4.5.0 c11a688 built using march=native on an i7-4700MQ, I've tried both GCC 10.2.0 and 11.1.0 and all optimisations removed. If the program is just launched manually it behaves the same; if I close it and re-open it loses all sync folder settings, or if it crashes and restarts. I've reverted to 4.4.0 and it works fine. However, I've now tried this on a different Gentoo computer running an AMD K10 and 4.5.0 doesn't have the same problem, so it may be specific to Intel architecture? I may be able to test on a different Intel machine this week.

**Comment by petsam** [comment]
I have the same issue in Garuda Linux (archlinux based).

megasync v.4.5.3.0-1 (chaotic-aur , built from [AUR](https://aur.archlinux.org/packages/megasync/)

After exiting megasync and restarting, all pre-set syncs are gone.

Any hint on where these settings are kept/saved?

Could that relate with memory, cache or CoW/btrfs?

**Comment by DurhamDecLab** [comment]
BUMP
Exactly the same thing is now happening on MX Linux, client version 4.5.3 (7c8db8f)

**Comment by DurhamDecLab** [comment]
NOW same issue on Artix Linux with version 4.5.3. Reverting to 4.4.0 fixes it. This is now a major pain for me.

**Comment by petsam** [comment]
megasync-bin 4.6.3-4 from AUR does not have this issue for me (Archlinux).
Still megasync 4.6.3.0-1 AUR keeps losing sync folders.
Something might be wrong in packaging...?

**Comment by DurhamDecLab** [comment]
> megasync-bin 4.6.3-4 from AUR does not have this issue for me (Archlinux). Still megasync 4.6.3.0-1 AUR keeps losing sync folders. Something might be wrong in packaging...?

**Comment by DurhamDecLab** [comment]
> megasync-bin 4.6.3-4 from AUR does not have this issue for me (Archlinux). Still megasync 4.6.3.0-1 AUR keeps losing sync folders. Something might be wrong in packaging...?

I built 4.4.0 from source and that's the only version that seems to work for me. It's disappointing but at least I'm able to work.
