### ISSUE TITLE
files with ":" in name are synced with "%3a" in place of it (Linux)

### ISSUE THREAD

**Issue by Szwendacz99** [meganz/MEGAsync#589]
I am syncing folder that contains files with time in its name with format hh:mm:ss, and when these files are copied to different device via megasync characters ":" are replaced to string  "%3a", but only locally, on mega drive opened via web browser, these files have proper name. 
I am on Arch Linux, using latest MEGAsync via flatpak

**Comment by polmr** [comment]
MEGAsync engine, syncs down escaping some characters on purpose for giving a coherent cross-platform behaviour.
You can rename them locally and the sync engine will continue working.
