### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by trajano** [meganz/MEGAsync#59]
Provide a package for https://chocolatey.org/

**Comment by trajano** [comment]
http://chocolatey.github.io/contribute.html#creating-chocolatey-packages

**Comment by trajano** [comment]
https://chocolatey.org/docs/create-packages

**Comment by trajano** [comment]
<pre>
$packageName = 'megasync'
$fileType = 'exe'
$url = 'https://mega.nz/MEGAsyncSetup.exe'
$silentArgs = '/S'

Install-ChocolateyPackage $packageName $fileType $silentArgs $url
</pre>

**Comment by trajano** [comment]
I tried to build one but I couldn't get the installer to work with `/S` correctly.

**Comment by trajano** [comment]
I got it working, but it won't work on AppVeyor https://github.com/trajano/choco-packages/tree/master/megasync I think something hangs in the UI but it works properly on Windows 10.

**Comment by vtmateos** [comment]
Dear user,
For the moment there is no plan to provide Chocolatey package support in mid term, but we will take your suggestion into account.
Thanks for your suggestions.
