### ISSUE TITLE
Flattened icon on the macOS screen which isn't in use

### ISSUE THREAD

**Issue by Tizioincognit0** [meganz/MEGAsync#592]
When I plug one or more monitor to my MacBook Pro 16" with macOS 11.4 Big Sur, MEGASync tray icon is flattened when it appears on monitors that aren't in use.
<img width="31" alt="Schermata 2021-06-12 alle 14 46 48" src="https://user-images.githubusercontent.com/40031873/121776474-5c0b3e00-cb8d-11eb-8f57-6b084c5d8689.png">

**Comment by sakethv-mega** [comment]
Hello, we are aware of this issue and we are working towards fixing it. Thank you.
