### ISSUE TITLE
megasync does not play well with others.

### ISSUE THREAD

**Issue by timoc** [meganz/MEGAsync#6]
I use linux. I'm loooking into moving some of my work from dropbox, and i'm missing a mechanism like the dropbox.py script, that allows me to inquire as to the state of the service (synching, idle, not started, connected etc) from a bash script or cron job. 

While it understands --version, the megasync does not respond to --help.

**Comment by javiserrano** [comment]
Currently, MEGAsync only acceps `--version` and `--debug` (to print logs to `stdout`).
We still don't have any tool to query the state of the service or individual files or folders. Currently, that information can only be seen in the GUI or in Nautilus thanks to our extension.

It would be possible to use the same interface as our extension for Nautilus to get that information. You can take a look at these files to see how it works:
- https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/platform/linux/NotifyServer.cpp
- https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/platform/linux/ExtServer.cpp
- https://github.com/meganz/MEGAsync/tree/master/src/MEGAShellExtNautilus

We might provide a command-line tool to get that information in the future, but it isn't one of our current priorities, sorry.

Another option would be to use `megasimplesync`, that is a command line tool that uses the same sync engine as MEGAsync. In the source code of that tool you can see callbacks that provide the state of all files:
- https://github.com/meganz/sdk/blob/master/examples/megasimplesync.cpp

**Comment by timoc** [comment]
Thanks for the update. I will look into it what i can do with it, i guess i can do something with the mega.socket after digging into the megasync code.

If i can give some constructive criticism, after reviewing the general approach and the code?
I would suggest it would be easier to implement extserver as a D-BUS listener for IPC rather than hand roll your own hand rolled listener. That way megasync integration is available to anything that has a dbus library, and that can run a dbus service (linux, windows, and OSX). D-BUS comes out of the box for QT see: http://doc.qt.io/qt-5/examples-dbus.html or http://doc.qt.io/qt-4.8/examples-dbus.html. 

I'm looking at megasimplesync, and from a code review point- I'm not a fan of magic-numbers e.g.:
https://github.com/meganz/sdk/blob/master/examples/megasimplesync.cpp#L140
and i assume its ok, but just in case, i thought to point out that there seems to becredentials  hardcoded into the megasimplesync.cpp source https://github.com/meganz/sdk/blob/master/examples/megasimplesync.cpp#L529
