### ISSUE TITLE
Dependency error on Linux Mint 18.1 (libc-ares2)

### ISSUE THREAD

**Issue by twomby** [meganz/MEGAsync#60]
Can't install the client on Linux Mint 18.1 Cinnamon. Error message from Package installer is the following : 

"Error: Dependency is not satisfiable: libc-ares2 (>= 1.7.4). I'm completely clueless as to what to do, as I cannot find this package in the official ubuntu/mint repos.

Would be much grateful for some ideas as how to proceed. 

Thanks!

**Comment by polmr** [comment]
The dependency is fine:
