### ISSUE TITLE
Build failed on RPi4 Ubuntu

### ISSUE THREAD

**Issue by lee-yunseok** [meganz/MEGAsync#600]
I'm using RPi4(aarch64) Ubuntu(arm64),

Trying to build MEGASync but failed on `make` step.

**Comment by sakethv-mega** [comment]
Do you have `make` installed in your system? if not, please install make using the command
`sudo apt install make` and then try again.
Thank you.

**Comment by lee-yunseok** [comment]
> Do you have `make` installed in your system? if not, please install make using the command
> 
> `sudo apt install make` and then try again.
> 
> Thank you.


Already have it.

**Comment by sakethv-mega** [comment]
Can you please paste the output here so that we can check? Thank you.

**Comment by lee-yunseok** [comment]
Sorry too late. Here I attached full `make` log.
[results.txt](https://github.com/meganz/MEGAsync/files/6733160/results.txt)

**Comment by sakethv-mega** [comment]
Can you please confirm if you have managed to build it or if you still need assistance? Thank you.

**Comment by polmr** [comment]
Thanks for reporting that @lee-yunseok , it seems google-breakpad code needs some changes to compile for arm 64 (we will adjust it eventually).
Note: as stated here https://github.com/meganz/MEGAsync/issues/490, @daniel0076 created a fork that fixes those issues ( https://github.com/daniel0076/MEGAsync ).
You may want to grab his `src/MEGASync/google_breakpad` folder and replace yours

**Comment by daniel0076** [comment]
@lee-yunseok 
Hi, you may replace the `src/MEGASync/google_breakpad` to replace yours, and also "update the makefiles"
you may refer to my [commit](https://github.com/daniel0076/MEGAsync/commit/b9b20d8798bb2b2cfa6f1c9ff259cd00f97877ff)

@polmr Good to hear that Mega will eventually support arm64.

**Comment by lee-yunseok** [comment]
@polmr @daniel0076 It working. Thanks for the advice.

**Comment by polmr** [comment]
Thanks to @daniel0076 for this
