### ISSUE TITLE
Folder Sync says "Warning Storage Limit Exceeded" & Disappears

### ISSUE THREAD

**Issue by sanjaylord** [meganz/MEGAsync#603]
Apparently with the new version of the MEGAsync app once you go over your storage limit, as expected sync stops and the MEGAsync folder in Windows File Explorer left side-menu disappears. But then after you delete stuff in your account and go below the storage limit, the folder DOESN'T re-appear and when you go to the Sync tab in MEGAsync settings it still gives you the ! warning that storage limit has exceeded even though that no longer is the case. 

So you're required to manually delete the Sync folder from the Settings and re-add for it appear again in the File Explorer side bar and then restart the app for the "x" mark denoting the folder sync status to revert to tick mark again.

MEGASync 4.5.2
Windows 10 Home 64-bit

**Comment by sakethv-mega** [comment]
Hello Sanjay,

Please confirm if you are doing this. After deleting the data on your account to free up space due to over storage, are you also emptying the rubbish bin on your account before re enabling the sync again?

Thank you.

**Comment by sanjaylord** [comment]
> Hello Sanjay,
> 
> Please confirm if you are doing this. After deleting the data on your account to free up space due to over storage, are you also emptying the rubbish bin on your account before re enabling the sync again?
> 
> Thank you.

Yes, I'm quite sure that I had emptied the rubbish bin after deleting the content to free up space. Because after I removed the Sync folder, re-added it and restarted the client, the issue immediately went away and the Sync folder re-appeared on the left side of the File Explorer. Older version of MEGAsync would automatically and instantly re-instate the Sync folder the moment you emptied the Rubbish Bin to go below the storage limit. Here you had to remove and re-add the folder and then restart the client for it to recognize the same.

**Comment by sakethv-mega** [comment]
Hello again Sanjay,

The algorithm in MEGAsync has changed since ver. 4.5.0 so after you delete the excess data (and clear your Rubbish bin) you need to re-check the existing synced path check box manually. You do not need to delete and re-create the sync path. The folder should again appear in your File Explorer. If not, please relaunch explorer.

Thank you.

**Comment by sanjaylord** [comment]
> Hello again Sanjay,
> 
> The algorithm in MEGAsync has changed since ver. 4.5.0 so after you delete the excess data (and clear your Rubbish bin) you need to re-check the existing synced path check box manually. You do not need to delete and re-create the sync path. The folder should again appear in your File Explorer. If not, please relaunch explorer.
> 
> Thank you.

Okay, thank you for the clarification on the issue. That doesn't sound like too big of a hassle, I will try that in case I go above the storage limit in the future. 👍
