### ISSUE TITLE
MEGA not open-source anymore?

### ISSUE THREAD

**Issue by taha-mcp** [meganz/MEGAsync#614]
I came across a user on a forum claiming that mega does not share it's source-code anymore and has switched to being a closed-source software. I did look this up on the internet but I didn't find anything to confirm his satement... how valid is that claim? Does MEGA plan to keep the (at the very least) client-side code open-source?

**Comment by taha-mcp** [comment]
As a side-note I see very little to no pull-requests have been merged into the main branch. Is there a specific reason for that?

**Comment by vtmateos** [comment]
Hi!

We share our client source code under the terms of our [LICENSE](https://github.com/meganz/MEGAsync/blob/master/LICENCE.md). The official repository is being updated each time a new MEGAsync version is released, you can also check the releases [here](https://github.com/meganz/MEGAsync/releases)
