### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by pshirshov** [meganz/MEGAsync#618]
Currently MegaSync client is brigh-white under all the operating systems despite of dark mode preferences set by user.

Please support dark mode.

**Comment by vtmateos** [comment]
Thanks for your suggestion. It is in the roadmap and looking forward to have it ready soon. Stay tuned for future updates!!

**Comment by pshirshov** [comment]
I think it's somehow not ethical to close tickets which are not delivered yet. 

By the way, I'm a paying customer.

**Comment by ruben69695** [comment]
We need the dark mode guys!

**Comment by Yasand123** [comment]
Megasync is the only piece of software on my machine that doesn't have dark mode and every time I use it quite literally lights up the room, burning my eyes in the process.

**Comment by t0ma5** [comment]
> Thanks for your suggestion. It is in the roadmap and looking forward to have it ready soon. Stay tuned for future updates!!

Our retinas are still waiting, any update? :)

**Comment by Mactastic1-5** [comment]
No Dark Mode yet.

**Comment by t0ma5** [comment]
> Currently MegaSync client is brigh-white under all the operating systems despite of dark mode preferences set by user.
> 
> Please support dark mode.

2 years sad anniversary, no dark mode yet :(

**Comment by Mactastic1-5** [comment]
Very sad.

**Comment by t0ma5** [comment]
maybe 2024 is the year in which dark mode finally arrives to MEGA

**Comment by t0ma5** [comment]
> Thanks for your suggestion. It is in the roadmap and looking forward to have it ready soon. Stay tuned for future updates!!

maybe 2024 is the year in which dark mode finally arrives to MEGA, we waited almost 3 years :)

**Comment by pshirshov** [comment]
It isn't.

**Comment by t0ma5** [comment]
> Thanks for your suggestion. It is in the roadmap and looking forward to have it ready soon. Stay tuned for future updates!!

Pls remember your words from 2021 🙏🙏🙏

**Comment by xcs011** [comment]
Would be a nice feature

**Comment by ciros88** [comment]
still waiting dark mode for desktop app, as per #829 and #903

**Comment by Sin-Shadow-Fox** [comment]
Update for anyone that genuinely wants dark mode for the desktop app. Download the mobile app and leave a one star review for that on the play store (keep is clean or no one will see it). Companies don't care what you want but they do care about their ratings. If their mobile app has nothing but bad ratings then they'll start caring real quick.

If you have a paid account you can also try [AssassinLV](https://github.com/AssassinLV)'s [idea](https://github.com/meganz/MEGAsync/issues/829#issuecomment-2600761709)

![Image](https://github.com/user-attachments/assets/44ed47f4-59a7-43fc-a8fd-630e9b4f0f4a)

**Comment by ciros88** [comment]
![Image](https://github.com/user-attachments/assets/325fe1c7-932f-4bba-b372-95f1ad7d7b5a)
