### ISSUE TITLE
compatibility with Mac OS X El capitain

### ISSUE THREAD

**Issue by pilot1981** [meganz/MEGAsync#626]
Hi,
which version of MEGA SYNC I have to use to download to have it working fine with Mac OS X El Capitain?

**Comment by sakethv-mega** [comment]
Hello, sorry but we have dropped support for the versions Sierra and below.

Thank you.

**Comment by vtmateos** [comment]
Hi @pilot1981 ,
Please check out [Readme](https://github.com/meganz/MEGAsync) in order to perform a custom build. Due to MEGAsync is built with Qt, you need to set the **MEGAQTPATH** env variable to a valid QT installation path in order to build.

Thanks.
