### ISSUE TITLE
autostart has something wrong in Linux.

### ISSUE THREAD

**Issue by queenmedley** [meganz/MEGAsync#63]
Version : 2.9.1
Os. : Archlinux 64, openbox wm.
Compiled with AUR.

When it autostart with megasync.desktop in .config/autostart 
or just "megasync" in .config/openbox/autostart
it doesn't work and no icon in system tray.

I found that autostart start 2 time as "ps -aux | grep mega."
but just executing megasync in terminal, it works well.

**Comment by polmr** [comment]
There is a new version of megasync (2.9.10). You should try those. Also, please, use https://mega.nz/#sync to download the lattest version as this is the official download source.
If the problem persist with the latest version, please, let us know.
