### ISSUE TITLE
Wrong translation in app settings

### ISSUE THREAD

**Issue by wizard86pz** [meganz/MEGAsync#632]
MEGAsync macOS app, v4.6.0.0 (https://github.com/meganz/MEGAsync/releases/tag/v4.6.0.0_OSX)

One of those two strings needs to be "download", from network settings:
![image](https://user-images.githubusercontent.com/36189429/139150450-fcf743fc-1b86-47c2-add6-d6b49fbe4229.png)

General settings, cut string:
![image](https://user-images.githubusercontent.com/36189429/139150677-b06996a8-de1c-4cb1-9f07-75e99f9498ca.png)

Account settings, details about the remaining free space:
![image](https://user-images.githubusercontent.com/36189429/139150895-7559cdc7-ea72-480a-88be-7f52997bc25c.png)

**Comment by sakethv-mega** [comment]
Hello there,

Thank you for the report.

The Italian translation issues shown in the first and third screenshots have been fixed.

The issue shown in the second screenshot has been raised to our developers and is awaiting a fix.
