### ISSUE TITLE
Apple Silicon support?

### ISSUE THREAD

**Issue by KTachibanaM** [meganz/MEGAsync#634]
Hello 👋 I am wondering if there is a plan to support Apple Silicon?

**Comment by sakethv-mega** [comment]
Hello there, we are already working on it.

Thank you.

**Comment by webdev69420** [comment]
@KTachibanaM @SJang1 it seems that MEGAsync v4.7.2 added Apple Silicon support.
The update should be available automatically, but it's also downloadable here if needed:

- [https://github.com/meganz/MEGAsync/releases/tag/v4.7.2.0_OSX](https://github.com/meganz/MEGAsync/releases/tag/v4.7.2.0_OSX)

Thanks MEGA for finally adding Apple Silicon support! This issue can be closed now.
