### ISSUE TITLE
MEGAsync sits at 6-10% usage while idling

### ISSUE THREAD

**Issue by brightknight2** [meganz/MEGAsync#635]
Hi there,

since a few days (before that I usually didn't pay attention to my task manager so I can't tell for how long this is going on) the MEGAsync client sits at 6-10% CPU usage (Ryzen 7 3700x) while doing nothing. The app isn't opened and doesn't have anything to sync. I guess that can't be normal.

I'm using Windows 10 Pro 21H1 (19043.1288). 

Any idea if there is something I could do about this myself?

**Comment by mattw-mega** [comment]
Have a look in "C:\Users\<you>\AppData\Local\Mega Limited\MEGAsync\logs\MEGAsync.log", where MEGAsync records what it's doing.  You should be able to see the paths of any files that it is working on, perhaps there is something unresolved.  thanks

**Comment by brightknight2** [comment]
All I can see in those logs is stuff like this "–6úýþŠšpÜ¹v‡YÊ}a„£ƒ–äåmm-ÉÓï¸£!‰¯(‚M€¶ä÷¿ß\N’¨" I have no idea how to interpret that...

**Comment by mattw-mega** [comment]
The file MEGAsync.log does tell you what it's been doing very recently, please do check again.   The files that contain that nonsense text have extension .0 .1 .2 etc, those are older portions of the log that have been compressed.   If you check the one just called MegaSync.log (with no further extension, and it'll be the one with the most recent Date Modified), you'll see what it is doing.  thanks

**Comment by brightknight2** [comment]
Oh I see. Sorry, windows said it 0KB in size so I didn't bother to open it up.
Now I figured out what actually causes MegaSyncs CPU usage to go up. But I still don't understand why. 
I'm using a tool called "Obsidian" a lot. It's a note taking tool using only textfiles. And my note-folder is synced by megasync. As soon as I open Obsidian, MegaSync goes wild. Even though I'm not doing anything (so no files are changed). 

Here is the log from a couple of seconds. I removed the filenames. Maybe you can now figure out what is going on and what I can do about it.

 
> 11/08-05:40:14.317457 21728 DTL  sc cURL: Mark bundle as not supporting multiuse [net.cpp:1762]
11/08-05:40:14.317462 21728 DTL  sc Header: HTTP/1.1 200 OK [net.cpp:2487]
11/08-05:40:14.317463 21728 DTL  sc Header: Content-Type: text/plain [net.cpp:2487]
11/08-05:40:14.317464 21728 DTL  sc Header: Content-Length: 1 [net.cpp:2487]
11/08-05:40:14.317465 21728 DTL  sc Header: Cache-Control: no-cache [net.cpp:2487]
11/08-05:40:14.317466 21728 DTL  sc Header: Cache-Control: no-store [net.cpp:2487]
11/08-05:40:14.317467 21728 DTL  sc Header: Pragma: no-cache [net.cpp:2487]
11/08-05:40:14.317467 21728 DTL  sc Header: Expires: 0 [net.cpp:2487]
11/08-05:40:14.317469 21728 DTL  sc Header: Access-Control-Allow-Origin: * [net.cpp:2487]
11/08-05:40:14.317470 21728 DTL  sc Header: Access-Control-Allow-Headers: Content-Type, MEGA-Chrome-Antileak [net.cpp:2487]
11/08-05:40:14.317470 21728 DTL  sc Header: Access-Control-Expose-Headers: Original-Content-Length [net.cpp:2487]
11/08-05:40:14.317471 21728 DTL  sc Header: Access-Control-Max-Age: 86400 [net.cpp:2487]
11/08-05:40:14.317483 21728 DTL  sc cURL: Connection #0 to host 66.203.125.11 left intact [net.cpp:1762]
11/08-05:40:14.317485 21728 DBG  Removing socket 1696 [net.cpp:2589]
11/08-05:40:14.317490 21728 DBG  CURLMSG_DONE with HTTP status: 200 from g.api.mega.co.nz - 66.203.125.11 [net.cpp:2170]
11/08-05:40:14.317491 21728 DBG  sc Received 1: 0 [net.cpp:2199]
11/08-05:40:14.317499 21728 DBG  SC keep-alive received [megaclient.cpp:2048]
11/08-05:40:14.317504 21728 DBG  DNS cache hit for g.api.mega.co.nz (IPv4) 66.203.125.11 [net.cpp:1919]
11/08-05:40:14.317505 21728 DBG  sc POST target URL: https://g.api.mega.co.nz/wsc/[removed]?sn=---sid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [net.cpp:1377]
11/08-05:40:14.317506 21728 DBG  sc Sending 0:  [net.cpp:1388]
11/08-05:40:14.317508 21728 DBG  Using the IP of the hostname: 66.203.125.11 [net.cpp:1408]
11/08-05:40:14.317542 21728 DBG  Next notification repeats, skipping duplicate [sync.cpp:1904]
11/08-05:40:14.317751 21728 DTL  Scanning... Remaining files: 0 [sync.cpp:1962]
11/08-05:40:14.317756 21728 DTL  Checkpath: Documents\Notes\Obsidian Vault\--\.obsidian\plugins\obsidian-daily-stats\data.json [sync.cpp:1974]
11/08-05:40:14.317767 21728 DBG  Excluded: \\?\E:\Cloud\Mega\Documents\Notes\Obsidian Vault\--\.obsidian\plugins\obsidian-daily-stats\data.json [sync.cpp:1286]
11/08-05:40:14.317769 21728 DBG  Scan queue processed, triggering a scan [megaclient.cpp:2679]
11/08-05:40:14.317771 21728 DTL  syncops: 1000 [megaclient.cpp:2736]
11/08-05:40:14.317771 21728 DBG  Running syncup on demand [megaclient.cpp:2749]
11/08-05:40:14.557052 21728 DTL  Running syncdown [megaclient.cpp:2875]
11/08-05:40:14.557055 21728 DBG  Running syncdown on demand [megaclient.cpp:2892]
11/08-05:40:15.128936 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 103 Nmtime: 1540578388 Nhandle: gCxhDQ5b [megaclient.cpp:13590]
11/08-05:40:15.128940 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:15.129078 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:15.129163 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 1393 Nmtime: 1540578360 Nhandle: RShl1ABD [megaclient.cpp:13590]
11/08-05:40:15.129164 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:15.129224 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:15.129229 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 3763 Nmtime: 1540578407 Nhandle: dThTjQwb [megaclient.cpp:13590]
11/08-05:40:15.129230 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:15.129280 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:15.129285 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 0 Nmtime: 1540578722 Nhandle: FWwRRCJA [megaclient.cpp:13590]
11/08-05:40:15.129286 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:15.129336 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:15.134431 21728 DBG  Node excluded ALA0zITA  Name: lnk{ -E961-4928-95AC-AE98451CC139}.tmp [megaclient.cpp:13426]
11/08-05:40:15.134717 21728 DBG  Node excluded EChgQZ7R  Name: lnk{ -0502-4671-9527-9D2E22E34B6A}.tmp [megaclient.cpp:13426]
11/08-05:40:15.529322 21728 DBG  Informing cURL of timeout reached for 2 at 9159 [net.cpp:725]
11/08-05:40:15.529366 21728 DTL  sc cURL: Found bundle for host 66.203.125.11: 0x1518121cbb0 [serially] [net.cpp:1762]
11/08-05:40:15.529369 21728 DTL  sc cURL: Re-using existing connection! (#0) with host 66.203.125.11 [net.cpp:1762]
11/08-05:40:15.529371 21728 DTL  sc cURL: Connected to 66.203.125.11 (66.203.125.11) port 443 (#0) [net.cpp:1762]
11/08-05:40:15.529478 21728 DBG  Adding curl socket 1696 to 1 [net.cpp:2602]
11/08-05:40:15.529520 21728 DBG  Next notification repeats, skipping duplicate [sync.cpp:1904]
[repeated x2]
11/08-05:40:15.529735 21728 DTL  Scanning... Remaining files: 0 [sync.cpp:1962]
11/08-05:40:15.529736 21728 DTL  Scanning postponed. Modification too recent [sync.cpp:1966]
11/08-05:40:15.944295 21728 DTL  Scanning... Remaining files: 0 [sync.cpp:1962]
11/08-05:40:15.944306 21728 DTL  Checkpath: Documents\Notes\Obsidian Vault\--\.obsidian\plugins\obsidian-daily-stats\data.json [sync.cpp:1974]
11/08-05:40:15.944321 21728 DBG  Excluded: \\?\E:\Cloud\Mega\Documents\Notes\Obsidian Vault\--\.obsidian\plugins\obsidian-daily-stats\data.json [sync.cpp:1286]
11/08-05:40:15.944324 21728 DBG  Scan queue processed, triggering a scan [megaclient.cpp:2679]
11/08-05:40:15.944327 21728 DTL  syncops: 1000 [megaclient.cpp:2736]
11/08-05:40:15.944328 21728 DBG  Running syncup on demand [megaclient.cpp:2749]
11/08-05:40:15.995149 20040 DBG  Ignored network interface: LAN-Verbindung 2 Flags: 36 [:-1]
11/08-05:40:15.995154 20040 DBG  Active network interface: VirtualBox Host-Only Network [:-1]
11/08-05:40:15.995158 20040 DBG  Ignored IPv6: fe80::cc69:5dd8:--:1f9f%ethernet_32773 [:-1]
11/08-05:40:15.995162 20040 DBG  IPv4: 192.168.56.1 [:-1]
11/08-05:40:15.995165 20040 DBG  Active network interface: vEthernet (Bridged) [:-1]
11/08-05:40:15.995168 20040 DBG  IPv6: 2001:9e8:2e61:da00::116 [:-1]
11/08-05:40:15.995171 20040 DBG  IPv6: 2001:9e8:2e61:da00:90e9:df4a:1152:3159 [:-1]
11/08-05:40:15.995173 20040 DBG  IPv6: 2001:9e8:2e61:da00:8dac:770:11b1:c0de [:-1]
11/08-05:40:15.995175 20040 DBG  Ignored IPv6: fe80::90e9:df4a:--:3159%ethernet_32777 [:-1]
11/08-05:40:15.995178 20040 DBG  IPv4: 192.168.178.22 [:-1]
11/08-05:40:15.995179 20040 DBG  Ignored network interface: Bluetooth-Netzwerkverbindung 2 Flags: 36 [:-1]
11/08-05:40:15.995181 20040 DBG  Active network interface: Loopback Pseudo-Interface 1 [:-1]
11/08-05:40:15.995183 20040 DBG  Ignored IPv6: ::1 [:-1]
11/08-05:40:15.995185 20040 DBG  Ignored IPv4: 127.0.0.1 [:-1]
11/08-05:40:15.995186 20040 DBG  Active network interface: vEthernet (Default Switch) [:-1]
11/08-05:40:15.995188 20040 DBG  Ignored IPv6: fe80::ad0c:cf54:51f0:638f%ethernet_32775 [:-1]
11/08-05:40:15.995191 20040 DBG  IPv4: 172.19.96.1 [:-1]
11/08-05:40:15.995209 20040 DBG  Local network adapters haven't changed [:-1]
11/08-05:40:16.182128 21728 DTL  Running syncdown [megaclient.cpp:2875]
11/08-05:40:16.182132 21728 DBG  Running syncdown on demand [megaclient.cpp:2892]
11/08-05:40:16.199285 20040 INFO Current state. Paused = 0 Indexing = 0 Waiting = 0 Syncing = 0 [:-1]
11/08-05:40:16.766274 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 103 Nmtime: 1540578388 Nhandle: gCxhDQ5b [megaclient.cpp:13590]
11/08-05:40:16.766278 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:16.766436 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:16.766566 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 1393 Nmtime: 1540578360 Nhandle: RShl1ABD [megaclient.cpp:13590]
11/08-05:40:16.766567 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:16.766653 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:16.766661 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 3763 Nmtime: 1540578407 Nhandle: dThTjQwb [megaclient.cpp:13590]
11/08-05:40:16.766662 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:16.766743 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:16.766749 21728 DBG  Unsynced remote node in syncdown: \\?\E:\Cloud\Mega\Documents\Notes\--.md Nsize: 0 Nmtime: 1540578722 Nhandle: FWwRRCJA [megaclient.cpp:13590]
11/08-05:40:16.766750 21728 DBG  doesn't have a previous localnode [megaclient.cpp:13637]
11/08-05:40:16.766820 21728 DBG  Skipping download over an unscanned file/folder, or the file/folder is not to be synced (special attributes) [megaclient.cpp:13654]
11/08-05:40:16.772155 21728 DBG  Node excluded ALA0zITA  Name: lnk{15E698B7-E961-4928-95AC-AE98451CC139}.tmp [megaclient.cpp:13426]
11/08-05:40:16.772458 21728 DBG  Node excluded EChgQZ7R  Name: lnk{8DD5D70F-0502-4671-9527-9D2E22E34B6A}.tmp [megaclient.cpp:13426]
11/08-05:40:17.167654 21728 DBG  Next notification repeats, skipping duplicate [sync.cpp:1904]
11/08-05:40:17.167873 21728 DTL  Scanning... Remaining files: 0 [sync.cpp:1962]
11/08-05:40:17.167878 21728 DTL  Checkpath: Documents\Notes\Obsidian Vault\--.json [sync.cpp:1974]
11/08-05:40:17.167888 21728 DBG  Excluded: \\?\E:\Cloud\Mega\Documents\Notes\Obsidian Vault\--.json [sync.cpp:1286]
11/08-05:40:17.167891 217

**Comment by mattw-mega** [comment]
yes it looks like MEGAsync is woken up by the filesystem notifications of changes Obsidian is making.   But then it's also having trouble with the file E:\Cloud\Mega\Documents\Notes--.md.   Maybe that is part of your exclusion set or maybe the local copy of the file has special attributes, but MEGAsync is not able to sync it.    If it doesn't break anything, you could remove the cloud version of that file and it won't try to process that one anymore (make sure to back up your local copy of it in case it gets removed but turns out to be needed)  thanks

**Comment by mattw-mega** [comment]
btw Obsidian is making changes, not to your files but to its own:  ...\obsidian-daily-stats\data.json.  Maybe try excluding that folder obsidian-daily-stats.  thanks

**Comment by brightknight2** [comment]
Ok, first off, thank you for bearing with me. I was really frustrated and it was quite hard to figure out what is going on. But Thanks

**Comment by brightknight2** [comment]
t
