### ISSUE TITLE
Errors on cloning repository, hash 8b0f09ef19a06b96767b88d8d55c2ccf74106f23 does not exist

### ISSUE THREAD

**Issue by Peter4487** [meganz/MEGAsync#637]
Hi,
I'm trying to build per the build instructions on Debian.
Upon running:
`git clone --recursive https://github.com/meganz/MEGAsync.git`
I see
`fatal: remote error: upload-pack: not our ref 8b0f09ef19a06b96767b88d8d55c2ccf74106f23
Fetched in submodule path 'src/MEGASync/mega', but it did not contain 8b0f09ef19a06b96767b88d8d55c2ccf74106f23. Direct fetching of that commit failed.
`

If I continue on regardless I see:
`./configure: line 76: ./MEGASync/mega/contrib/build_sdk.sh: No such file or directory
./configure: line 82: ./contrib/build_sdk.sh: No such file or directory
ln: failed to create symbolic link '/the/local/directory/MEGAsync/src/MEGASync/mega/bindings/qt/3rdparty/libs': No such file or directory`

Which has been reported before in #515 , #481, #190, #114, #56

I assume this is due to the commit that hash matches not being there for some reason, but I'm not sure why or how a commit could disappear while leaving the hash. What's up?

**Comment by polmr** [comment]
Hi @Peter4487 , try that again, it should work now. Thanks for reporting it!
