### ISSUE TITLE
file downloading order ?  move up or down a specific file?

### ISSUE THREAD

**Issue by blackholeearth** [meganz/MEGAsync#64]
please add a  ordering  option  for the files to be downloaded .

```
---------------------------------------------
 [move up]  [move down]
---------------------------------------------
movie1.mp4    -- [ %40 ][ downloading ]
movie5.mp4
movie2.mp4
movie3.mp4 
movie4.mp4
---------------------------------------------
```

while downloading 1 single file is  okey . but when whe have more than 1 files, it is unmanagable. 
look at the movie5.mp4 is at 2nd in queue. i want to move it to last place . please please add this functionality . it will be really good.

**Comment by javiserrano** [comment]
MEGAsync 3.0 (released today) includes a transfer manager that allows to do it.
You can download it in our official web:
https://mega.nz/sync

Existing installations will be updated during the next days.

**Comment by blackholeearth** [comment]
thank you. now i dont need other unofficial mega downloader
