### ISSUE TITLE
[Bug] Hidden files uploaded when excluded in settings (default config) in Fedora 35

### ISSUE THREAD

**Issue by Barraguesh** [meganz/MEGAsync#643]
Every time I upgrade to a new Fedora version, I clean install it. This time I upgraded to Fedora 35 and after installing Mega, I see my hidden files of the home folder are being uploaded (folders and files, as shown in the screenshots), without even touching the settings, just from a clean installation of MegaSYNC.

I double-checked, and I have the ".*" exclusion to prevent this (as it is by default), so I guess this has to be a bug. This has happened 2 times already (I installed F35 2 times to test this).

Screenshot of folders on the Cloud Drive: https://imgur.com/a/IE1F9xR
Screenshot of the settings on desktop: https://imgur.com/a/mgaXMuA

**Comment by polmr** [comment]
Hi @Barraguesh , bear in mind that the exclusion list refers only to synchronizations. 
For manual uploads, those exclusions are not enforced.

**Comment by Barraguesh** [comment]
I did not manually upload anything. I installed the sync client and I saw stuff being uploaded, it was a fresh install so I didn't really know what there was, and then I saw the hidden files.

**Comment by Barraguesh** [comment]
@polmr deleting the files in the cloud doesn't delete them from the system anymore, and they're no longer uploaded by MegaSync. Might have been a Fedora error in the file system or something, but glad this doesn't happen anymore. Closing the issue.

**Comment by polmr** [comment]
Thanks @Barraguesh !
