### ISSUE TITLE
v4.6.1.0 Linux release

### ISSUE THREAD

**Issue by tim77** [meganz/MEGAsync#647]
Is there any reason why Linux version [tagged](https://github.com/meganz/MEGAsync/releases/tag/v4.6.1.0_Linux), but [not released](https://github.com/meganz/MEGAsync/releases)? Thanks in advance.

**Comment by polmr** [comment]
It's coming soon. Please, be patient ;-). Codebase shall be that of the tag.

**Comment by tim77** [comment]
@polmr thanks! That's why i am asking and not rushing with updates. :)

**Comment by Perkolator** [comment]
So where is it? I see v4.6.2.0_OSX out now and previous linux release is still missing! And can't you really do proper changelogs for every release?! You just copy paste changelog to several releases, what is the point of that? How should users know what has actually changed between releases? It's unbelievable that you can't see anything wrong with what you're doing with the changelogs.

**Comment by tim77** [comment]
[4.6.3.0_Linux](https://github.com/meganz/MEGAsync/releases/tag/v4.6.3.0_Linux) released. @polmr thank you!
