### ISSUE TITLE
Wrong string for versioning feature setting

### ISSUE THREAD

**Issue by wizard86pz** [meganz/MEGAsync#648]
In the macOS MEGASync app, the check box about the file versioning feature uses a wrong string _"Disabled file versioning"_:

- when the versioning feature is **enabled**, the check box is **checked**;
- otherwise, when the versioning feature is **disabled**, the check box is **unchecked**.

Conceptually, when the feature is enabled, the check box has to be unchecked if the string used is _"Disabled file versioning"_.
When the feature is disabled, the check box has to be checked if the string used is _"Disabled file versioning"_

Example: the feature is enabled on my account (checked on iOS app and web-app), but on macOS app this is what I see:
![image](https://user-images.githubusercontent.com/36189429/142739465-f5804ce6-e4ea-4699-9c19-35779ed7533f.png)

Latest MEGASync app v4.6.1.0.

**Comment by vtmateos** [comment]
Thanks for pointing that out. We will review and fix in next versions. 👍
