### ISSUE TITLE
Future request .ignore file

### ISSUE THREAD

**Issue by nukadelic** [meganz/MEGAsync#654]
I know its been posted before many times, all I'm asking is a text file that would ignore local folders only.

For example a two line text file like the following :
```
Library
Tmp
```
That would ignore syncing those folders when placed at the project location. So if the .ignore file would be located at `/Mega/Project1/.ignore` - it would prevent the following path from syncing :
```
/Mega/Project1/Library
/Mega/Project1/Tmp
```

Cheers

**Comment by mattw-mega** [comment]
Hi @nukadelic , I think you are in the other thread already but for the benefit of anyone else looking here, please refer to https://github.com/meganz/MEGAsync/issues/770 thanks

**Comment by nukadelic** [comment]
Thank you
