### ISSUE TITLE
API_EAGAIN [-3] for a week 

### ISSUE THREAD

**Issue by jilienlafillette** [meganz/MEGAsync#655]
hi , i wanted to log in into my account and im getting [-3] API_EAGAIN for more then an hour , retries and the server keep responsing -3 , it has been now a week everyday i try to log in with no success  , i contacted support with no success of solving the problem , i tried everything all browsers ,ios,android,megaCMD , still getting -3 , i really need to access my files , im stuck , please do something

**Comment by sakethv-mega** [comment]
Hello, can you please reply back with the support ticket so that we can follow it up? Thank you.

**Comment by jilienlafillette** [comment]
Ticket ID: WGC-576-20012

thanks

**Comment by jilienlafillette** [comment]
@sakethv-mega Ticket ID: WGC-576-20012

thanks

**Comment by sakethv-mega** [comment]
Hi, based on our correspondence on the support ticket you have raised, we believe your issue has been resolved. We are closing this issue now. Thank you.
