### ISSUE TITLE
Your sync “name” can’t be enabled. Reason: Local path not available

### ISSUE THREAD

**Issue by s0lst1ce** [meganz/MEGAsync#666]
Hello,
I've recently been having issues with megasync (version 4.6.1 and 4.5.x) on Arch Linux. For some reason after a reboot the syncs were disabled and I've been unable to activate them once again because I get the error: `Your sync “name” can’t be enabled. Reason: Local path not available`.
This happens for all my syncs, even though the paths do exist and are even open in read/write mode.
How can I fix this?

**Comment by zweq** [comment]
I'm suffering from the same issue.
When in Settings -> Sync choosing "Show in folder", the following error shows up:

Failed to open URI.
Operation not supported.
file:a/Mega

Mega is the correct path, I don't know where the "a/" prefix comes from.

**Comment by s0lst1ce** [comment]
I opened a ticket to mega support about this. They recommended reloading the account and forcing a full scan. Neither did anything for me but maybe it'd help you @zweq ? If you try it please share your results.

**Comment by s0lst1ce** [comment]
Completely deleting megasync, including config files and re-installing everything ended up working out for me.
