### ISSUE TITLE
Apple M1 processor support in released binaries

### ISSUE THREAD

**Issue by larstobi** [meganz/MEGAsync#673]
The MEGAsync app can only run on emulation with Rosetta 2 on the Macs and Macbooks with the M1 processor. Please compile MEGAsync to native code for the M1 processor and publish the binaries. Thanks! :-)

**Comment by angelds-mega** [comment]
Hello, 
Our developers are already working on it. There is no exact date yet. 
We aim to release the native m1 app before the 1st half of this year.

**Comment by 545ch4** [comment]
Any updates? On MacOS 12.x it seems to be quite buggy: #668

I would like to provide any help, but I am unable to build the client based on the procedure given at README...

**Comment by webdev69420** [comment]
What about now? Any updates?

**Comment by kieugiahung** [comment]
It's long time to wait... :(

**Comment by zliebersbach** [comment]
@angelds-mega The first half of the year has now passed, is there an updated release date for this?

**Comment by prakashvis** [comment]
Hello devs, any updates on native m1 support? Planning to hop on a subscription and this is the only factor I'm hesitant about.

**Comment by webdev69420** [comment]
> Hello devs, any updates on native m1 support? Planning to hop on a subscription and this is the only factor I'm hesitant about.

It's been 2 years since the first M1 MacBook has been released and there is still no news about Apple Silicon support by MEGA so I wouldn't count on it. Sucks because MEGA is a pretty nice cloud! I use it on my 2020 M1 MacBook Air with Rosetta, it works but I feel like it's draining my battery quite a bit...

**Comment by webdev69420** [comment]
@larstobi it seems that MEGAsync v4.7.2 added Apple Silicon support.
The update should be available automatically, but it's also downloadable here if needed:

- [https://github.com/meganz/MEGAsync/releases/tag/v4.7.2.0_OSX](https://github.com/meganz/MEGAsync/releases/tag/v4.7.2.0_OSX)

Thanks MEGA for finally adding Apple Silicon support! This issue can be closed now.

**Comment by larstobi** [comment]
Excellent! I have installed it, and it shows running as "Type" "Apple" in Activiy Monitor. 

I tried to upgrade the existing one, but then I just got a new Intel version, so I deleted mega, downloaded the new one from the link above, selected Apple Silicon, and installed that.

**Comment by vardecab** [comment]
> Excellent! I have installed it, and it shows running as "Type" "Apple" in Activiy Monitor.
> 
> I tried to upgrade the existing one, but then I just got a new Intel version, so I deleted mega, downloaded the new one from the link above, selected Apple Silicon, and installed that.

Looks like uninstalling is not necessary. I downloaded Apple one from MEGA website and installed on top of Intel one I already had and it seems to work. I had "Kind" = "Intel" before and now "Kind" = "Apple" in Activity Monitor.

**Comment by sataset** [comment]
Updated Cask code in homebrew.
Now you can install Apple Silicon version from there.
```
brew install --cask megasync
```

P.S. Do not the behaviour on upgrade. Suggesting to reinstall it.
