### ISSUE TITLE
Option to inhibit system sleep

### ISSUE THREAD

**Issue by sanjaylord** [meganz/MEGAsync#675]
Hello,

Please include a checkbox within the app to prevent system from entering sleep when a transfer or sync is happening. I've to manually change power settings each time whenever a big transfer is taking place from windows power settings otherwise the system goes to sleep mode.

Thanks.

**Comment by angelds-mega** [comment]
Hello, we pass on your feedback to our development team. 
We appreciate all feedback and are working to improve and integrate new features with this feedback in mind. Thank you.

**Comment by sanjaylord** [comment]
> Hello, we pass on your feedback to our development team. We appreciate all feedback and are working to improve and integrate new features with this feedback in mind. Thank you.

Please do ensure this feature gets added because often times I have to schedule transfers in the night and leaving the PC powered on till the morning **wastes significant energy** when an option within the client to inhibit sleep could've solved this by allowing the PC to go to sleep right after the transfer is complete.

Some clients such as Jdownloader2 & qBittorrent implement this and it works great. I hope the team behind the MEGAsync application can also incorporate it in a future release.

![screenshot_2195](https://user-images.githubusercontent.com/60788875/155413102-64282241-55dd-4148-b706-81ac29419c65.png)

![screenshot_2196](https://user-images.githubusercontent.com/60788875/155413134-619435ea-3640-4d7d-9c63-3f146babf5b6.png)

**Comment by angelds-mega** [comment]
Noted that. Thank you.
