### ISSUE TITLE
MEGAsync.exe deleted by Kaspersky

### ISSUE THREAD

**Issue by JCVanderbilt** [meganz/MEGAsync#693]
MEGAsync.exe was deleted by Kaspersky this morning for containing Trojan.Win32.Generic.

Event: Malicious object detected
Application: MEGAsync
User: <me>
User type: Active user
Component: System Watcher
Result description: Detected
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Threat level: High
Object type: Process
Object path: c:\users\jcvanderbilt\appdata\local\megasync
Object name: megasync.exe
Reason: Databases
Databases release date: Yesterday, 3/20/2022 4:21:00 AM

**Comment by angelds-mega** [comment]
Hello. Some antivirus programs (such as Avast, AVG, Eset, G Data, Kaspersky, Bitdefender, BullGuard and Comodo) interfere with MEGA but you can set an exception/exclusion.

**Comment by angelds-mega** [comment]
Hello.

Just touching base. 

Will you be able to rescan, and/or if you could  downloaded it from Mega or from somewhere else? 
What version of MEGAsync he has and what type of the Kaspersky A/V program ? And what version of WIN?
![Uploading Screenshot 2022-04-01 at 4.02.11 PM.png…]()
