### ISSUE TITLE
Unable to launch MEGAsync on Fedora 36 KDE

### ISSUE THREAD

**Issue by DonKatsu** [meganz/MEGAsync#707]
Attempting to launch through the console generates the following message.

```
$ megasync 
megasync: symbol lookup error: /lib64/libfreeimage.so.3: undefined symbol: _TIFFDataSize, version LIBTIFF_4.0
```

**Comment by BaBBa71** [comment]
Same problem for me.
SOLUTION:
I suppose you have: 

`megasync                   x86_64                  4.6.6.0-2.fc36                             @rpmfusion-nonfree `

You must manual install megasync-4.6.7-2.1.x86_64 or newer, because the rpmfusion-nonfree package isn't compatible with last Fedora 36 update release on June 2022.

**Comment by Zetaphor** [comment]
@BaBBa71 Are you installing from source? I've tried downloading the latest rpm from the website but I'm getting the following:

>  - nothing provides libraw.so.19()(64bit) needed by megasync-4.6.7-2.1.x86_64

**Comment by BaBBa71** [comment]
Yes of course. You can see all packages dependency with `sudo dnf deplist megasync-Fedora_36.x86_64.rpm` 
For libraw.so.19 check if you have the LibRaw (case sensitive) in the system. In my last update I have the 0.20.2 version

`Installed Packages
Name         : LibRaw
Version      : 0.20.2
Release      : 5.fc36
Architecture : x86_64
Size         : 2.3 M
Source       : LibRaw-0.20.2-5.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Library for reading RAW files obtained from digital photo cameras
URL          : http://www.libraw.org
License      : BSD and (CDDL-1.0 or LGPLv2)
Description  : LibRaw is a library for reading RAW files obtained from digital photo
             : cameras (CRW/CR2, NEF, RAF, DNG, and others).
             : 
             : LibRaw is based on the source codes of the dcraw utility, where part of
             : drawbacks have already been eliminated and part will be fixed in future.
`

**Comment by Zetaphor** [comment]
@BaBBa71 
I didn't scroll down to see that there was a Fedora 36 version, thanks!

**Comment by BaBBa71** [comment]
> @BaBBa71 I didn't scroll down to see that there was a Fedora 36 version, thanks!

It's my pleasure!

**Comment by DoodlesEpic** [comment]
This problem is related to the 4.4.0 update on libtiff
https://bugzilla.redhat.com/show_bug.cgi?id=2099985

You may downgrade to 4.3.0 to fix the issue that megasync is throwing, and then the version on rpm fusion will work until an update arrives to the repo version that fixes it:

```bash
sudo dnf downgrade libtiff
```

**Comment by DonKatsu** [comment]
Yesterday's batch of Fedora updates seems to have resolved the issue.
