### ISSUE TITLE
Pausing sync doesn't pause it completely

### ISSUE THREAD

**Issue by awvalenti** [meganz/MEGAsync#708]
1. On computer 1 (c1) MEGA Sync > Upload/download manager > Pause
2. On computer 2 (c2):
    1. Create or remove a folder. It's still updated on c1.
    2. Change a file. It's deleted on c1 until Resume is clicked

Is this behavior expected? If so, I suggest a text is added below the Pause button explaining: "Pausing only pauses file contents download/upload. To fully pause MEGA Sync, please close the app via tray icon" or something like that.

**Comment by voc-mega** [comment]
Hello,
We would like to further study your scenario.
Would you please be able to send us a video of the issue you are experiencing so we can have a look and let you know if it is expected or not?
You can do so by emailing support@mega.nz for more privacy.
Thank you very much and we will be looking forward for your reply.

**Comment by awvalenti** [comment]
Hello, thanks for the interest and quick reply. Sorry for my delay. Just uploaded the video to the informed e-mail. Cheers!

**Comment by awvalenti** [comment]
I believe the correct behavior would be to completely stop sync, as if MEGAsync was closed. No changes in local copy, neither creating folders or deleting/changing files.

It may worth trying renamings as well.

**Comment by jx-mega** [comment]
Hi again, we have responded to your email in ticket ID: [QIO-326-10462] please continue our conversation from there.

**Comment by awvalenti** [comment]
So, the conclusion is that pausing sync only serves to reduce internet data consumption. If you really want to completely stop sync, the easiest way is to close the app MEGAsync for a while. Thanks for the e-mail with detailed explanations!
