### ISSUE TITLE
MEGAsync xfce4 implementation

### ISSUE THREAD

**Issue by WyRe** [meganz/MEGAsync#71]
I would like a few of things:

**First**: There will be the same integration of megasync to Thunar what there is with Nautilus? (with sync status icons to folders and files)

**Two**: I've got installed Nautilus in my XFCE4 environment and nautilus-megasync but I cannot get the same integration as in Genome. In fact, nautilus-megasync doesn't work in XFCE4, Why is this? Maybe I need some particular dependency? 

Thank you! :P

**Comment by polmr** [comment]
There was a pilot project for a similar extension for Thunar. We'll eventually continue that one. Nautilus extension is working fine in XFCE (naturally... in nautilus, you need to use nautilus as a file browser). Notice that after installing nautilus-megasync you need restart nautilus (ensure there is no nautilus process running before). Here's an sreenshot in Xubuntu 16.04:
![Screenshot nautilus-extension XFCE4](https://cloud.githubusercontent.com/assets/10722503/22967324/4f8cf83e-f366-11e6-9930-92718960bb60.png)

**Comment by WyRe** [comment]
I haven't got that behaviour with my xfce4 version and nautilus-megasync into your Mega repo for Arch, the sync icons status either, 

![captura de pantalla de 2017-02-15 11-47-47](https://cloud.githubusercontent.com/assets/4059108/22971291/7d3c6e36-f375-11e6-9e22-b12cb842cd66.png)

However, Thunar extensions works properly, I hope sync icons in a future :) 

![captura de pantalla de 2017-02-15 11-47-40](https://cloud.githubusercontent.com/assets/4059108/22971283/7507357a-f375-11e6-8ae1-b9e6183a114b.png)
![captura de pantalla de 2017-02-15 11-47-34](https://cloud.githubusercontent.com/assets/4059108/22971286/7a47237e-f375-11e6-8a9c-632daabf6dda.png)

**Comment by WyRe** [comment]
I've noticed this package https://aur.archlinux.org/packages/nautilus-megasync/ works better than official in the MEGA repos:

![captura de pantalla de 2017-02-15 12-17-01](https://cloud.githubusercontent.com/assets/4059108/22972208/fe1e7ad2-f378-11e6-9ac4-5aae06ac825b.png)

**Comment by polmr** [comment]
@WyRe nautilus-megasync is broken for Arch Linux (in the end it installs an empty package). Thanks for reporting, it'll be fixed asap.

**Comment by WyRe** [comment]
Anyway, te people has included them into AUR repos, and with good popularity, so ... maybe is possible can be included into officials :D

https://aur.archlinux.org/packages/?O=0&SeB=nd&K=megasync&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by polmr** [comment]
nautilus-megasync is now restablished at the official repo. Update with pacman -Sy && pacman -S nautilus-megasync, or download it (64 bits) from: https://mega.nz/linux/MEGAsync/Arch_Extra/x86_64/nautilus-megasync-x86_64.pkg.tar.xz. The direct download link at https://mega.nz/#sync is temporarily broken, it'll be fixed soon.
