### ISSUE TITLE
Add "System.IsPinnedToNamespaceTree" on Windows

### ISSUE THREAD

**Issue by naseweis520** [meganz/MEGAsync#72]
Hi.
Many other cloud providers like Dropbox, Microsoft or Adobe add a shortcut leading to the cloud root directory to the Windows Explorer sidebar, which also can be expanded in order to list the contents of that folder without actually navigating into that folder. An other effect of that is, that one can navigate the directory by simply entering the name of the service, so in this case "_MEGAsync_", instead of entering the full path (e.g. _%UserProfile%\MEGAsync_) I think that this could be very handy for MEGAsync too, though, I'd also suggest to allow the user to toggle this function in the settings.

**Comment by ievgen-baida** [comment]
+1

> I'd also suggest to allow the user to toggle this feature in Settings.
For this part as well.

**Comment by polmr** [comment]
The thing is... unlike other cloud providers, MEGAsync supports synching more than one folder. Offering pinning those folder from within the application might be quite messy. In any case, Windows already allows you to easily pin whatever you want to Quick Access: https://support.microsoft.com/en-us/instantanswers/e4c6d890-9957-4263-a89a-79f93fa68373/pin-remove-and-customize-in-quick-access

**Comment by polmr** [comment]
I withdraw that: this is already being accounted for, it's likely to appear in the next release of megasync.

**Comment by eric-tucker** [comment]
Why oh why did you ever request this?  This feature sucks. If you want a pin, add to quick access. Sigh.

**Comment by naseweis520** [comment]
@eric-tucker Because it's a feature I like to have. That simple.
It's not even hard to remove it by yourself in the registry. And as vtmateos commented in #91 it can be easily disabled. So stop being so grumpy.

**Comment by eric-tucker** [comment]
"It's not even hard to remove it by yourself in the registry."

You realize the irony in this statement, right?

The option to remove is not in settings.  Hence, it's not clear how to get rid of these.  The feature should have been something that could be disabled in settings.

My issue is with the implementation and rollout, and flash backs to Dropbox having this feature with NO WAY to disable it, even registry hacks being overwritten at boot.  Also, that it puts a locked pin for every single folder you have synced (if you're not syncing just the root of your cloud drive) is horrible.
