### ISSUE TITLE
Why does MegaSync update the new file by the old one?

### ISSUE THREAD

**Issue by Talismanch1k** [meganz/MEGAsync#720]
Hello everyone!
So my issue is when i'm trying to edit existing file in my Obsidian storage on Windows, my file returns to older versions without changes (because MegaSync download older versions of file from cloud). I tried turn off MegaSync then edit file, after that turn on MegaSync and it's still returns my file to old version. But why? It's so strange. The edited file weighs more, and MegaSync just download old version from cloud. I have no problems on linux with syncing but there is on windows. Can you also throw off compiled version 4.6.7, there may be a problem in the current version. Also, this difference may be due to file permissions in Linux? Any ideas? 

Linux Manjaro:
Obsidian: v0.15.9
MegaSync: 4.6.7

Windows 11:
Obsidian: v0.15.9
MegaSync: 4.6.8

**Comment by jx-mega** [comment]
This is interesting, please email us at support@mega.nz from your MEGA account email address explaining the issue and we will be investigating from there.

**Comment by Talismanch1k** [comment]
I fixed this problem. But I still don't understand why this is so. I will leave here a solution that helped me for future generations. It turns out that I opened the wrong folder in Obsidian. If you open the root folder where you created files, your folders in Obsidian, then everything is fine, but if you open the parent folder, MEGAsync starts downloading the old version of the file from the cloud all the time. I attached some pics to show you.
If you open your Obsidian Vault here MegaSync downloading old version of file from cloud.
![image](https://user-images.githubusercontent.com/107954148/185217918-548db86d-95bc-4e26-ab65-5e1c7ee66be3.png)
But if you open your vault here everything is fine!
![image](https://user-images.githubusercontent.com/107954148/185218163-957e71b4-8577-48d6-82e9-c979d8ffce9d.png)

.obsidian files don't affect in any way. I checked it.
If someone knows why this is happening, please tell me.
