### ISSUE TITLE
KDE Plasma Tray Icon White On White

### ISSUE THREAD

**Issue by fleamour** [meganz/MEGAsync#721]
Under openSUSE Tumbleweed KDE Wayland, the MEGAsync tray applet is not visible, certainly not red like yonder year. It been this way for roughly the last three releases.

**Comment by gbcox** [comment]
I using Fedora, and haven't noticed this issue.  I seems that possible some settings somehow got corrupted on your system.  You might give this a try: 

1.     Open the app you are wanting to fix (Vivaldi, Firefox Nightly, HandBrake, etc.)
2.     Add new kwin rule with Alt+F3 → More Actions → Configure Special Application Settings → Add Property → Desktop file name →
3.     Enter the desktop file name without extension (e.g. chromium-browser.desktop, fr.handbrake.ghb.desktop, vivaldi-stable.desktop, etc.)

More information can be found here:  https://www.reddit.com/r/kde/comments/tzw738/fix_generic_wayland_icon_in_task_manager_for/

    If you are using standard package, check name in “/usr/share/applications/”
    if you are using flatpak package, check name in “var/lib/flatpak/exports/share/applications/”

**Comment by fleamour** [comment]
No worky. Uninstalling native rpm then reinstalling no worky either. However it did not purge settings either as still signed in when reinstall through YaST. Maybe I should try Flatpak?

**Comment by gbcox** [comment]
Yeah, I didn't think Flatpak would work.  My guess is something got messed up or corrupted in your Plasma/KDE settings.  I haven't seen this problem on Fedora and I can't imagine that SUSE would be doing something in their build to cause this.  Sorry the suggestion I posted didn't work for you.  It does work to eliminate the annoying default "W" wayland icon though.

![Screenshot_20220817_131817](https://user-images.githubusercontent.com/4543019/185235770-479cf97b-957d-40b9-8810-6c7f9e9d1077.png)

**Comment by fleamour** [comment]
OK, I do run some non standard repos. With dependency switches, I could see some non standard bugs creep in over time. I guess the allure of forever rolling maybe a myth & maybe I should nuke & pave. QA can't catch my edge cases after all.

**Comment by fleamour** [comment]
After fresh install it is my custom Icon theme that was missing MEGAsync icon.

**Comment by gbcox** [comment]
> After fresh install it is my custom Icon theme that was missing MEGAsync icon. However Libre Office Writer does not crash when opening a file anymore. I figure years of vendor switching results in a "custom" setup franken beast.

Yeah, unfortunately, things get corrupted sometimes.  It would be nice if Plasma would have an easy option to set all settings to default and wipe out any corrupted files.  I've had to do a fresh install to correct issues before, it's a drag.  Anyway, glad you could get the issue resolved.  ;-)

**Comment by fleamour** [comment]
So the default Breeze icon set will display correct red tray icon, using Numix-Circle or Papirus icons results in ghost icon:

[https://ibb.co/p0cqSXm](url)
