### ISSUE TITLE
Cli commands

### ISSUE THREAD

**Issue by extensionsapp** [meganz/MEGAsync#73]
Hello.

How to install on Debian 8
And synchronized folder
`/home/myfiles -> (mega)/myfiles`

Where information about the cli commands?

**Comment by polmr** [comment]
You need to download MEGAsync from https://mega.nz/sync
You can browse through here to learn how to use it (included synchronization): https://mega.nz/help/client/megasync/getting-started
If you are willing to use a command line interface to interact with mega you might want to read this: https://github.com/meganz/sdk/tree/master/examples/megacmd

**Comment by extensionsapp** [comment]
Ok, I install, I see commands, but how to use?

<img width="453" alt="sync" src="https://cloud.githubusercontent.com/assets/8192379/23460738/723e4cbe-fe8f-11e6-9042-4a344c0f11b9.png">

**Comment by polmr** [comment]
Please, read: https://github.com/meganz/sdk/blob/master/examples/megacmd/README.md (specially the part specific for your platform -linux-)
You need to launch the interactive console (mega-cmd). You can interact with it typing your commands. Type "help" to begin with. All the other commands (mega-*) can be run from another terminal once the interactive console is running.

**Comment by extensionsapp** [comment]
@polmr It would be nice if you did more examples of usage.

I have a folder in the Mega - local
I have a folder on VPS - server

How can I synchronize them?

<img width="466" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/8192379/23505144/10e1d352-ff4b-11e6-88c8-e7503af1b319.png">

**Comment by polmr** [comment]
You can get the info of the usage of a command by typing "command --help". In this case "sync --help"

In the end you can do it with:
sync /path/to/local/folder /path/to/remote/folder

In your case:
sync /home/myfiles /myfiles

In case the remote folder does not exist you might want to create it with:
mkdir /myfiles

We will eventually create a help page with an usage tutorial with several examples, so any question/suggestions will be more than welcome.

**Comment by extensionsapp** [comment]
@polmr Thanks for the help.

**Comment by extensionsapp** [comment]
However, when I go quit `mega-cmd`, synchronization stops. How to make it work in the background?

**Comment by polmr** [comment]
You can execute mega-cmd in the background. Do it with 
nohup mega-cmd &

The nohup is required in the current version (it'll be fixed in a new release, so that you can run it in the background normally with "mega-cmd &" )
