### ISSUE TITLE
Feature Request, FUSE filesystem

### ISSUE THREAD

**Issue by chmercesmoreira** [meganz/MEGAsync#74]
Hello, I'd like to know if there is any plans, by the development team, to develop a way to mount a virtual file system using Fuse, currently I'm using this program: https://github.com/matteoserva/MegaFuse, but it is not very stable.

The reason why I'm asking this is because I want to make my Plex Media Server "watch" media stored on my virtual driver on MEGA and stream my files every time I request them.

An official fuse implementation would be awesome, none of the other cloud providers offer such feature and it will surely be a great advantage over them.

**Comment by chmercesmoreira** [comment]
Ok, no answer after 1 week, so I presume that there is no plan to release this feature.

**Comment by vtmateos** [comment]
Hello, 
Apologies for the late reply. Actually, we have some examples of our SDK based on FUSE (Linux) and Dokan (Windows). Those drivers are read-only, but allows some write operations like creation of folder, moves, etc. This isn't an application for final users, please use it for testing and developing purposes only.

Windows:
https://github.com/meganz/sdk/tree/e8e66e9f030febfb35c9e4dd503d69091e28fc04/examples/win32

Linux:
https://github.com/meganz/sdk/tree/e8e66e9f030febfb35c9e4dd503d69091e28fc04/examples/linux

Kind regards.

**Comment by chmercesmoreira** [comment]
Thank you for your answer. I was able to build and run megafuse, and it is working properly.
I have a doubt that I didn't find reading the README file:

- How do I pass fuse mount options to megafuse? Example: _allow_other, uid=1000, gid=1000_. I want to know this because I'm unable to get access to the mounted folder without these mount options, at lease when I am mounting automatically using /etc/fstab:

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>                                             <mount point>               <type>    <options>                             <dump>  <pass>
/usr/bin/MegaFuseWrapper.sh                                 /opt/plexmediaserver/MEGA   fuse      allow_other,uid=1000,gid=1000         0       0
```

And the script _/usr/bin/MegaFuseWrapper.sh_:
```
#!/bin/bash

megafuse ***** ***** /opt/plexmediaserver/MEGA / >/dev/null 2>&1 &
```
When mounting manually I can see the folder if I mount it in my user home, but if I try to mount outside my home folder I need to run the command using _sudo_:
```
sudo megafuse ***** ***** /opt/plexmediaserver/MEGA /
```
and in the end I get the same problem when mounting automatically, unless I change the folder/file permissions using _chown_ but this is definitely not safe.

So I think that it must have any way to pass fuse mount options to the megafuse binary, this unofficial fuse filesystem for mega: https://github.com/matteoserva/MegaFuse has an option to pass parameters:

> you can pass additional options to the fuse module via the command line option -f. example:
./MegaFuse -f -o allow_other -o uid=1000
