### ISSUE TITLE
MEGAsync doesn't work with the latest Arch Linux updates

### ISSUE THREAD

**Issue by guipan** [meganz/MEGAsync#753]
There is problem launching MEGAsync with an updated version of Arch Linux. I confirm that also other people have the same problem.
The error launching the app is this one:
`megasync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

I hope that you will solve the problem as soon as possible. Thanks a lot.

**Comment by kdevg0** [comment]
> There is problem launching MEGAsync with an updated version of Arch Linux. I confirm that also other people have the same problem. The error launching the app is this one: `megasync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
> 
> I hope that you will solve the problem as soon as possible. Thanks a lot.




Seems like an openssl issue. Downgrading to version 1.1 will make it work. However I'll go ahead and upgrade to openssl 3.0 again. Will wait till they offically release a new version of mega that uses 3.0 version of openssl.

**Comment by guipan** [comment]
> > There is problem launching MEGAsync with an updated version of Arch Linux. I confirm that also other people have the same problem. The error launching the app is this one: `megasync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
> > I hope that you will solve the problem as soon as possible. Thanks a lot.
> 
> Seems like an openssl issue. Downgrading to version 1.1 will make it work. However I'll go ahead and upgrade to openssl 3.0 again. Will wait till they offically release a new version of mega that uses 3.0 version of openssl.

I don't think is so simple to downgrade to version 1.1 of openssl, because the downgrade interrupts many dependencies, and is impossible.
I think it's better to wait for a new MEGAsync release, instead.

**Comment by kdevg0** [comment]
> > > There is problem launching MEGAsync with an updated version of Arch Linux. I confirm that also other people have the same problem. The error launching the app is this one: `megasync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
> > > I hope that you will solve the problem as soon as possible. Thanks a lot.
> > 
> > 
> > Seems like an openssl issue. Downgrading to version 1.1 will make it work. However I'll go ahead and upgrade to openssl 3.0 again. Will wait till they offically release a new version of mega that uses 3.0 version of openssl.
> 
> I don't think is so simple to downgrade to version 1.1 of openssl, because the downgrade interrupts many dependencies, and is impossible. I think it's better to wait for a new MEGAsync release, instead.

Well, I did downgrade before posting here. And it did work. However after opening the megasync app(with notification on  top bar), I upgraded again to the latest version.

**Comment by guipan** [comment]
Ok, the problem seems to be solved by installing the package openssl-1.1 
Thanks.
