### ISSUE TITLE
Windows 10/11 process priority

### ISSUE THREAD

**Issue by stalker780** [meganz/MEGAsync#762]
I use Win10 and i7-13700k CPU. It has Production and Efficient cores.

Often MegaSync performs some background tasks with about 4-5% CPU usage.
But it always uses Performance cores which are hot. This may take hours and CPU temperature can easily reach 75C. I have 75C limit in my BIOS settings. Other CPUs can reach up to 100C.

![image](https://user-images.githubusercontent.com/6297070/205515379-63b82d4f-0fae-4366-b004-58640a7e09b7.png)

After I manually select process priority Below normal, Win10 uses Efficient cores instead of Performance. This significantly drops CPU and MB temperatures. Up to 10-20C difference.
![image](https://user-images.githubusercontent.com/6297070/205515331-0b195608-74c1-464a-9d01-fd72b041e609.png)

![image](https://user-images.githubusercontent.com/6297070/205515388-29171154-9533-4f0e-baaa-e272cbf7b1c8.png)

I don't know. Is it possible to make an option in app settings to use low process priority? Or make it permanently low on start. To make app more efficient with modern CPUs.

**Comment by mattw-mega** [comment]
Thanks for the suggestion, I think its' a good idea.  Perhaps not for the GUI thread, as you still want the GUI to be responsive even if the computer is busy (especially on a machine with fewer cores).   However an upcoming version will have sync calculations carried out on a separate thread, and that one could be lower priority.   I will make a ticket for that (though, it probably won't be in the first such version).  thanks
