### ISSUE TITLE
Megasync Windows Desktop Stuck At Syncing

### ISSUE THREAD

**Issue by DannyYap888** [meganz/MEGAsync#766]
I am using Windows 7 Pro and with effect from last week, the Desktop App (V. 4.8.5) keep getting stuck at syncing and retrying without the files being uploaded from the desktop to cloud. I've tried uninstalling the app and reinstalling it (both 32 and 64 bit) but still experiencing the same issue. Not having any issue when running Windows 10 on another PC. Thanks in advance. 

Note: If I uncheck  Use HTTP from Setting - Network - Bandwidth (Change Setting), the Desktop App would appear to have sync all the files but they do not appear in the mega.nz folder.  

![Untitled](https://user-images.githubusercontent.com/121478666/209623451-9fc31159-1f81-4f42-8ac4-6d34c511b6b9.png)

**Comment by mattw-mega** [comment]
If the files are not appearing in the webclient even though they uploaded ok, please try "Reload your account" in the webclient menu, top right

**Comment by DannyYap888** [comment]
> If the files are not appearing in the webclient even though they uploaded ok, please try "Reload your account" in the webclient menu, top right

Thanks for the suggestion. I've tried "Reload your account" in the webclient but the files still do not appear. When I re-check the Use HTTP from Setting - Network - Bandwidth (Change Setting), the same problem appears again.

**Comment by jcthor21** [comment]
This will solve your problem:

1º https://www.catalog.update.microsoft.com/search.aspx?q=kb4490628
2º https://www.catalog.update.microsoft.com/search.aspx?q=kb4474419
Reboot

3º https://www.catalog.update.microsoft.com/Search.aspx?q=KB3020369
4º https://www.catalog.update.microsoft.com/Search.aspx?q=KB3172605
Reboot

**Comment by DannyYap888** [comment]
> This will solve your problem:
> 
> 1º https://www.catalog.update.microsoft.com/search.aspx?q=kb4490628 2º https://www.catalog.update.microsoft.com/search.aspx?q=kb4474419 Reboot
> 
> 3º https://www.catalog.update.microsoft.com/Search.aspx?q=KB3020369 4º https://www.catalog.update.microsoft.com/Search.aspx?q=KB3172605 Reboot

After updating, the Desktop App appears to be able to "sync". However, the relevant files do not appear in the mega.nz website. I've tried "Reload your account" in the webclient but the files still do not appear. I also installed google drive in the same computer and the syncing via Google Drive is working fine. Any suggestion on what I can do next? Thanks.

**Comment by DannyYap888** [comment]
The weird thing is that when I right click on a file under the Completed of the Desktop App's Transfer Manager and choose "Open in MEGA", I can see the path of the file on the webclient just for that file:-
  
![image](https://user-images.githubusercontent.com/121478666/209769145-ea2e0bc3-5353-4f2e-ab84-0d8d41e81242.png)

However, when I go back to the main folder on the webclient, the file is missing:-

![image](https://user-images.githubusercontent.com/121478666/209769228-9b282520-42dc-4b5c-b007-17fa1045d093.png)

**Comment by mattw-mega** [comment]
It looks like those are just two different folders, both called "Lee Kim Lai".   One is in the cloud root, and the other in inside subfolder MEGAsync.    I think you are just syncing to one (CloudDrive/MEGAsync/KeeKimLai subfolder), and looking for the files in the other (CloudDrive/LeeKimKai).

**Comment by DannyYap888** [comment]
> It looks like those are just two different folders, both called "Lee Kim Lai". One is in the cloud root, and the other in inside subfolder MEGAsync. I think you are just syncing to one (CloudDrive/MEGAsync/KeeKimLai subfolder), and looking for the files in the other (CloudDrive/LeeKimKai).

Looks like you are absolutely right. I feel so foolish for not realizing that after reinstalling the Desktop App, by default, the Desktop App would sync to the (CloudDrive/MEGAsync/) folder whereas I am so used to having the files sync to the (CloudDrive) root folder.  All is good and resolved now. Thanks a million.
