### ISSUE TITLE
Is v4.8.5 accidentally released?

### ISSUE THREAD

**Issue by user8446** [meganz/MEGAsync#775]
I installed MEGAsync desktop for windows and it installed v4.8.5 yet GitHub shows 4.8.1 as the latest release. Just bringing this up if this was a mistake.

![Screenshot 2023-01-25 110049](https://user-images.githubusercontent.com/18019245/214613560-7e630c01-0271-4cc8-87e2-81021a8f6f79.png)

**Comment by vtmateos** [comment]
Hi,
It was produced by a delay in our publish mechanism. Already fixed and tags pushed to repo. Thanks.
