### ISSUE TITLE
Fonts too thin / unreadable

### ISSUE THREAD

**Issue by swiinger** [meganz/MEGAsync#783]
Hello,

I'm using the latest version 4.8.7 of megasync and now the fonts are too thin almost unreadable
I've reinstalled the client but still the same problem
I'm using windows 10 
Any thoughts ?
Thanks

![image](https://user-images.githubusercontent.com/43796769/219467070-186177d9-96bc-45dd-b9fe-a2cc599a33db.png)
![image](https://user-images.githubusercontent.com/43796769/219468116-598aa0e3-c202-458a-8791-5e7bc202d1c9.png)

**Comment by vtmateos** [comment]
Hi,
We have tested on W11 and W10 and displays correctly for both platforms. Do you know if you have any special display adjustment or configuration in your Windows that could produce that?

**Comment by swiinger** [comment]
ok thanks, after a reinstall from backup it's ok now
