### ISSUE TITLE
Vulnerable version of OpenSSL

### ISSUE THREAD

**Issue by Balgden** [meganz/MEGAsync#8]
Prompted by https://github.com/meganz/sdk/issues/252, I checked the versions shipped with MEGAsync 2.8.0. OpenSSL is still on 1.0.2d. You might want to update that ASAP as there have been three security advisories since.

While you're at it, maybe check for other outdated dependencies.

**Comment by javiserrano** [comment]
Thank you for notifying us.

We have updated the binaries in the computer that builds the official version of MEGAsync to 1.0.2g so the next version will use it.

An autoupdate will be released as soon as we finish some other ongoing works.

**Comment by javiserrano** [comment]
The problem was already solved. The current version of MEGAsync uses the latest version of OpenSSL (currently 1.0.2h).
