### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by Jvlsc** [meganz/MEGAsync#803]
Hello:

I'm experience an issue when trying to update MEGASync client on Ubuntu since last days:
![image](https://github.com/meganz/MEGAsync/assets/36289254/7247390d-9a35-4a9e-acb5-d241c41fcbdb)

Trying to download it from web:
![image](https://github.com/meganz/MEGAsync/assets/36289254/1fb84e6e-50c3-4965-aa6e-8440f8d9553f)

Regards.

**Comment by polmr** [comment]
You are being resolved to a private IP.

From the looks of it, your router, a public Wifi router, or your ISP provider is not letting you access to https://mega.nz/....

**Comment by Jvlsc** [comment]
You are right, it's something related to my ISP provider... I tried with a VPN and it works.

Sorry for the report.


Kind regards.
