### ISSUE TITLE
Repository broken Ubuntu 20.04

### ISSUE THREAD

**Issue by paloha** [meganz/MEGAsync#807]
**Description of the issue:**

When trying to do an apt upgrade on Ubuntu 20.04 it shows the following error:

```
Err:1 https://mega.nz/linux/repo/xUbuntu_20.04 ./ megasync 4.9.4-3.1
  404  Not Found [IP: 31.216.145.5 443]
E: Failed to fetch https://mega.nz/linux/repo/xUbuntu_20.04/./amd64/megasync_4.9.4-3.1_amd64.deb  404  Not Found [IP: 31.216.145.5 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Further comments:**

When you visit this address: `https://mega.nz/linux/repo/xUbuntu_20.04/amd64/`, the file `megasync_4.9.4-3.1_amd64.deb` appears to be there. However, I am not able to download it manually - when clicking on it, no download is issued. This is the case for all other files in that folder that are larger (in MB). For the smaller files (in kB), the file download starts with no problem. 

**Expected behavior:** 

When issuing `sudo apt upgrade`, Megasync should upgrade automatically without an error.

**Related issues:**

This might or might not be related to [this issue](https://github.com/meganz/MEGAsync/issues/203) that was fixed and closed in 2018.

**Comment by polmr** [comment]
There was some temporary issue in a repository server: it should be solved already. Thank you for reporting @paloha

**Comment by CleanHit** [comment]
I'm getting the same issue today in Debian 12.

```shell
E: Failed to fetch https://mega.nz/linux/repo/Debian_12/./amd64/megasync_5.11.1-1.1_amd64.deb  404  Not Found [IP: 2a0b:e46:1:144::5 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
There might be another temporary issue with the repository server.
