### ISSUE TITLE
Exclude apple ._* files from sync

### ISSUE THREAD

**Issue by x42en** [meganz/MEGAsync#82]
Hi,
I'd like to be able to prevent megasync from syncing apple index files (and probably .DS_Store, and .thumbs from windows, etc...).
It would be great if we can add a .syncignore inspired from .gitignore schema at the root of shared folders ... ;)

Thx !

**Comment by Akito13** [comment]
This feature already exists. Check the app's settings.

**Comment by x42en** [comment]
Ok my bad! ;) I should have checked twice before posting !!
I close this.
