### ISSUE TITLE
There is no option to unpin synced folders from windows file explorer's navigation pane

### ISSUE THREAD

**Issue by lkjimy** [meganz/MEGAsync#824]
Synced folders are automatically pinned to the system section of the navigation panel, instead of the user section, where I would have actually been able to unpin it.
![image](https://github.com/meganz/MEGAsync/assets/13991518/602b81dd-2207-4085-83a3-cf8dd6e03a97)

**Comment by SJai-mega** [comment]
Hello. If you want to hide all of synced folders you can simply do the following:

1. Right Click the "M" icon on your task bar
2. Click Settings
3. In the General Tab >> Untick "Enable Windows File Explorer Integration"

We hope this helps!

**Comment by lkjimy** [comment]
Got it @SJai-mega, thanks!

**Comment by dvschuetz** [comment]
The status of this issue should be set to "solved". Thank you!
