### ISSUE TITLE
Unable to use MEGASync while VPN active.

### ISSUE THREAD

**Issue by DonaldTPP** [meganz/MEGAsync#826]
It's only started doing this recently for me and I was wondering if there was anybody else experiencing the same problem. I use a VPN to browse safely and I wanted to sync my files but it doesn't log in. It just hangs there. I can log into my account normally through 3 different web browsers that I tried but not MEGASync Desktop App.

I turn off the VPN and I'm able to get in fine.

**Comment by jay2216** [comment]
I have the identical issue. As of two days ago I'm unable to log in with my vpn running. Has worked fine for years. This is very frustrating as this is used to sync my business with my home.

**Comment by mattw-mega** [comment]
Which VPN is it?  Perhaps it is interfering with the SSL requests to MEGA, altering either the requests or responses.  Also, perhaps it has options to turn off that interference, please check the VPN settings

**Comment by jay2216** [comment]
Expressvpn.

**Comment by mattw-mega** [comment]
According to their website, they have a feature where they block some sites.   Possibly MEGA got added to their list?   Or, it could be that they are interfering with the SSL somehow.   I would check their settings (which are not documented on their website, sorry), and try turning more and more features off until MEGA is contactable.   Then by a process of elimination you can determine which setting it was

**Comment by jay2216** [comment]
I'm using the linux version which has a limited settings offering and is run from the terminal. Running my business just became way more difficult to do when I can't physically be at it.

**Comment by DonaldTPP** [comment]
I too should have also mentioned that I'm using ExpressVPN. I just find it weird that I'm allowed to use the website freely but not the app. I am going to contact support and I'll come back when I've gotten a response, hopefully I'll be able to solve it for everybody.

**Comment by DonaldTPP** [comment]
Tried some troubleshooting through their live chat, and they cannot work out what it is and basically this is their solution;

"Since the app is unaccessible while connected to the VPN, this is the solution that we are seeing right now.
If you are not comfortable with it, please access it through the browser instead. "

**Comment by DonaldTPP** [comment]
It's definitely the IPV4 address that the DNS sets automatically once you connect that's causing the problems. I've just used another VPN and it connects to a different IPV4 address, and I can get into my MEGASync app without any problems.

**Comment by igorty** [comment]
Started to observe similar issue with Android app on two devices as well. Having infinite circle after "Connecting to the server" and "Updating file list".
Other apps have network access via ExpressVPN

**Comment by jay2216** [comment]
> Tried some troubleshooting through their live chat, and they cannot work out what it is and basically this is their solution;
> 
> "Since the app is unaccessible while connected to the VPN, this is the solution that we are seeing right now. If you are not comfortable with it, please access it through the browser instead. "

So their solution is that there is no solution and to use the browser? Hmmm. I tried the browser (Firefox) and it produces the same issue.

So which app made the changes that cause this problem? Was it Mega or Expressvpn? I don't see any app updates from either in the past few days.

**Comment by igorty** [comment]
Firefox works for me if I exit MEGASync app. If the app is running, it seems to be trying to perform actual download instead of browser

**Comment by jay2216** [comment]
> Firefox works for me if I exit MEGASync app. If the app is running, it seems to be trying to perform actual download instead of browser

I should clarify:
I tried controlling the vpn through the browser with the same results. I am able to connect to the mega website normally. It is unaffected by this issue. I use the app for it's auto sync, which is important to me. Obviously that isn't an option through a website interface.

**Comment by DonaldTPP** [comment]
I've just switched over to another VPN provider because of their lack of support.

**Comment by jay2216** [comment]
> I've just switched over to another VPN provider because of their lack of support.

Looking into the same. I sent Expressvpn an email. I'll give them the opportunity to fix the problem. If they can't/won't, adios.

Considering NordVPN. Thoughts?

**Comment by jay2216** [comment]
> Had troubles with NordVPN in the past on Ubuntu. Basically, after each update of their app it failed to establish VPN with try-again-later message. Had to reinstall their app each time in order to resolve the issue. Had also used Proton VPN. Is good overall. Some time ago they had some large infrastructure upgrades which ended up in a global outage of their service, and lasted almost whole day. After demanding a compensation for that issue they added extra free month to my subscription

Can I inquire which you are switching to now?

**Comment by igorty** [comment]
For now I've send ExpressVPN a message, as everyone here already did, and pointed to this issue on GitHub. If they won't try to investigate or come with no solution, I'll most likely return to Proton VPN.
It's a shame I prolonged my ExpressVPN subscription just couple weeks ago 😂

**Comment by jay2216** [comment]
> For now I've sent ExpressVPN a message, as everyone here already did, and pointed to this issue on GitHub. If they won't try to investigate or come with no solution, I'll most likely return to Proton VPN. It's a shame I prolonged my ExpressVPN subscription just couple weeks ago 😂

Any experience with surfshark?

**Comment by igorty** [comment]
Haven't used that service

**Comment by jay2216** [comment]
> Haven't used that service

Thanks.

**Comment by mattw-mega** [comment]
We have received reports that switching to Protocol Lightway-UDP within ExpressVPN fixes the problem.  thanks

**Comment by jay2216** [comment]
How does one do that on a linux installation that has no specific settings available?

**Comment by mattw-mega** [comment]
This page seems to have instructions:  https://www.expressvpn.com/support/vpn-setup/app-for-linux/

**Comment by jay2216** [comment]
> This page seems to have instructions: https://www.expressvpn.com/support/vpn-setup/app-for-linux/
From the instructions:
"Important: The OpenVPN manual configuration does not offer the same security and privacy benefits as the ExpressVPN app. If you are located in a country with a high level of internet censorship, you are recommended to use the ExpressVPN app for a more stable VPN connection."


Switched to Proton today. More features, half the price. Megasync works fine with it.

**Comment by DonaldTPP** [comment]
Just going to close this as there really is no solution.
