### ISSUE TITLE
MEGASync fails to build and/or run on Arch Linux.

### ISSUE THREAD

**Issue by cmason37** [meganz/MEGAsync#83]
I can not use MEGASync on Arch Linux. If I run the binary package, either from the official site ***or*** archlinuxcn repo, I get to the part where it sats you are in guest mode, then the app crashes without even giving me a chance to log in. [Here's the trace shown in the "Send Report" window](https://pastebin.com/jLE5baUK) & here's [the debug log generated by running megasync --debug > logfile.](https://pastebin.com/dsPp557D) I have had this issue for ~2 weeks despite the fact that I used the "Send Report" button to send the report to MEGA.

Now, when I try to build MEGASync, either the 3.0.1 version or the master branch,[ I get these errors.](https://pastebin.com/jwX1VxpN)

**Comment by polmr** [comment]
Please, ensure you have your Arch Linux updated:
pacman -Syu
For building, if you are still interested, you can take a look at: https://github.com/meganz/MEGAsync/blob/master/build/templates/MEGAsync/PKGBUILD to see what dependencies and build dependencies you need and the commands you need after recursivelly cloning the repo:
```
cd src
./configure -e -q
qmake-qt5 MEGA.pro || qmake-qt4 MEGA.pro
lrelease-qt5 MEGASync/MEGASync.pro || lrelease-qt4 MEGASync/MEGASync.pro 
make
```
The configure will download and compile some required dependencies. Caveat: you need to update the version of sodium to download and the corresponding md5 (this will eventually be fixed in `master`). Edit the corresponding lines in MEGASync/mega/contrib/build_sdk.sh:
```
local sodium_ver="1.0.12"
local sodium_md5="c308e3faa724b630b86cc0aaf887a5d4"
```

**Comment by cmason37** [comment]
@polmr My Arch system is completely up to date.  After following your steps, the build still fails with the exact same error. Also tried building from AUR & installing binary packages again, even though they weren't updated, just for the hell of it. Building package from AUR still fails with the aforementioned error. Binary packages from both mega.co.nz & archlinuxcn repo still crash with previously mentioned stack trace, too.

**Comment by polmr** [comment]
Indeed you seem to be too updated. This seems related to this recently opened issue in the sdk: https://github.com/meganz/sdk/issues/603. It seems there are compatibility issues with the lattest openssl. Do you have openssl 1.1.0e?

**Comment by cmason37** [comment]
@polmr Yes, I do.

**Comment by polmr** [comment]
There's an open PR in the sdk to support openssl 1.1.0. https://github.com/meganz/sdk/pull/622 . You might want to grab those changes in the submodule of megasync (src/MEGAsync/mega) and try to compile megasync. However curl should be compiled with openssl 1.1.0 too. I believe the easiest way to do that is to call configure with -g too: ./configure -e -q -g.  Alternatively you can always compile openssl 1.0.2 somewhere in your system and call megasync with LD_LIBRARY_PATH configured with the path of your compiled openssl 1.0.2/lib. I believe that should prevent the crash.

**Comment by cmason37** [comment]
@polmr Oddly enough, using ld variables to preload openssl-1.0 did not work, but building megasync with the Mega SDK on the develop branch (which has the above PR merged) did.

**Comment by bmbaker** [comment]
Hi there,
I'm having the same problem! I'm running a fully updated arch system with gnome-shell 3.22.

**Comment by polmr** [comment]
@bmbaker use `develop` branch please

**Comment by bmbaker** [comment]
@polmr I successfully compiled using the changes from the develop branch, and then built megasync which now runs just fine :-) look forward to seeing a new build land in Arch.
thanks alot BB

**Comment by mhoogkamer** [comment]
The following AUR package builds and runs fine: https://aur.archlinux.org/packages/megasync-git/
Thanks to @polmr's sdk fix to the develop branch which is now fetched in the PKGBUILD.

**Comment by polmr** [comment]
I'm wondering.... Do you all have openssl 1.1.0 installed manually? Official repos have 1.0.2.k which works fine with latest megasync at https://mega.nz/sync

**Comment by cmason37** [comment]
@polmr Nope, I never installed anything manually here.

**Comment by bmbaker** [comment]
I'm running the testing repo which has openssl 1.1.0.e-1.
Just did a rebuild using  https://aur.archlinux.org/packages/megasync-git/ works great.

**Comment by mhoogkamer** [comment]
Manually no. But it is in the testing repo.

**Comment by polmr** [comment]
Ok, thanks all!

**Comment by polmr** [comment]
Solved in the last release
