### ISSUE TITLE
Repository broken Ubuntu 20.04.3 LTS x86_64

### ISSUE THREAD

**Issue by Mateus-M-Reis** [meganz/MEGAsync#834]
**Description of the issue:**

When trying to do an apt upgrade on **Xbuntu 22.04.3 LTS X86_64** it shows the following error:

```
Err:1 https://mega.nz/linux/repo/xUbuntu_22.04 ./ megasync 4.9.6-1.1
  404  Not Found [IP: 2a0b:e46:1:144::5 443]
E: Failed to fetch https://mega.nz/linux/repo/xUbuntu_22.04/./amd64/megasync_4.9.6-1.1_amd64.deb  404  Not Found [IP: 2a0b:e46:1:144::5 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Further comments:**
The problem appeared after upgrading to Ubuntu 22.04.3 LTS (Jammy Jellyfish) some days ago, released 10 Ago 2023 as far as I am aware, 

**Expected behavior:**

When issuing sudo apt upgrade, Megasync should upgrade automatically without an error.

**Related issues:**

This might or might not be related to [this](https://github.com/meganz/MEGAsync/issues/807) issue that was fixed and closed in 19 May 2023.

**Solution**

Installing megasync-xUbuntu_22.04_amd64.deb from **https://mega.io/desktop#downloadapps** solves the problem:, so I'm just reporting.

```
...
Get:2 https://mega.nz/linux/repo/xUbuntu_22.04 ./ InRelease [2.961 B]   
....
#
The following packages will be upgraded:
  megasync
...
Get:1 https://mega.nz/linux/repo/xUbuntu_22.04 ./ megasync 4.9.6-1.1 [18,3 MB]

...
Unpacking megasync (4.9.6-1.1) over (4.9.5-1.1)
 ...
Setting up megasync (4.9.6-1.1) ...

```

**Comment by mbb78** [comment]
The same is happening in the Arch_Extra repo.

**Comment by archerindigo** [comment]
Same issue on Manjaro Linux. `DEB_Arch_Extra` repository

```
sudo pacman -Syyu
...
Packages (1) megasync-4.9.6-2

Total Download Size:   23.12 MiB
Total Installed Size:  52.77 MiB
Net Upgrade Size:       0.06 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 megasync-4.9.6-2-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'megasync-4.9.6-2-x86_64.pkg.tar.zst' from mega.nz : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
```

**Comment by polmr** [comment]
These issues should be fixed by now. Thanks for reporting.

**Comment by mbb78** [comment]
I confirm the issue is fixed.

**Comment by Mateus-M-Reis** [comment]
Closing as fixed.
