### ISSUE TITLE
Don't show the "no system tray" message all the time

### ISSUE THREAD

**Issue by jrepan** [meganz/MEGAsync#84]
I don't have a system tray by choice and it is very annoying that MEGAsync shows the "A system tray to place MEGAsync tray icon could not found" message every time I start my computer. It should either be shown only on the first start or have a checkbox "Don't show this warning again".

**Comment by polmr** [comment]
Hi, we'll only show this message once in future releases. Thanks for pointing that out.

**Comment by thurse93** [comment]
just a quick work around using xdotool since it also bothered me the past two weeks:
```megasync_notray_fix.sh
#!/bin/sh
until xdotool search --class "^MEGASync$" windowactivate
do
  sleep .2
done
xdotool key KP_Enter```
I put it in my wm startup configuration
