### ISSUE TITLE
Freezes on Steamdeck while creating a new a sync

### ISSUE THREAD

**Issue by Edummoon** [meganz/MEGAsync#841]
To replicate: 

Open megasync on Steamdeck. Select add sync. Once on the add folder screen after you select a "Local folder" mega sync will completely freeze and be unresponsive. Based on reviews from the Discover application (which helps you find and install applications, games, and tools on Linux) there are multiple reviews regurgitating this issue.

**Comment by palchyk-alex** [comment]
@Lcchy Unfortunately, installing AUR packages (Steam OS is Arch btw based) is not a good option. Also giving permissions through FlatSeal doesn't help. Hopefully it'll get fixed :(

**Comment by honsontran** [comment]
Also facing a similar problem here. Any updates on this?

**Comment by JakobDev** [comment]
Downgrading to an older versions fixed the problem for me

**Comment by JakobDev** [comment]
> Care to share what version? :)

[See this comment](https://github.com/flathub/nz.mega.MEGAsync/issues/49#issuecomment-1681521566)

**Comment by sudoshindo** [comment]
Help please, Linux Flatpak users have been having this problem since 2021, way before Steam Deck users started using MEGAsync.
@eprivado @jso-mega @oa-mega @vtmateos

**Comment by vtmateos** [comment]
Dear users,
Apologies for the inconveniences, but currently we do not support flatpack nor steamdeck officially. We will take your suggestion into account for future updates on that regards.
Thanks.
