### ISSUE TITLE
MEGAprivate ERROR DUMP

### ISSUE THREAD

**Issue by aniura** [meganz/MEGAsync#851]
Hi,

Yesterday MEGA stopped working in my laptop for some reason. The error messages are listed below. Re-installing didn't work.

Thanks in advanced for any help.

> MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: ab98ad51875c6fcb1a788c435f5b0879
Version code: 4906.1
Module name: MEGA
Timestamp: 1696892746450
Operating system: Linux
System version:  linuxmint 21.2/#96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023
System release:  5.15.0-86-generic
System arch: x86_64
Error info:
Falha de segmentação (11) at address 0x7fbd0548c000
Stacktrace:
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0x4690b6) [0x7fbd15beb0b6]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0x4690b6) [0x7fbd15beb0b6]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0x15ce70) [0x7fbd158dee70]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0x936e2) [0x7fbd158156e2]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0x96108) [0x7fbd15818108]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0xde680) [0x7fbd15860680]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0x93053) [0x7fbd15815053]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0x96108) [0x7fbd15818108]
/lib/x86_64-linux-gnu/libmediainfo.so.0(+0xff413) [0x7fbd15881413]
/lib/x86_64-linux-gnu/libmediainfo.so.0(_ZN12MediaInfoLib9MediaInfo20Open_Buffer_ContinueEPKhm+0x10) [0x7fbd15861690]
megasync(+0x4e92f1) [0x5573b28052f1]
megasync(+0x4e9a5e) [0x5573b2805a5e]
megasync(+0x47c1f8) [0x5573b27981f8]
megasync(+0x486a22) [0x5573b27a2a22]
megasync(+0x49c94a) [0x5573b27b894a]
megasync(+0x419a07) [0x5573b2735a07]
megasync(+0x5cf480) [0x5573b28eb480]
megasync(+0x5cf581) [0x5573b28eb581]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x7fbd13012253]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7fbd12c9bac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7fbd12d2da40]

**Comment by aniura** [comment]
?

**Comment by theotrst** [comment]
same issue here. Did you solve the problem?

**Comment by aniura** [comment]
Yes. In about a week the problem was solved somehow. (Don't know how)

Em sex., 8 de mar. de 2024 às 14:22, theotrst ***@***.***>
escreveu:
