### ISSUE TITLE
Outdated flatpak runtime

### ISSUE THREAD

**Issue by hevanaa** [meganz/MEGAsync#864]
On Fedora Linux, with the application installed from Flathub, updating the system on command line shows the following notification:

> Info: runtime org.kde.Platform branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   nz.mega.MEGAsync

> Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   nz.mega.MEGAsync

Version: 4.9.5.0_OSX

It would be expected to keep the application up-to-date, to minimize security issues etc. Current kde platform version is 5.15-23.08 and freedesktop 23.08.

**Comment by slagiewka** [comment]
As far as I know, this official repository (or the company itself) has nothing to do with the Flatpak-ed versioned.

There is a (stale) patch for this though:  https://github.com/flathub/nz.mega.MEGAsync/pull/27

**Comment by hevanaa** [comment]
Thanks for responding. It's not easy for a user to know who is responsible for which part of an application. Your link leads all the way to this bug, which seems to be the culprit: https://github.com/meganz/MEGAsync/issues/698 

Oh noes, my distro (Fedora 39) is already on ffmpeg 6.0. I'm closing this one and will add an (IMHO) appropriate comment there.
