### ISSUE TITLE
Disable Context Menu Integration

### ISSUE THREAD

**Issue by MatLcq** [meganz/MEGAsync#867]
Hello,
This issue here [https://github.com/meganz/MEGAsync/issues/319](url) has been marked as completed, so I guess there's a setting to toggle the context menu integration.
But I can't find it.
Can somebody help?
Thanks

EDIT: There is also the "Get MEGA link" and "View previous versions"

**Comment by cihe13375** [comment]
I don't think it can be done within MegaSync client itself, but there are lots of context menu management tools available on the Internet.

**Comment by segln** [comment]
For those looking to remove the MEGA menu item: Uninstall the MEGASyncShellSparse msix package

**Comment by VengefulAncient** [comment]
@segln I've tried your suggestion but such a package does not exist on my system.

**Comment by segln** [comment]
​Try running `winget list mega`. You need to find another way if it is not there because your system status is unknown here.
