### ISSUE TITLE
[Small Feature request ] - Ability to change the date format to DD.MM.YYYY

### ISSUE THREAD

**Issue by zenminimalist** [meganz/MEGAsync#878]
Some countries do not use / as a date separator, but a period "." like so 02.12.2023. 

Additionally, Mega could also add "-" (dash) for thos who prefer something like YYYY-MM-DD

This would be s small change, but make it more "local".

**Comment by vtmateos** [comment]
Could you specify for which languages should we apply this adjustment? Then, we will forward your request to our translation team.

Thanks.

**Comment by zenminimalist** [comment]
Sure thing @vtmateos 
Germany and many other European countries use the same date format as  02.12.2023 (DD.MM.YYYY)

**Comment by rautamiekka** [comment]
There's 1 big problem: only the YYYY-MM-DD format, with whatever separator, can be sorted properly.

**Comment by vtmateos** [comment]
After checking your request, I think you are referring to our webclient remote cloud view at "Date added/Last Modifed" columns right?

**Comment by zenminimalist** [comment]
> After checking your request, I think you are referring to our webclient remote cloud view at "Date added/Last Modifed" columns right?

Yes, that's exactly what I was referring to. Sorry, if I didn't make that clear in my first entry.

**Comment by vtmateos** [comment]
ok, then you should create the ticket at webclient [repository](https://github.com/meganz/webclient/issues). I am afraid not able to transfer this issue directly to it, so please fill a new one there. Closing this one.
Thanks.
