### ISSUE TITLE
Feature request: Flatpak installer for Linux

### ISSUE THREAD

**Issue by ktw** [meganz/MEGAsync#88]
It would be great if we had a Flatpak installer for Linux. 
Building from source does not seem to work in Solus, but Flatpak is supported by this great OS.

**Comment by polmr** [comment]
I'm afraid that atm we are not considering supporting Flatpak. It's good to know the interest, but it doesn't seem to have a wide acceptance yet and Qt support doesn't seem to be fully ready.

**Comment by nazar2sfive** [comment]
@polmr 
now flatpak is everywhere. hoping for reconsidering the thought.

**Comment by tim77** [comment]
:package: MEGAsync packaged on Flathub now https://flathub.org/apps/details/nz.mega.MEGAsync

**Comment by migtorr** [comment]
bump for an official build

**Comment by marek22k** [comment]
Why is the app labeled "Proprietary" on Flathub? The source code can be viewed.

**Comment by tim77** [comment]
> Why is the app labeled "Proprietary" on Flathub? The source code can be viewed.

https://github.com/meganz/MEGAsync/blob/master/LICENCE.md
