### ISSUE TITLE
MEGAprivate ERROR DUMP on raspberry pi

### ISSUE THREAD

**Issue by dronehack** [meganz/MEGAsync#880]
I am using megasync on raspberry pi. I have 5 devices and they all have the same error. I uninstalled the program and reinstalled it but it didn't work. Does anyone have any information about this problem?

MEGAprivate ERROR DUMP
Application: MEGAsync [32 bit]
Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Version code: 4607.2
Module name: megasync
Timestamp: xxxxxxxxxxxxxxxxxxxxxxxxx
Operating system: Linux
System version:  raspbian 10/#1529 SMP Tue Mar 8 12:24:00 GMT 2022
System release:  5.10.103-v7l+
System arch: armv7l
Error info:
Parçalama arızası (11) at address 0x620
Stacktrace:
/usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so(+0x1f50) [0xb6ee1f50]

**Comment by vtmateos** [comment]
Hi,
I am afraid we are not providing further versions of MEGAsync to Raspbian due to some third party problems with Qt. We will re-evaluate this situation, but in the meantime I would suggest to use MEGAcmd 1.7.0 when ready (it will happen in next weeks)

Thanks for your report.
