### ISSUE TITLE
megasync fails to start after icu package update on Arch / EndeavourOS

### ISSUE THREAD

**Issue by Peter-Ries** [meganz/MEGAsync#881]
Today icu package got updated to 74.2-1 and megasync fails to start with:

❯ megasync
megasync: error while loading shared libraries: libicuuc.so.73: cannot open shared object file: No such file or directory

dependency might need to be updated to new version

**Comment by Peter-Ries** [comment]
I could build the package with `yay megasync` - as this takes a while I use the megasync-bin package. This sems to be outdated. I'll reach out to package maintainer.

So not an megasync error,

**Comment by meatspinner** [comment]
This is not really completed since the Arch package provided on the website via wget is still broken.
