### ISSUE TITLE
Show in Folder always opens the Documents folder since 4.11.0

### ISSUE THREAD

**Issue by okurka** [meganz/MEGAsync#883]
After downloading a file clicking the "Show in folder" icon next to the file in the Transfers Window should open the folder the file is located in.
Since version 4.11.0 it always opens the Windows User's Documents folder even though the file is located on another drive.

Bug since: 4.11.0
OS: Windows 10

**Comment by SJai-mega** [comment]
Hello. Thank you for reporting. Our developers are aware of the issue and are investigating a fix. It will be resolved in the near future. 
Thanks! - SJ

**Comment by DJScias** [comment]
Hello there,

This seems to have randomly started working again today as of 4.12.2 (2e9307d) on my Windows 10.
A few days ago this was still broken, so there seems to have been a hotfix?
