### ISSUE TITLE
Critical dependency error in megasync on Arch

### ISSUE THREAD

**Issue by ivovegter** [meganz/MEGAsync#890]
I run Arch. I have megasync 4.11.0.0-1 installed from the Arch User Repository (AUR).

When I start megasync, I get: 
`megasync: error while loading shared libraries: libicuuc.so.73: cannot open shared object file: No such file or directory`

My current libicuuc.so library is libicuuc.so.74, installed via core/icu 74.2-1

I tried recompiling megasync, but it also complains that libicuuc.so.73 is missing. 

I tried to create a symbolic link from libicuuc.so.73 to libicuuc.so, but that threw a new error: 
`megasync: symbol lookup error: megasync: undefined symbol: u_foldCase_73`

I tried to downgrade icu back to version 73, but that breaks several dependecies for critical packages, including libreoffice.

Please fix megasync to work with icu version 74 as a matter of urgency. I am a paying MEGA subscriber, and the ability to sync my work to the MEGA cloud is critical to my workflow.

**Comment by vtmateos** [comment]
Hi @ivovegter ,
We have rebuilt packages for Arch so please download from [here](https://mega.io/desktop) and try again. 
Apologies for the inconveniences.
Regards.

**Comment by ivovegter** [comment]
Thanks. That package works. Can I assume future upgrades will occur as normal, via my package manager?

**Comment by vtmateos** [comment]
Sure, if you notice any other problem, just let us know.
Thanks.
