### ISSUE TITLE
build error in windows Qt

### ISSUE THREAD

**Issue by codinggg** [meganz/MEGAsync#92]
Hi, I am trying to build this project on my computer, and my pc has qt4.8.1 with vs2010, qt5.5.0 with vs2013
I use qt4.8.1 to build project. It has follow error:
:-1: error: LNK1181: can
 not open file “E:\myCode\sourceTree\abc\src\MEGASync\mega\bindings\qt\3rdparty\libs\x32\sodium.lib”

And, I don't find sodium.lib in x32 directory and x32d directory, but I find in x64 directory and x64d directory. I search in google not anything about sodium,but much like libsodium.

By the way, qt in windows not exist 64 byte version, so how to do ?
Please help me how to handle this error.
Thank's !

**Comment by vtmateos** [comment]
Dear user,

Thanks for trying out to build the project from scratch. With the newest vcpkg deps management and cmake, you can follow the readme installation notes and the process should be pretty straightforward.

Give it a try and if there is any issue, feel free to create a new issue. 

Thanks.
