### ISSUE TITLE
MEGAsync keep crashing every time

### ISSUE THREAD

**Issue by brandonnmartinsj** [meganz/MEGAsync#931]
Debian 8

MEGAprivate ERROR DUMP
Application: MEGAsync
Version code: 4002.0
Module name: megasync
Operating system: Linux
System version:  debian 8/#1 SMP Debian 3.16.84-1 (2020-06-09)
System release:  3.16.0-11-amd64
System arch: x86_64
Error info:
Segmentation fault (11) at address 0x11d8
Stacktrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f9ace65820d]
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f9ace65820d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbfee8) [0x7f9acf15dee8]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendEPKcm+0xe) [0x7f9acf15df2e]
megasync() [0x57819b]
megasync() [0x53159e]
megasync() [0x540fb1]
megasync() [0x55f641]
megasync() [0x566c3c]
megasync() [0x56a718]
megasync() [0x64cdfd]
megasync() [0x64ce77]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7c70f) [0x7f9acf64270f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f9acf3b1064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f9ace6ae62d]
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync
Version code: 4002.0
Module name: megasync
Operating system: Linux
System version:  debian 8/#1 SMP Debian 3.16.84-1 (2020-06-09)
System release:  3.16.0-11-amd64
System arch: x86_64
Error info:
Segmentation fault (11) at address 0x11d8
Stacktrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7fbd6b1e820d]
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7fbd6b1e820d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbfee8) [0x7fbd6bcedee8]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendEPKcm+0xe) [0x7fbd6bcedf2e]
megasync() [0x57819b]
megasync() [0x53159e]
megasync() [0x540fb1]
megasync() [0x55f641]
megasync() [0x566c3c]
megasync() [0x56a718]
megasync() [0x64cdfd]
megasync() [0x64ce77]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7c70f) [0x7fbd6c1d270f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7fbd6bf41064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fbd6b23e62d]
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync
Version code: 4002.0
Module name: megasync
Operating system: Linux
System version:  debian 8/#1 SMP Debian 3.16.84-1 (2020-06-09)
System release:  3.16.0-11-amd64
System arch: x86_64
Error info:
Segmentation fault (11) at address 0x11d8
Stacktrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7efda099920d]
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7efda099920d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbfee8) [0x7efda149eee8]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendEPKcm+0xe) [0x7efda149ef2e]
megasync() [0x57819b]
megasync() [0x53159e]
megasync() [0x540fb1]
megasync() [0x55f641]
megasync() [0x566c3c]
megasync() [0x56a718]
megasync() [0x64cdfd]
megasync() [0x64ce77]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7c70f) [0x7efda198370f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7efda16f2064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7efda09ef62d]
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync
Version code: 4002.0
Module name: megasync
Operating system: Linux
System version:  debian 8/#1 SMP Debian 3.16.84-1 (2020-06-09)
System release:  3.16.0-11-amd64
System arch: x86_64
Error info:
Segmentation fault (11) at address 0x11d8
Stacktrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f319670320d]
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f319670320d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbfee8) [0x7f3197208ee8]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendEPKcm+0xe) [0x7f3197208f2e]
megasync() [0x57819b]
megasync() [0x53159e]
megasync() [0x540fb1]
megasync() [0x55f641]
megasync() [0x566c3c]
megasync() [0x56a718]
megasync() [0x64cdfd]
megasync() [0x64ce77]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7c70f) [0x7f31976ed70f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f319745c064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f319675962d]
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync
Version code: 4002.0
Module name: megasync
Operating system: Linux
System version:  debian 8/#1 SMP Debian 3.16.84-1 (2020-06-09)
System release:  3.16.0-11-amd64
System arch: x86_64
Error info:
Segmentation fault (11) at address 0x11d8
Stacktrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f8a14e5a20d]
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f8a14e5a20d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbfee8) [0x7f8a1595fee8]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendEPKcm+0xe) [0x7f8a1595ff2e]
megasync() [0x57819b]
megasync() [0x53159e]
megasync() [0x540fb1]
megasync() [0x55f641]
megasync() [0x566c3c]
megasync() [0x56a718]
megasync() [0x64cdfd]
megasync() [0x64ce77]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7c70f) [0x7f8a15e4470f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f8a15bb3064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f8a14eb062d]
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync
Version code: 4002.0
Module name: megasync
Operating system: Linux
System version:  debian 8/#1 SMP Debian 3.16.84-1 (2020-06-09)
System release:  3.16.0-11-amd64
System arch: x86_64
Error info:
Segmentation fault (11) at address 0x11d8
Stacktrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f908835920d]
/lib/x86_64-linux-gnu/libc.so.6(+0x9220d) [0x7f908835920d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbfee8) [0x7f9088e5eee8]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs6appendEPKcm+0xe) [0x7f9088e5ef2e]
megasync() [0x57819b]
megasync() [0x53159e]
megasync() [0x540fb1]
megasync() [0x55f641]
megasync() [0x566c3c]
megasync() [0x56a718]
megasync() [0x64cdfd]
megasync() [0x64ce77]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7c70f) [0x7f908934370f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f90890b2064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f90883af62d]

**Comment by tt-mega** [comment]
Hello brandonnmartinsj, 

Please email us at support@mega.nz from the affected email address explaining your issue and we will be happy to help you.  

Thanks!
