### ISSUE TITLE
LMDE6 issue: Megasync crashes on huge sunc - Unable to add filesystem watch (Linux Mint Debian Edition)

### ISSUE THREAD

**Issue by joachimrs** [meganz/MEGAsync#933]
To resolve this have a look at /etc/sysctl.d/lmde.conf and _comment_ _out_ the fs.inotify.max_user_watches line like so:
```/etc/sysctl.d/lmde.conf
kernel.dmesg_restrict=0
# fs.inotify.max_user_watches=65536
```
When installing megasync-Debian_12_amd64.deb there should be a /etc/sysctl.d/99-megasync-inotify-limit.conf containing:
```/etc/sysctl.d/99-megasync-inotify-limit.conf
fs.inotify.max_user_watches = 524288
```
Unfortunately LMDE6 does not adhere to the old Unix style of '##==Priority' but rather adopts the poettering systemd 'I know better than you in which order I will load .conf files! Shut up!" schema. Being '99' the megasync configuration should be loaded last, but as 'lmde' comes after '99' it is overwritten with the lmde setting of 65k - unless you comment that out, see above. Restart required. After rebooting check with:
```
$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 524288
```
It worked and you should be able to 'Desktop Sync' those HUGE directories of useless junk again :)

**Comment by tt-mega** [comment]
Hello joachimrs, 

Please email us at [support@mega.nz](mailto:support@mega.nz) from the affected email address explaining your issue and we will be happy to help you.  

Thanks!

**Comment by joachimrs** [comment]
To add a note here: LMDE6 has fs.inotify.max_user_watches=65535 which is not high enough for my case. I found that changing the value in sysctl.conf or a sysct.conf.d file, as megacmd (99-megacmd-...) does, does not work on LMDE6. I need to manually run sysctl -p after a reboot and after adding the line "fs.inotify.max_user_watches=524288" in /etc/sysctl.conf - Will investigate more. MEGAsync crashes instead of giving advice, checking /proc/sys/fs/inotify/max_user_watches and keeping track of watchers set up could make MEGAsync aware of the limitation set up on the underlying system and could give advice or even change the value. Setting the line in /etc/sysctl.conf and sudo sysctl -p on Debian / LMDE6n does the trick and MEGAsync runs fine afterwards with even huge files and directories being synced. But it shouldn't crash in the first place and check how many watches it can set and warn the user and then at least exit gracefully with advice on how to set the max_user_watches to the max value, see above.
