### ISSUE TITLE
Section 2: Grant Of Rights Issue in the  License (Typo)

### ISSUE THREAD

**Issue by merzainc** [meganz/MEGAsync#935]
Section 2: Grant Of Rights 

You may provide the code to anyone else and publish _**excerpts**_ of it for the purposes of review, compilation and non-commercial distribution, provided that when you do so you make any recipient of the code aware of the terms of this licence, they must agree to be bound by the terms of this licence and you must attribute the code to Mega.

The highlighted word in bold seems to be a typing error and makes the sentence lose intend meaning.

**Comment by jx-mega** [comment]
Hi,
We´ve checked with the team and the word is correct. 
Let us know if you have further questions or if you have examples to support your point would be even better.

**Comment by merzainc** [comment]
> Hi, We´ve checked with the team and the word is correct. Let us know if you have further questions or if you have examples to support your point would be even better.

Noted thank you very much.
