### ISSUE TITLE
Failed to download gpg - fedora 40

### ISSUE THREAD

**Issue by vorticalbox** [meganz/MEGAsync#938]
I am on kinonite (fedora 40) and getting the following error when i check for updates. 

```
rpm-ostree transaction failed with:
error: Loading sack: Updating rpm-md repo 'MEGAsync': Failed to download gpg key for repo 'MEGAsync': Status code: 404 for https://mega.nz/linux/repo/Fedora_40/repodata/repomd.xml.key (IP: 31.216.144.5)
```

**Comment by lukasmrtvy** [comment]
https://mega.nz/linux/repo/Fedora_40 does not exist yet

**Comment by vorticalbox** [comment]
> https://mega.nz/linux/repo/Fedora_40 does not exist yet

I know but today is fedora 40 release date

**Comment by imli700** [comment]
> https://mega.nz/linux/repo/Fedora_40 does not exist yet

when is it usually available?
