### ISSUE TITLE
Crash on startup upgrade dialog

### ISSUE THREAD

**Issue by summoner001** [meganz/MEGAsync#939]
When I launch the Megasync application this window pops up:

Security upgrade

Your accounts security is now beeing upgraded. This will happen only once. If you've seen this message for this account before, click cancel.

When I click on cancel -> the application exits
When I click on yes -> Failed to upgrade security. Error: Temporarily not available

Problem occured in this release: https://aur.archlinux.org/packages/megasync-bin

OS: Latest Arch Linux
Current installed release: https://aur.archlinux.org/packages/megasync-bin
The same problem is present in the megasync 5.2.0.0-1 - https://aur.archlinux.org/packages/megasync version.

**Comment by sallirom** [comment]
I have exactly the same problem, sync unusable.

**Comment by saflo76** [comment]
I have 2 Arch linux machines, one works fine even with latest megasync version, the other went with this error since the major update version (5.2) and the error still persists with last 5.2.1-4 package.
Cannot evince anything in journal to understand what triggers this issue, I tried to wipe any of my userspace data and package reinstall, but at the moment of signing with my mega account right after confirmation the error described above happens and program apparently crashes.

**Comment by meatspinner** [comment]
Same here. I've tried to install both from the official repo as well as AUR and Chaotic AUR but the issue persists; Logging out through the website and log in through the app does nothing to solve the issue.

Not sure if either KDE 6 or Arch is the problem.

**Comment by summoner001** [comment]
@meatspinner  I'm using gnome46 so I don't think it's a kde 6 problem.

**Comment by sallirom** [comment]
> @meatspinner I'm using gnome46 so I don't think it's a kde 6 problem.

yeah, same here. I have Manjaro with KDE in one machone and Manjaro with XFCE in another one. The problem appears on both of them.

**Comment by meatspinner** [comment]
> @meatspinner I'm using gnome46 so I don't think it's a kde 6 problem.



> > @meatspinner I'm using gnome46 so I don't think it's a kde 6 problem.
> 
> yeah, same here. I have Manjaro with KDE in one machone and Manjaro with XFCE in another one. The problem appears on both of them.

Its likely an Arch issue then. I'll try to install either the flatpak package or an older version of megasync to see if I can sync, at least temporarily.

**Comment by Randal400** [comment]
I have two machines with ARCH + XFCE, one has the same problem and the other works well.

I don't know what is happening but is disappointing

**Comment by saflo76** [comment]
I can't be in front of the issue machine now but from the other (the one which works) I have discovered that if you run from terminal megasync with --debug parameter you can follow all debug messages for internal program operations, this may turn useful to spot something for bugged cases.
I will try it later in the "bugged" installation.

**Comment by veroneze** [comment]
`05/09-16:32:43.097337 140595241363136 INFO Request (UPGRADE_SECURITY) starting [megaapi_impl.cpp:16457]
05/09-16:32:43.097391 140595241363136 DBG  Upgrading cryptographic subsystem. [megaclient.cpp:11368]
05/09-16:32:43.097397 140595241363136 WARN Keys not available [megaclient.cpp:11391]
05/09-16:32:43.097403 140595241363136 WARN Request (UPGRADE_SECURITY) finished with error: Temporarily not available [megaapi_impl.cpp:16499]`

**Comment by meatspinner** [comment]
I've tried everything I could think of and and the only thing that worked was this AUR package: [https://aur.archlinux.org/packages/megasync-nopdfium](url).

Its a temporary fix until the devs solve the issue.

**Comment by sallirom** [comment]
THANK YOU, thank you so much for the heads up, this was extremely helpful. :pray: 

> I've tried everything I could think of and the only thing that worked was this AUR package:
> 
> [https://aur.archlinux.org/packages/megasync-nopdfium](url) (For some reason the URL isn't working so you've to copy the URL text).
> 
> Its a temporary fix until the devs fix the issue.

**Comment by Randal400** [comment]
> I've tried everything I could think of and the only thing that worked was this AUR package:
> 
> [https://aur.archlinux.org/packages/megasync-nopdfium](url) (For some reason the URL isn't working so you've to copy the URL text).
> 
> Its a temporary fix until the devs fix the issue.

Then I would have to uninstall the official app and install this from AUR?

**Comment by meatspinner** [comment]
> > I've tried everything I could think of and the only thing that worked was this AUR package:
> > [https://aur.archlinux.org/packages/megasync-nopdfium](url) (For some reason the URL isn't working so you've to copy the URL text).
> > Its a temporary fix until the devs fix the issue.
> 
> Then I would have to uninstall the official app and install this from AUR?

I think so, for now. I don't think you can have both versions installed at the same time.

**Comment by Randal400** [comment]
I made the update but the problem continues :-(

**Comment by summoner001** [comment]
Megasync-bin the proble is still there in [v5.2.1-5](https://aur.archlinux.org/packages/megasync-bin)

**Comment by summoner001** [comment]
I checked the package you linked. I think it's the same as the package in AUR, just with a different maintainer, but I won't argue. I installed it. Yes, the problem is also present in the official package.

![Képernyőkép 2024-06-10 11-17-06](https://github.com/meganz/MEGAsync/assets/11212632/f7065d28-90e1-4ae5-b8c6-c2e2cfa016a7)

**Comment by vtmateos** [comment]
Hi,
The package deals with some linking issues that avoid running the app on Arch linux. It seems that this is a different issue with the current logged account in MEGAsync. Please, would you mind to contact our support system so they can perform some check ups over your accounts? 

They will help with that.

Apologies for the inconveniences.

**Comment by summoner001** [comment]
This is not an account problem. I can't even log in through the app because the window that you see in the screenshot pops up before the login window...

**Comment by vtmateos** [comment]
Hi,
You are already logged in from previous execution, that is why the log in dialog does not pop up. You have still an active session.
Please, if you want further assistance reach our support team so they will ask for your account and they can perform some verifications. support@mega.co.nz.

Thanks.

**Comment by summoner001** [comment]
Ok I understand now. I wrote to support about this. Thank you! have a nice day!

**Comment by summoner001** [comment]
@vtmateos  The support doesn't reply my question for 3 days. I didn't know it would take so long. :(

**Comment by john371911** [comment]
> I've tried everything I could think of and the only thing that worked was this AUR package:
> 
> [https://aur.archlinux.org/packages/megasync-nopdfium](url) (For some reason the URL isn't working so you've to copy the URL text).
> 
> Its a temporary fix until the devs fix the issue.

I have the problem too. Does that file work currently?

**Comment by john371911** [comment]
> Hi,  [v5.2.1-5](https://aur.archlinux.org/packages/megasync-bin) is an AUR package that MEGA does not offer support for. We have updated our Arch packages under this repo url https://mega.nz/linux/repo/Arch_Extra/x86_64/v5.2.1-5
> 
> Did you test the ArchLinux version from the MEGA repo?

My OS is manjaro plasma.
On your official website, I installed with your instruction:
wget https://mega.nz/linux/repo/Arch_Extra/x86_64/megasync-x86_64.pkg.tar.zst && sudo pacman -U "$PWD/megasync-x86_64.pkg.tar.zst"

I wound download 5.2.1-4, but this vision can't even run. Then the AUR would update to to 5.2.1-5, and it has the problem as this article showed. Should I uninstall it then install from your reop: https://mega.nz/linux/repo/Arch_Extra/x86_64/v5.2.1-5 ?

**Comment by Randal400** [comment]
the last official update (megasync 5.3.0-2) seems to fix the problem :-), at least to me.

**Comment by john371911** [comment]
> the last official update (megasync 5.3.0-2) seems to fix the problem :-), at least to me.

Sadly my manjaro crashed may because I moved home incorrectly. I'm still trying to fixing it😅
