### ISSUE TITLE
Arch linux: symbol lookup error: megasync: undefined symbol: u_foldCase_74

### ISSUE THREAD

**Issue by dolkilu** [meganz/MEGAsync#953]
Neither versions worked for me.
` sudo pacman -U https://mega.nz/linux/repo/Arch_Extra/x86_64/megasync-x86_64.pkg.tar.zst`
```
 paru megasync
 DEB_Arch_Extra/megasync 5.2.1-4 [0 B 58.17 MiB]
    Get more control over your data
 aur/megasync 5.2.1.0-1 [+382 ~2.39]
    Official MEGA desktop application for syncing with MEGA Cloud Drive
```

```
> megasync 
megasync: symbol lookup error: megasync: undefined symbol: u_foldCase_74
```

Before install megasync I did a `-Syu`, which upgraded kernel to 6.9.1-arch1-2, not sure if related.
Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.9.1-arch1-2 (64-bit)
Graphics Platform: X11

**Comment by nsirolli** [comment]
This should be related to the icu package. Here I get a different error message:

```
nico@pilar~ $ megasync
megasync: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory
```

I tried creating a symlink with that name, pointing to libicuuc.so.74, and then I get the same error message as you.

**Comment by dolkilu** [comment]
> This should be related to the icu package. Here I get a different error message:
> 
> ```
> nico@pilar~ $ megasync
> megasync: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory
> ```
> 
> I tried creating a symlink with that name, pointing to libicuuc.so.74, and then I get the same error message as you.

Oh yea that's the work around I did too, Forgot to mention it.

**Comment by vtmateos** [comment]
Hi,
We are working on a fix for icu74 issues. Apologies for the inconveniences.
It will be ready soon.
Thanks.
