### ISSUE TITLE
Doesn't work with Fedora 26 

### ISSUE THREAD

**Issue by srakitnican** [meganz/MEGAsync#96]
Starting megasync from command line gives no output, however it doesn't appear to be right. Process is using 100% cpu, tray icon does not load correctly and megasync is unresponsive.

**Comment by polmr** [comment]
I understand you're using Fedora 25 package. Some difference in the versions of a dependency might be causing that. We will provide packages for Fedora 26 soon.

**Comment by srakitnican** [comment]
Actually, I was using Fedora 23 repo, this is an old test install and I've completely forgot about that. Sorry about that.

Using Fedora 25 repo now, seems to work fine.

Not sure about other distros, but in Fedora it is possible to use `$releasever` variable in repository file, usually in links, so that links always point to repository for current distribution release.

**Comment by srakitnican** [comment]
https://github.com/meganz/MEGAsync/blob/master/build/templates/MEGAsync/megasync.spec#L158
I see you are writing repo file when package is installed, could you make that into something like:
```
YUM_FILE="/etc/yum.repos.d/megasync.repo"
cat > "$YUM_FILE" << DATA
[MEGAsync]
name=MEGAsync
baseurl=https://mega.nz/linux/MEGAsync/Fedora_$releasever/
gpgkey=https://mega.nz/linux/MEGAsync/Fedora_$releasever/repodata/repomd.xml.key
gpgcheck=1
enabled=1
DATA
```

**Comment by polmr** [comment]
that's interesting... however in this particular case: You are using a Fedora 25 package in a Fedora 26. Fedora 26 repo does not exist yet, and it'll fail. On the other hand you will have your repo configured correctly by the time a package for Fedora 26 is released.

**Comment by srakitnican** [comment]
It would not be a big of a deal, repository that doesn't exist yet is just skipped. Notifying user is better in my opinion then to use old repo in the background.

Always overwriting repo file is not the best practice also in my opinion. Rpm have an option to specify configuration files. That way it can be specified what to do with the file in the system if it is different then the file from package; overwrite it and backup the old file as .rpmsave or create as a new file .rpmnew. But that would require to package repo file as file I think there is no way around that.

I found another minor issue: Repo file is not owned by megasync package although it originates from it. For files that are not present when package is created you can use %ghost tag in %files section.

http://rpm5.org/docs/api/specfile.html

**Comment by polmr** [comment]
$releasever variable is now used. Thanks for the inputs. As for the `%ghost` inclusion of the repo. We don't want it to be part of the package, as it also can be created upon the installation of `megacmd`.
