### ISSUE TITLE
Release 4.13.0.0 ?

### ISSUE THREAD

**Issue by Perkolator** [meganz/MEGAsync#960]
So, what is the recent 4.13.0.0 version release? Is 5.x versions taken back for now? Is there going to be a 4.13.0.0 for linux? Your github repo & releases are a mess.

**Comment by tt-mega** [comment]
Hello,
Version 4.13 was released just to contemplate a small hotfix related to Pro upgrade information.
Our latest version for all OS is still version 5.x
