### ISSUE TITLE
the display of exclusion settings is corrupted when the language is Japanese

### ISSUE THREAD

**Issue by Endergreen12** [meganz/MEGAsync#973]
i'm using Windows 11 23H2
when the language is Japanese, the “Manage exclusions” section becomes vertically long, and the button to add an exclusion is outside the window, making it impossible to press and impossible to set the exclusion
it's normal when the language is English
![image](https://github.com/user-attachments/assets/780c998d-8bec-4291-ada6-cdbcf2c929e1)

**Comment by vtmateos** [comment]
Thanks for reaching us. We have made some test with our ongoing version we are preparing (5.4.0), and all looks fine. Could you confirm which version are you using? Thanks.

**Comment by Endergreen12** [comment]
> Thanks for reaching us. We have made some test with our ongoing version we are preparing (5.4.0), and all looks fine. Could you confirm which version are you using? Thanks.

i'm using 5.3.0 64-bit (eb8dba0)

**Comment by vtmateos** [comment]
Please, retest once 5.4 is released. If this still happens, reopen the issue. Thanks.
