### ISSUE TITLE
Doesn't support ReFS volumes

### ISSUE THREAD

**Issue by Kovur** [meganz/MEGAsync#980]
Hi.
The MEGAsync doesn't support ReFS volumes. I got the "Local filesystem mismatch" error.
Please add the support of this filesystem.

(version 5.2.1 64-bit)

**Comment by rautamiekka** [comment]
Old version, try the 5.4.0.0.

**Comment by Kovur** [comment]
> 5.4.0.0.
Thanks. Version 5.4.0.0 works correctly.
