### ISSUE TITLE
[installer error] vcruntime140.dll error save file install

### ISSUE THREAD

**Issue by FadeMind** [meganz/MEGAsync#981]
Since recent updates Client Windows Desktop for Mega during install proccess I have an error with permission denied for `vcruntime140.dll` 
![20240814-1723649271](https://github.com/user-attachments/assets/97705d4c-9eaf-4820-b9a1-bee86edb6074)
Ignore works but this is annoying. 

Windows 11 23H2 22631.x X64

**Comment by Machou** [comment]
same error on Windows 11 64 bit since 5.4.0 (i'm on 5.3.0)

**Comment by Eldaw** [comment]
Same here. Can't upgrade from 5.3.0 to 5.4.1 because of this issue.

**Comment by betterdoitnow** [comment]
same issue here. I ended up ingorning the pop-up window and went through, seems work fine....

**Comment by vtmateos** [comment]
Hi!
Apologies for the inconveniences. We have already fixed it on next version we are currently preparing, aka 5.5.0. Stay tuned!
Just ignore it, it was an issue during reinstallation over a previous MEGAsync installation because the dll is in use. It does not affect the normal work of the program.
