### ISSUE TITLE
Windows Defender keeps finding Trojan:Win32/Vigorf.A in :\Users\Yours_Truly\Documents\MEGA\Rubbish\tmp\.getxfer.7492.1.mega

### ISSUE THREAD

**Issue by UglyStuff** [meganz/MEGAsync#990]
Hi Everyone, 

I'm new to this part of the forum. I recently upgraded Mega to 200GB and contrarily to what happened when I was still on the free tier, now I keep receiving threat notifications from Windows Defender about it finding Trojan:Win32/Vigorf.A in :\Users\Yours_Truly\Documents\MEGA\Rubbish\tmp\.getxfer.7492.1.mega. 

The Rubbish\tmp folder is hidden and though I've deleted it then rebooted my PC, it's created again upon reboot by the Mega app and almost immediately Windows Defender pops up with its warnings. 

The threat is quarantined by Windows Defender but I can't help wondering why on Earth would this suddenly happen. When I was on the free tier, I didn't have any such warnings. 

Of course I uploaded more personal data since I upgraded and maybe the infected file or files were among that data (though Windows Defender never detected anything on my PC before that) but why does Mega keep putting suspicious files in that tmp folder? 

EDIT: The app notifies me that a file called produkey.zip couldn't be synced, probably because Windows Defender quarantined it. How do I get rid of that file if I can't locate it fast enough? 😐

**Comment by rautamiekka** [comment]
Tell Defender to send the quarantined files to M$, so they can fix their own bullshit. If they can, that is.

If you do somehow happen to get a reply, try sending them this very issue.

**Comment by UglyStuff** [comment]
Hi and thanks for taking the time. 

Actually, I deleted the file from the web interface (I didn't use it anyway) and all is well now. 

I agree that Microsoft doesn't like that kind of product and enforces stupid rules to block/quarantine them, but I wonder why Mega will place them in a tmp folder like that. Is it so syncing files can proceed while a file is being investigated or blocked by Windows Defender (or any other antivirus, for that matter)?
