### ISSUE TITLE
Website download links for Linux are broken

### ISSUE THREAD

**Issue by loukamb** [meganz/MEGAsync#994]
On [this page](https://mega.io/desktop), regardless of the distribution you select, the website will fail to fill in `packageDownloadUrl` and `packageFilename` variables in the output to copy.

For example, Ubuntu shows this:
```sh
wget packageDownloadUrl && sudo apt install "$PWD/packageFilename"
```

Arch shows this:
```sh
wget packageDownloadUrl && sudo pacman -U "$PWD/packageFilename"
```

`megalib.js` outputs the following warnings in the console:
```
Unregistered placeholder "packageDownloadUrl" detected. Ignoring.
Unregistered placeholder "packageFilename" detected. Ignoring.
```

I currently run Firefox 130. I know that this issue also occurs on Safari on iOS.

**Comment by rautamiekka** [comment]
Confirmed, same happens to me on Google Chrome 128.0.6613.138 (which was old by the time I checked the version) on Win10.

**Comment by vtmateos** [comment]
We will check out and fix. Thanks for your report.

**Comment by rautamiekka** [comment]
I confirm it's fixed, although I'm still on the same older Chrome.
