### ISSUE TITLE
Mega Sync Desktop App Crashing

### ISSUE THREAD

**Issue by 6268095** [meganz/MEGAsync#996]
good afternoon!
I bought a one-year Pro II just a few days ago and these are the first days for me to use the app. the operating system is Win10.
Unfortunately, every time I use it, it crashes, but it's not regular, sometimes it crashes a few hours after opening, sometimes it crashes after just a few minutes of opening, and I can't figure out why.
Every time I go to the start menu and reopen the app, a diagnostic screen pops up with these error messages, and the Error info is the same every time Error info: Unhandled exception 0xC0000005 at 0x1358 (VCRUNTIME140.dll)
I tried reinstalling Visual C++ Redistributable, but it didn't work.
Do you guys know how to fix this, please help me, I'm very frustrated right now. Below is the error message, the point is that it is the same Error info every time, there is no difference.

**MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: 09cde7c9a3955a5b00d77a1fafc8eeab
Version code: 50401.1
Timestamp: 1726978132598
Module name: MEGAsync.exe
Operating system: Windows 10.0.19045
Error info:
Unhandled exception 0xC0000005 at 0x1358(VCRUNTIME140.dll)
Stacktrace:
#0 0x1358 (VCRUNTIME140.dll)
#1 0x18B652E (MEGAsync.exe)
#2 0x18DA704 (MEGAsync.exe)
#3 0x18DACEC (MEGAsync.exe)
#4 0x18D9C47 (MEGAsync.exe)
#5 0x18DC8A7 (MEGAsync.exe)
#6 0x187F144 (MEGAsync.exe)
#7 0x187CB39 (MEGAsync.exe)
#8 0x18659CE (MEGAsync.exe)
#9 0x1865AA0 (MEGAsync.exe)
#A 0xB3FF57 (MEGAsync.exe)
#B 0xA81689 (MEGAsync.exe)
#C 0xA827B5 (MEGAsync.exe)
#D 0xA83529 (MEGAsync.exe)
#E 0x664CFF (MEGAsync.exe)
#F 0x21BB2 (ucrtbase.dll)
#10 0x17374 (KERNEL32.DLL)
#11 0x4CC91 (ntdll.dll)
------------------------------
MEGAprivate ERROR DUMP
Application: MEGAsync [64 bit]
Hash: e69e6ccb7fd39cf2c73fa3613f0390ad
Version code: 50401.1
Timestamp: 1726975879323
Module name: MEGAsync.exe
Operating system: Windows 10.0.19045
Error info:
Unhandled exception 0xC0000005 at 0x1358(VCRUNTIME140.dll)
Stacktrace:
#0 0x1358 (VCRUNTIME140.dll)
#1 0x18B652E (MEGAsync.exe)
#2 0x18DA704 (MEGAsync.exe)
#3 0x18DACEC (MEGAsync.exe)
#4 0x18D9C47 (MEGAsync.exe)
#5 0x18DC8A7 (MEGAsync.exe)
#6 0x187F144 (MEGAsync.exe)
#7 0x187CB39 (MEGAsync.exe)
#8 0x18659CE (MEGAsync.exe)
#9 0x1865AA0 (MEGAsync.exe)
#A 0xB3FF57 (MEGAsync.exe)
#B 0xA81689 (MEGAsync.exe)
#C 0xA827B5 (MEGAsync.exe)
#D 0xA83529 (MEGAsync.exe)
#E 0x664CFF (MEGAsync.exe)
#F 0x21BB2 (ucrtbase.dll)
#10 0x17374 (KERNEL32.DLL)
#11 0x4CC91 (ntdll.dll)**

![B99B620AA4837D09D46D02847D2BCD16](https://github.com/user-attachments/assets/baabd6b7-34e6-4a7c-a0fe-f6c2614ea21d)

**Comment by 6268095** [comment]
@rl-mega  Thanks, this method was successful, and the program never crashed again. Love you guys

**Comment by rl-mega** [comment]
Happy to read that!

**Comment by bahaaMIMAR** [comment]
This bug is known since Sep 2024 and it has not been fixed yet...
