### ISSUE TITLE
I see wrong version that does not exists yet 5.5.0

### ISSUE THREAD

**Issue by itayasaf2001xd** [meganz/MEGAsync#998]
I download megaSync for the official website here:
https://mega.io/desktop

But I see wrong version that does not exists yet 5.5.0
![image](https://github.com/user-attachments/assets/6b3eb7fa-4441-44ef-939e-918c7caa8da8)

on GitHub release and on my other computer which updated through the update mechanism of the app I see Version 5.4.1

Any idea what is going on?

**Comment by vtmateos** [comment]
Hi,
You have caught us during the process of the release 5.5.0 today :)
During today we will publish source code for that version on github.
Autoupdate for all users will be available on next days.
